### ISSUE TITLE
fastq-dump.2.8.2 err: connection not found while validating within network system module

### ISSUE THREAD

**Issue by BillYates** [ncbi/sra-tools#102]
When I use fastq-dump --split-3, I get the error as follows:
fastq-dump.2.8.2 err: connection not found while validating within network system module
What's wrong?

**Comment by kwrodarmer** [comment]
Basically, this cryptic string is useful if you know how to pick it apart (and you're not expected to know as an end user). It means that while searching for the run to convert, it was not found - or in this case not able to be opened due to a network connection validation error.

The reason you hear "not found" is that the software works hard to try to locate a usable object, and when nothing works, you get something like "no usable object was found." The place that the error was detected was in the networking code.

The significance is that your host was unable to resolve a DNS name needed for downloading the run in question. Specifically, `gethostbyname_r()` returned `HOST_NOT_FOUND` *(assuming you are running on Linux)*.

You should read the page on setting up the firewall (or forward it to your IT group):
https://github.com/ncbi/sra-tools/wiki/Firewall-and-Routing-Information
