### ISSUE TITLE
fastq-dump slow for single cell dbGaP data

### ISSUE THREAD

**Issue by mukamel-lab** [ncbi/sra-tools#104]
I am experiencing very slow transfers using fastq-dump to get dbGaP data (e.g., SRR1764405). Any advice would be appreciated -- it seems to be slow even without any compression. I need to transfer >8,000 SRR files (single cell sequencing) and it has taken 6 days to complete ~2,000 files (each ~150 MB).

time fastq-dump -Z SRR1764405 | head -n 100

real	1m0.737s
user	0m0.228s
sys	0m0.023s

**Comment by klearned** [comment]
@mukamel-lab Have you considered using prefetch instead of fastq-dump to downlaod? I've noticed using prefetch is considerably faster than fastq-dump to download the data, especially if you have the aspera connect installed ([instructions](https://www.ncbi.nlm.nih.gov/books/NBK36439/#Download.download_using_prefetch_command)). After downloading the files with prefetch, I then use fastq-dump to convert from .sra to .fastq files.
