### ISSUE TITLE
sam-dump error: data inconsistent while executing function within transform module

### ISSUE THREAD

**Issue by gymreklab** [ncbi/sra-tools#107]
I am downloading WGS data from dbGAP project phs000424.v7.p2 (GTEx). Prefetch to get SRA files works fine, but on every single file I've run sam-dump on I'm getting an error. Below are the command and the error that are output:

```
prefetch --max-size 200G SRR2156726
sam-dump -u sra/SRR2156726.sra | samtools view -bS > wgs/SRR2156726.bam
```

Error:
```
2017-12-20T14:23:17 sam-dump.2.8.1 int: data inconsistent while executing function within transform module - VCursorCellDataDirect( row#45676305 . idx#8 . READ ) INSDC_dna_text (ptr) failed
[W::sam_read1] Parse error at line 1000357590
```

For most of the files, I am getting all of the chromosomes so it looks like most of the BAM is being created. But in all cases the result BAM file gives me messages about a truncated file. I've tried this command on multiple machines with the same result.

**Comment by osris** [comment]
This is caused by silently hard-clipped secondary placements from BWA-mem.
It was an unexpected change (along with addition of ‘supplemental’ flag) and had bad repercussions to any software that implemented sam-spec.
We did adjust our parsing to deal with this and I thought we had reprocessed these.
SRA stores SEQ and QUAL only once and uses them when dumping secondary alignments. Samtools complains because the sum of cigar operators != length of SEQ

Unless you really want the secondary/supplemental alignments, try using --primary option with the files you have already prefetched. I’ll queue these for reprocessing here.
-Chris


*********************************
Christopher O’Sullivan PhD
Sequence Read Archive
NCBI/NLM/NIH
osulliva@ncbi.nlm.nih.gov
*********************************

**Comment by gymreklab** [comment]
Thanks for the fast response. For now I'll give `--primary` a try.

**Comment by hsiehph** [comment]
Hello,

I got a very similar error when I ran the same command for SRR2167374. For our analysis, we would like to include supplementary reads as well. Is there a way to get the entire BAM? I have been stuck in converting .sra to BAM for two weeks now....

sam-dump -u -r SRR2167374 |  samtools view -bS -@4 - | samtools sort -@4 -T $TMP -o ./BAMs_WGS/SRR2167374.sorted.bam -

Thanks,
Benson

**Comment by klymenko** [comment]
@hsiehph, bam file for SRR2167374 is now available in cold store.

**Comment by klymenko** [comment]
@hsiehph, @gymreklab, do you still need help?

**Comment by hsiehph** [comment]
Thanks for the email. I don't need additional assistance at this time.

**Comment by gymreklab** [comment]
Thanks for sending. No, I no longer need help with this.
Best,
~Melissa
