### ISSUE TITLE
Parameterize the fastq-dump cache location

### ISSUE THREAD

**Issue by sminot** [ncbi/sra-tools#108]
I have a use case where I'm running multiple processes on a single machine, and I'd like to keep track of all of the temp files for each process so that I can clean them up when the process finishes. 

Ideally, I'd like to keep every process within its own temp folder, so that if the job fails I can just delete the temp folder and not worry about knowing exactly which files the process was working on.

When I use fastq-dump as part of that process, I find that it caches an *.sra file in a single location. I'm hesitant to have every running process change the temp folder location, for fear of collisions. 

My suggestion for a new feature would be to parameterize the cache folder location with the fastq-dump command. That way every process could specify its own temp folder at runtime, and never have to worry about a collision.

**Comment by kwrodarmer** [comment]
The difficulty with this suggestion is that these are potentially quite large files. If you run 100 jobs that access the same run, and each run is 250GB in size, well, you see the problem.

**Comment by sminot** [comment]
That's a great point, and actually the motivation behind my suggestion. The OS partition in Docker can be quite small, and fill up quickly with *.sra files if it isn't cleaned up between jobs. 

Just a thought, no need to implement it if it doesn't make sense within the larger project. Thanks for your time.

**Comment by kwrodarmer** [comment]
At this moment we don't have any great solution for cluster computing, largely because without control of how the jobs are run/scheduled, we have no protection against pathological conditions. As mentioned above, we can't afford to cache in private areas, and we have no assurance that people won't throw 10000 jobs at a single run. When constrained to a shared cache area, the latter case causes contention over which job gets to update the cache files, essentially serializing all of the jobs.

What we do is we allow multiple jobs to compete for the cache. We know that the worst case in a collision is to forget some of what was already known, causing multiple retrievals. But eventually the cache files stabilize. At no point should they become inconsistent, however.

Our next release will be increasing the amount of cache in RAM, which may help your situation. The two benefits of caching on disk are 1) to eliminate repeated network retrievals and 2) as a source for future executions. If you are cleaning cache between jobs, then you don't get much benefit from "2", so it may be that turning disk caching off entirely and relying upon RAM cache will be better for you.

That said, it will require release 2.9.0 to operate. Turning off cache today is a bad idea when using networked access!
