### ISSUE TITLE
fastq-dump slows over time

### ISSUE THREAD

**Issue by mchaisso** [ncbi/sra-tools#113]
This issue came up while I was converting a few prefetched .sra files at once. Conversion would happen quickly for the first half or so, then grind to a halt on the filesystem.  It wasn't clear why the files would convert quickly in the beginning, and more slowly over time. I plotted the converted bytes/10 minutes to run fastq-dump --split-reads --gzip SRR1291070.sra here:

![fastq-dump rate](https://user-images.githubusercontent.com/1372990/35030136-d2ec8d2a-fb12-11e7-840a-3c541820f283.png)

The conversion and file sizes are correct.  This issue has to do with the performance.  It is unclear why the conversion rates would taper like this over time.   I'd be curious to see what it is like on your end. I just watch file size like below, and plotted the deltas:

`while [ true ]; do
  ls -l SRR1291070_1.fastq.gz >> SRR1291070_1.fastq.gz.size
  sleep 10m
done
`

**Comment by kwrodarmer** [comment]
This is an interesting test. Have you tried it without gzipping the output? The implication is that fastq-dump is slowing down over time, but you're measuring that by looking at how many compressed bytes are added to the file. In theory, any compressed file that reuses its dictionaries will tend to slow its rate of newly added bits, so I'm not sure it's indicating anything relevant.

fastq-dump (or any tool) could potentially change rate of conversion based upon the data stored within a given run. Unaligned runs will be essentially constant rate, while aligned runs can have different access patterns depending upon how they align. Especially, there is a common trick where people append additional information to the end of a BAM file that can cause a slow down just because it doesn't conform to the patterns within the general data.

**Comment by kwrodarmer** [comment]
How did you download SRR1291070? From your report, it appears that you simply downloaded it using curl/wget/ascp/etc. You didn't use prefetch, I imagine?

Use of `prefetch` is fairly important here, since the run has an associated index that is needed to improve performance. We generate these indices when runs are particularly malformed and generate crazy random access for either sam-dump or fastq-dump.

**Comment by mchaisso** [comment]
I did first download, then I ran prefetch on the locally downloaded file to
generate the index.  Perhaps that was the issue?

**Comment by mchaisso** [comment]
I didn't try without gzip, however one curious thing was that when I tried
to do this with multiple files concurrently, it slowed to a trickle per
file after about 15GB of writing.  The jobs would start with 100% cpu usage
for a few hours, then be down to  < 5% usage after, and have only a few
Mbp/min being generated.  So the access patterns on the file system were
easy in the beginning, and then somehow got progressively more seek
intensive, which is in agreement with your second theory.

**Comment by kwrodarmer** [comment]
I looked at the file, too. It is not a well-formed file and exhibits a lot of random access from its alignments. The fastq file generated is about 212G in size, from the 40G cSRA. Compressing it with gzip took 3 hours, and I observed a fairly stable rate of compression until the last few minutes, when it dropped off considerably.

We have a new tool (_called fasterq-dump_) that is in beta-testing. It trades off memory for speed. It was able to dump this file in less than 78 minutes, using 265GB at its peak.

Some data are simply bad and can throw off the expected access patterns. **fasterq-dump** will not be affected so much by this.

**Comment by mchaisso** [comment]
Good to know I'm not just running things incorrectly.  Thanks for the
reference to the fasterq-dump - all of this is sufficient that the issue is
resolved.

**Comment by holtgrewe** [comment]
Hi.

We did a closer investigation of the fastq-dump tool and what comes up is that a lot of `pread64()` syscalls to 32KB blocks turn up in the `strace` of running the dumping. The problem is even more dominant when reading from a cluster file system such as GPFS as was previously observed. In contrast, tools like `zcat`, `pigz` etc. use `read()` syscalls of 32KB.

My interpretation is that using `pread64()` breaks caching and block prefetching in the operation whereas using `read()` would use this.

HTH

**Comment by kwrodarmer** [comment]
This could be. Most tools use `read()` rather than `pread()`. I consider it a bug that Linux bases the latter on the former rather than the other way around. We rely on the illusion of a STATELESS file descriptor at the lowest levels of our operations. In order to simulate this in user code, we'd have to do much the same as Linux and perform a sequence of:
```
lock;
prior-pos = lseek(0, CUR);
lseek(new-pos, SET);
read();
lseek(prior-pos, SET);
unlock;
```
In order for code to do otherwise requires knowledge or assumption that the fd is never shared across threads, because the marker gets updated by every read operation. Since this code exists in a library (`libncbi-vdb`), there are limits on the assumptions we can make and a near total lack of knowledge. Using `pread()` is a system API that advertises the correct semantics, and in a perfect world might hope for a kernel that implements it properly one day.

We will look at making changes toward `read()` in _VDB-3_ which is a project that is in early stages right now.

**Comment by klymenko** [comment]
Have you tried [fasterq-dump](https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump)?

**Comment by klymenko** [comment]
@mchaisso, do you still need help?
`fasterq-dump` performs much faster that `fastq-dump`.

**Comment by mchaisso** [comment]
No, this can be closed. Thanks!
