### ISSUE TITLE
Configuring vdb-config for Already-Dowloaded Dataset

### ISSUE THREAD

**Issue by DarioS** [ncbi/sra-tools#114]
I downloaded a dbGaP project using the online portal and then I also downloaded an NGC file to decrypt it from the portal. I'm trying to use the vdb-config tool to incorporate the key into SRA tools. I get a prompt "Do you want to change the location?" with Yes and No options, but it's unclear what file or files I'm being asked about and why. If I choose No, then nothing seems to be changed and I get:

> err: encryption key not found while opening manager within virtual file system module

I've already downloaded 1 TB of data, so I tried to change the location to the folder which contains it, but if I try to change the folder setting at the bottom of screen, I get an error that the folder is not empty.

The Decrypting Non-SRA Data section of [GaP FAQ](https://www.ncbi.nlm.nih.gov/books/NBK63512/#Download.are_downloaded_files_encrypted) is also not particularly helpful.

May the UX be improved?

**Comment by kwrodarmer** [comment]
If you have already downloaded 1T of data without the use of the SRA Toolkit, could you point us to where you found the instructions to do this? Data should never be downloaded directly, presuming that's what was done.

Here is a page that gives some information and pointers on using dbGaP data:
https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data

Your message has been forwarded to the dbGaP team. In the meanwhile, I will try to address some of the issues raised.

First, your access to dbGaP is predicated upon having accepted terms that stipulate how you will handle the data in order to preserve confidentiality. You are supposed to have set up a dedicated workspace that does not mix dbGaP data with any other data. Once you have been granted access, the process is supposed to involve download of your NGC file and establishment of the workspace via `vdb-config` (see https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data and https://github.com/ncbi/sra-tools/wiki/Toolkit-Configuration).

`vdb-config` proposes creation of your workspace in a subdirectory of your home directory, because -  where else could it propose, knowing nothing of your system? You are expected to reset the root of the dbGaP workspace to somewhere with sufficient storage and protection. The SRA Toolkit will attempt to own and manage a cache area within this workspace. If you attempt to designate an existing directory with content, the toolkit has no way to determine whether it can take ownership over these files or if they are being managed manually, and so will reject workspaces with a non-empty cache area.

I suggest that you rename the directory where you have already downloaded files, and then follow the process of creating your workspace. Only **then** should you move the downloaded files into the workspace cache. The particular sub-directories are important, and are based upon file type. I can say that files starting with _SRR_ or _ERR_ or _DRR_ belong in the `sra` cache directory, but there are other types that depend upon the class of file you have. If you have questions, I suggest you write to sra-tools@ncbi.nlm.nih.gov, sending the list of file names and we'll try to sort it out.

Once your workspace is configured, you should be working within it, meaning to cd to the root directory or one of its sub-directories. It is not intended that you should work within one of the cache directories. The SRA Toolkit provides a tool called `prefetch` that would have downloaded these files into their correct location. The SRA Toolkit knows how to locate files within the cache for further operation.

We will be releasing a GUI interface to the SRA Toolkit, starting with the ability to manage configuration and to run some trouble-shooting.

**Comment by DarioS** [comment]
Thanks for the clarification. When the approval letter from dbGaP is received, it links to the My Requests tab which contains a checkbox for Available Phenotype and Genotype files and a Create Download Request button. When the button is clicked on, it creates a command using `ascp` for the requested download, which can almost directly be used in a Linux terminal. There's no warning about setting the appropriate destination directory or any recommendation to use `prefetch` instead. In fact, I'd tend to avoid using SRA tools because of the warning "NCBI currently provide dbGaP data only by FASP protocol developed by Aspera". It seems as though Aspera software is the only software to be used. The prerequisite use of `vdb-config` is also not stated. There's just a passing statement "NCBI distributes data encrypted by your project password. To decrypt phenotype data please use NCBI Decryption Tools." if the "How do I decrypt data" link is clicked to expand that section of FAQ above the download link.

The folder swapping trick worked for me, so I do not have to re-download the dataset.

**Comment by kwrodarmer** [comment]
`prefetch` either uses HTTPS or drives `ascp` for downloads, and puts files into the cache locations where they can be found by SRA Toolkit.

But I'm very curious now - you've downloaded a terabyte of Phenotype and Genotype files, with no sequences? That's a lot of data!

**Comment by DarioS** [comment]
Yes, it's a large study called the Framingham Cohort with ID phs000007. It contains a large number of raw microarray measurements files. It's probably not typical of the datasets in dbGaP. Should the dbGaP download page recommend SRA Tools instead of using `ascp` directly?

**Comment by kwrodarmer** [comment]
I'll be meeting with them to discuss the best course of action. You will need SRA Tools in any event for decryption, so it may not be a good idea to put it off.

Let me know if there's anything else for right now, or if we should close the issue.
