### ISSUE TITLE
Retrieve original read names from SRA files

### ISSUE THREAD

**Issue by ghuls** [ncbi/sra-tools#115]
Hi,

Is it possible to retrieve original read names for reads in SRA files?

e.g.:
https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR5453718

From the accompanying paper: https://www.nature.com/articles/nbt.4038
> scTHS-seq data processing.
>
> Raw BCL files were demultiplexed to FASTQ Read1, Index1, and Index2 files with bcl2fastq v2.17.1.14, then used as input to deindexer (https://github.com/ws6/deindexer) with 0 mismatch barcode demultiplexing. Barcode combinations associated with each read were appended to each read header with in-house Perl scripts, and all FASTQ files were combined and mapped to an hg38 no-alternative loci plus decoy reference genome 

To separate single-cell sequencing data, cell barcodes are needed to demultiplex the reads for each cell, sratools removes all this info from the read name and makes a datasets like this useless: https://www.ncbi.nlm.nih.gov/sra?term=SRX2741904

**Comment by kwrodarmer** [comment]
In this case, the original read names are not stored, so there is no read name to be retrieved. In the cases where read names have been stored in the SRA, the tools will retrieve them.

From the standpoint of a general purpose loader, read names are comment fields that typically consume large amounts of storage but contain no more information than a serial number. The case that you mention is one where someone has tried to make use of this comment field to store something of significance, but there's nothing in the FASTQ format(s) to indicate it.

The SRA is composed of ETL'd objects, rather than the files originally submitted. Data contained in specific series that conform to the SRA model are extracted and stored. Unformatted data, often contained in comment portions of the input, have no explicit meaning and cannot be automatically interpreted. Read names generally fall into this category.

**Comment by ghuls** [comment]
@kwrodarmer With which command can you store the original read names in SRA format?

**Comment by kwrodarmer** [comment]
`fastq-load` is a tool that will preserve original read names. These are tools that are run by NCBI to process submitted files. As an SRA consumer, you will not be able to affect this process.

**Comment by klymenko** [comment]
Original fastq-file for SRR5453718 is now available in cold store.
