### ISSUE TITLE
fastq-dump.2.9.0 searching for SRA files in wrong location

### ISSUE THREAD

**Issue by mjinkm** [ncbi/sra-tools#119]
When running the command
`fastq-dump --split-files SRR1609911`
I receive the following error:
```
2018-03-23T15:14:45 fastq-dump.2.9.0 err: file not found while opening file within network system module - Failed to KNSManagerVMakeHttpFileInt('http://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR1609/SRR1609911/SRR1609911.sra' (130.14.250.11)) from '00.000.0.00'
2018-03-23T15:14:45 fastq-dump.2.9.0 err: item not found while constructing within virtual database module - the path 'SRR1609911' cannot be opened as database or table
```

Upon examining the directory structure of ftp-trace.ncbi.nlm.nih.gov, I have determined the SRA file I am attempting to access resides at http://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR160/SRR1609911/SRR1609911.sra rather than at the non-existent http://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR1609/SRR1609911/SRR1609911.sra that fastq-dump is attempting to access.  Is this a known issue, and, if so, how shall I resolve it?

**Comment by kwrodarmer** [comment]
_YOU_ don't resolve anything. `fastq-dump` resolves accessions into paths, and uses neither of the URLs you gave above (they are deprecated/obsolete). Tools in the SRA Toolkit use a name resolution service that returns the _current_ path to an object, which is subject to change without notice.

If you're having any problems such as this, they're more likely related to networking/firewall issues than anything else.

**Comment by mjinkm** [comment]
As you can see in the error message fastq-dump produced, it is attempting to access a non-existent file and failing.  'http://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR1609/SRR1609911/SRR1609911.sra' is the URL it reports attempting to access, which apparently does not exist.  Have you attempted to run `fastq-dump --split-files SRR1609911` ?  I suspect this error is reproducable.

**Comment by kwrodarmer** [comment]
Yes, I have attempted to run the command - it works perfectly. The problem is in your environment.

`fastq-dump` will follow rules in configuration, and it's sounding likely that you are running with old configuration files. We haven't supported http for a long time now (pure https), and we haven't used URLs of the sort you mention for years.

We need to know more about your environment in order to debug this, so I suggest that you run the command:

`test-sra SRR1609911 > test-sra-out.txt 2&>1`

 and send the results to sra-tools@ncbi.nlm.nih.gov where we can help you in your situation.
