### ISSUE TITLE
When will fasterq-dump be available?

### ISSUE THREAD

**Issue by yech1990** [ncbi/sra-tools#122]
I found the manual in wiki page, but could not find any link to download.

**Comment by circlexyy** [comment]
Same question here

**Comment by kwrodarmer** [comment]
We had a delay due to an unrelated project, but we are working on the release now.

Here is the issue - `fastq-dump` is very old, and has support for many technologies that are no longer supported. `fasterq-dump` will not have support for all technologies. We are running tests to ensure that it produces exactly the same output, or where it differs, we want to understand the situation.

As such, we are running `fasterq-dump` against several PB of compressed SRA data to ensure that there are no unknown corner cases. Once we can completely document its behavior, we can release. The actual tool works well now, and for essentially everything we've tested so far, is fine.

**Comment by circlexyy** [comment]
Good to know! Thanks!

**Comment by klymenko** [comment]
@yech1990 , it's available for a long time already!
