### ISSUE TITLE
fastq-dump:   improper read pairing for SRA entries submitted as bam files

### ISSUE THREAD

**Issue by jayoung** [ncbi/sra-tools#123]
Hi there,

We've been having some trouble getting properly formatted paired-end fastq files from a set of (large) accessions.  I think I figured out the problem, and would like to suggest an enhancement that might fix it.

I've been troubleshooting on one accession SRR5125834 (I wish it were smaller - sorry!).   SRA staff member Inna helped me understand that this was submitted as bam (no original fastq available), and  she gave me that bam file by ftp for troubleshooting.   

I run fastq-dump (SRA-toolkit v 2.9.0) like this:
fastq-dump --split-spot --split-files --gzip /fh/fast/malik_h/grp/public_databases/NCBI/SRA/cache/sra/SRR5125834.sra

and it gives us different numbers of reads in the forward and reverse files
SRR5125834_1.fastq.gz	207539871 reads 
SRR5125834_2.fastq.gz	205382673 reads
      total = 412922544 reads

Unfortunately those fastq files are not in a useful format for many downstream applications (e.g. most paired-end read mappers), as those algorithms require the two files for the paired end reads to contain the pairs in the same order as one another, and the pairing information does not currently seem to be retained.  We mapped SRR5125834_1.fastq.gz and SRR5125834_2.fastq.gz back to the mouse genome and found that while most reads did map (>97%), very few of them (<3%) mapped in a properly paired configuration. That's in contrast to >95% properly paired in the submitted bam file, so the problem seems to be in processing, not the original submission.

I think that fastq-dump does accurately output the reads that were present in the submitted bam file.  The issue is probably that while the submitted bam file (according to samtools flagstat) contains a total of 412922544 reads (same number fastq files), only 410765346 of them were "paired in sequencing".   i.e. there are reads in the bam file for which it will be impossible to recover the mate pair from the bam file no matter how it is processed by fastq-dump.  The submitted bam file probably had eliminated most of the unmapped reads, which means the mate pairing is hard to retreieve.

Would it be possible to add an option to fastq-dump so that it only extracts reads that have the "read paired" bit flag set in the SAM flag?   I think this would yield fastq files where the read number and order in the forward and reverse files match one another, although I'm not able to test it (it may depend on how the Illumina-style read names get processed into SRA-style shorter names when the bam file SRA submission is processed). 

Hope I'm making sense - please let me know if that sounds like nonsense. (and apologies if there's already a way to get well-paired fastq files and I'm missing it)

thanks very much,

Janet Young

------------------------------------------------------------------- 

Dr. Janet Young 

Malik lab
http://research.fhcrc.org/malik/en.html

Division of Basic Sciences
Fred Hutchinson Cancer Research Center
1100 Fairview Avenue N., A2-025, 
P.O. Box 19024, Seattle, WA 98109-1024, USA.

tel: (206) 667 4512
email: jayoung  ...at...  fredhutch.org

-------------------------------------------------------------------

**Comment by osris** [comment]
Janet,
fastq-dump has "--split-3" option that outputs singletons to a separate fastq file (SRR5125834.fastq) SRR5125834_1.fastq and  SRR5125834_2.fastq are still produced and will have matching mate-pair sort order.
apologies, i talked to Inna about your question a couple days ago and i missed the point entirely. i had checked that the bam was loaded correctly, and forgot that the actual issue was sort order. for this run, the first 'singleton' occurs at spot 26, so sort order would be lost almost immediately. reference aligners just rip the names and pass them to the output, never checking or complaining if they don't match. 

-Chris

Christopher O’Sullivan PhD
Sequence Read Archive 
NCBI/NLM/NIH
osulliva@ncbi.nlm.nih.gov

**Comment by jayoung** [comment]
Excellent - thanks, Chris! Should I use split-3 as well as split-files, or instead?

I skipped reading that option in the help when I saw "legacy" - that was a mistake on my part.   I was also a bit confused at first as I didn't know what  "biological reads" and "technical reads" were. I think I know now - are the technical reads the bar codes in situations where they exist?    

Is it worth re-phrasing the help for the "--split-3" option in "fastq-dump -help"?  It's a bit opaque right now. What does "Biological reads and above are ignored" mean?

I'm curious - what happens if we use the "--split-3" option on a dataset where properly paired fastq files were submitted and bam files were not submitted?   I'm wondering if I can use that option every time I run fastq-dump, without checking first whether alignments exist or whether there are singletons present.  

thanks,

Janet

**Comment by osris** [comment]
use split-3 instead of split-files. you can use it every time. it will only produce the 3rd file if there are orphans/singletons to put there. sometimes fastq files contain full complement of mate-pairs, but one mate is flagged low quality or is very short. split-3 filters out the short and low quality reads leaving the other mate orphaned. 
your interpretation of Biological read is correct. regardless of how data is submitted, SRA stores all bases from a "spot" as a single string with read boundaries set to separate technical reads (barcodes, linkers, 454 leader sequence,...) from the Biological read(s). 

fastq-dump was written waaay back when 1000 genomes project was doing a lot of technology evaluation. split-3 was added for 1000 genomes to address exactly the issue you had.  the help output needs to be fixed.

**Comment by ttriche** [comment]
When I use --split-3 instead of --split-files, I often end up with
curiously misnamed files:

# ...
SRR1395000_pass.fastq.gz        SRR563985_pass_1.fastq.gz
SRR1395000_pass??_??.fastq.gz   SRR563985_pass_2.fastq.gz
SRR1395002_pass??a??.fastq.gz   SRR564083_pass.fastq.gz
SRR1395002_pass.fastq.gz        SRR564083_pass????.fastq.gz
# ...

This does not seem like optimal default behavior.




--t

**Comment by osris** [comment]
@ttriche i've never seen that. what OS and filesystem?

**Comment by ttriche** [comment]
Linux (CentOS 7) and GPFS


--t

**Comment by jayoung** [comment]
Chris - thanks again: we now have properly paired fastq files for those two datasets- very happy!    (no weird file names here)
