### ISSUE TITLE
NCBI SRA-tools sam-dump taking excessive lengths of time 

### ISSUE THREAD

**Issue by Sames-Jtudd** [ncbi/sra-tools#126]
Hi, 

I'm trying to extract .bam files from SRA files downloaded from dbGAP. First off, thanks to whom ever provides the service and administers everything it is a great resource. Sorry for the long message.

I have some specific and general comments about SRA files and SRA-tools. I'll start with the specific ones. 

Im using the command "sam-dump SRRn.sra | samtools view -bS - > SRRn.bam"

As suggested in the SRA tools manual.

The length of time it is taking to extract bam files from SRA files is so large that it is borderline not viable.
I have download a number of SRA files in the order of 180GB and I have had jobs running for 65 ish hours which have extracted bam files of roughly 30GB. This is using one CPU/core Intel Xeon Haswell and 256GB of RAM per job. CPU utilisation is only around 10% and the process is I/O bound. 
  
As a demo I did this on an SRA file that is only around 35GB to get an idea of how long this process will take. The extracted bam files was 54GB. Now I understand that compression rates are not necessarily the same between two files but this suggests it will take roughly 25days to extract the bam from a 180GB SRA.  

When I said earlier " borderline not viable" revise that to totally unviable. 

Comparing fastq-dump to sam dump suggests that the later is faster. So it doesn't seem to make any sense to extract and re align. 

I can throw more resources at it but the cost implication is a concern.  I have 300 ish .sras to extract

What is unusual is that when extracting the 35GB sra  it took 'only' 6 hours with the same resources, suggesting that the time taken to extract is not proportional to the SRA file size , but maybe exponential? Maybe this have something to do with the resulting bam being sorted.

If so can I disable the 'sort' element of sam-dump as it doesn't sort it in the manner which I would like anyway (1,2,3,4,5 etc). 

If there was anyway I might speed this process up I would be grateful for any tips. 

More general issues, 

It frustrating that you can't see the contents of an SRA file before downloading it.  You don't know ; the size or what it contains. Also it seems to me that there is little point in bundling fastq and sam files in one sra. Why would you ever want both? Its wasteful in terms of downloading excessive data. 

If the fastq or bam were available separately it would make more sense to me.     

Are there any other tools that can handle SRA files? In terms of extracting them? It is an unusual format that I have never seen anyone else use, maybe Im wrong. 

thanks 

jamie

**Comment by kwrodarmer** [comment]
Hello @Sames-Jtudd - thank you for your comments.

Since your complaints are specific to your experience, which is specific to the set of runs you are working on, yet your description is generic, let me first address that. Different technologies tend to produce wildly different behaviors. For example, Complete Genomics tends to produce data that are very difficult to extract due to the amount of random access.

In general, CPU activity will be related to decompression, I/O will be related first to the random access patterns occasioned by your request and later by bulk of data. For example, if you are accessing an unaligned run as fastq, it will be a straight dump with little random access. Remember that aligned data produce multi-dimensional structures.

When we started the SRA, there were a larger number of actively used data formats and new technologies were appearing frequently. The SRA uses VDB technology to store run _information_ in a database, rather than a format per se. The resulting run sits as the representational hub of many format spokes, making it possible to ingest data from any format and produce a common form, from which you can generate other forms. But the intended way of accessing data is directly via APIs that we have published in various forms for a decade.

The VDB objects do not contain fastq and also SAM - they contain read, quality, reference, and alignment records along with a lot of other metadata as well as technology specific data in a single database unit.

Back to the issue of performance, you will find that if you take a BAM file and convert it to SAM, or vice versa, the process will run at I/O bound speed as expected. This is because you are using it natively, rather than trying to convert it to some other format that would require re-indexing and randomly assembling pieces into different shapes in different orders.

The question about whether there are any other tools that can read SRA's VDB objects, the answer is unfortunately *no*, in spite of the fact that we have encouraged tool authors to do so for a decade. But extracting data from SRA and transforming it to another format just so that your desired tool can operate is close to being the most backward thing that could be done. Wouldn't it make more sense if your aligner would just read the SRA objects directly? That's what should be happening and much to the detriment of the community, doesn't happen enough.

There _are_ aligners such as *Hisat2* that read SRA directly. There is also a version of GATK that reads SRA directly. These should be examined.

A few years ago, we published a simple API for accessing reads called *NGS* (https://github.com/ncbi/ngs.git). It provides bindings for 3 languages (Python, Java, C++), and is quite simple to use (and in fact is used by Hisat2 and GATK). Using the API and VDB columnar database storage of SRA, these tools can access basecalls independently of qualities, for example. Did you know that 80% of your storage in an aligned run is dedicated to quality values? The vast majority of time that is taken for your operations comes from reassembling basecalls and qualities into a single unit record, just so that your aligner can summarily ignore the qualities for the majority of its work.

We hear several claims about how _valuable_ quality values are, but this is mostly folklore. Quality values account for the majority of storage, and they provide an unreliable indication of anything. How can an aligner actually use them? At best they can be fed to a comparator function that produces a single bit of output - use or discard. At worst, they are not used because the aligner already has enough evidence based upon coverage depth and consensus at an alignment, rendering them superfluous. The unfortunate reality is that if they _are_ used, it's to compensate for cases where there is a lack of evidence to support a hypothesis, and this violates the principles of science. If you don't have enough evidence to support your claim, you are obligated to either obtain more evidence or back off.

You would find that if you could leave out qualities, your jobs would work much better. If your intention is to realign, you don't need BAM, and you shouldn't need qualities. Dumping to FASTA would be a better option if your tool chain supported it.

For these reasons, we have developed the `fasterq-dump` tool which trades off memory for speed. It essentially creates temporary tables and performs joins on them. The older `fastq-dump` on the other hand, performs its joins on much smaller buffers which inevitably results in higher random access, that can be devastating depending upon the original technology. We announced this tool a few months ago, but its release has been delayed due to an interruption of testing, caused by resource constraints. With the risk of sounding like a broken record, we anticipate its release in May.

Suggestions:
1. use Hisat2
2. write a Python script to access data however you want using the NGS API
3. dump data as FASTA
4. wait for `fasterq-dump`

**Comment by Sames-Jtudd** [comment]
Hi, thank you for replying so quickly and in so much detail. 

I was not aware that was how SRA files worked. I was also not aware GATK or others could use the files directly. 

The files are already aligned and from Complete Genomics so perhaps that contributes to the time and I/O issues.  

I will try to use them directly with GATK. 

many thanks 

Jamie

**Comment by Sames-Jtudd** [comment]
Thanks again, 

I have searched https://github.com/ncbi for any reference to GATK and could find none.

Sorry to pester but if you could you provide a link to the SRA compatible GATK version you are referring I would be grateful. 

many thanks

**Comment by kwrodarmer** [comment]
You can find a link on either of our two download pages:
https://github.com/ncbi/sra-tools/wiki/Downloads
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software

The specific download link is
https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.9.0/GenomeAnalysisTK.jar

**Comment by Sames-Jtudd** [comment]
Hi me again, 

sorry to be a pain. Im still having issues, if you had any ideas for a pointer, I'd be grateful. 

So I've down loaded https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.9.0/GenomeAnalysisTK.jar

and when trying to execute the command 
java -jar GenomeAnalysisTK.jar ect..ect.

I get an error message saying 
'no main manifest attribute, in GenomeAnalysisTK.jar'

A quick search suggests that I need an MANIFEST.MF file as per 
http://roufid.com/no-main-manifest-attribute-in-app-jar/ 

So I basically did this but the problem persists. 

I have  java/sun6/1.6.0u45 and  java/sun7/1.7.0u80 installing on my HPC cluster and I get the same error message with either. There is no other documentation on the pages you kindly provided so Im out of ideas. 

thanks

**Comment by klymenko** [comment]
It is a bug and we will fix it.

Meanwhile, run `java -cp GenomeAnalysisTK.jar`

**Comment by Sames-Jtudd** [comment]
Thanks for the quick reply.

I may have noticed another bug, or maybe I'm doing it wrong, its hard to know for sure. 

This is the command I'm executing ; 
java -cp GenomeAnalysisTK.jar -T HaplotypeCaller 
-R /pathtref/human_g1k_v37.fasta 
-I /pathtosomeSRA/SRR5115250.sra
-O /pathtosomeVCF/SRR5115250.vcf 

And I get the output 
"Unrecognized option: -T
Could not create the Java virtual machine."

On the GATK page (https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_engine_CommandLineGATK.php) it says
 
Here is a list of commands (the first of which is -T) that should work with almost every version of GATK.

thanks again

**Comment by kwrodarmer** [comment]
The version of GATK we have is 3.6.6 - you should look for documentation on that version or use the help command.

**Comment by klymenko** [comment]
Try instead:

`java -cp GenomeAnalysisTK.jar org.broadinstitute.gatk.engine.CommandLineGATK -T HaplotypeCaller -R /pathtref/human_g1k_v37.fasta -I /pathtosomeSRA/SRR5115250.sra -o /pathtosomeVCF/SRR5115250.vcf`

Your should be in the project's workspace directory.

**Comment by klymenko** [comment]
[GenomeAnalysisTK.jar](https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/GenomeAnalysisTK.jar) was updated.
You can execute it as `java -jar GenomeAnalysisTK.jar` .

**Comment by Sames-Jtudd** [comment]
Hi, you must be sick of me by now, having spoken to the gays and gals at GATK, apparently SRA files are supported in versions 3.8 onwards.

I would rather use the most up to date version of GATK for obvs reasons. So I tried to run the command in v4

gatk --java-options "-Dsamjdk.sra_libraries_download=true" HaplotypeCaller -R /path/reference_genomes/human_g1k_v37.fasta -I SRR5115250.sra -O SRR5115250.vcf 

 This gives an error, the nub of the issue is printed here, a more fulsome list of the error see below.

"Exception in thread "main" gov.nih.nlm.ncbi.ngs.error.LibraryNotFoundError: Failed to load 'ngs-sdk' - No installed library was found, auto-download failed - connection problem
Please check your network connection, and check if you need proxy configuration. Contact your IT department or email sra-tools@ncbi.nlm.nih.gov for assistance.
…
Caused by: gov.nih.nlm.ncbi.ngs.error.cause.ConnectionProblemCause: auto-download failed - connection problem"
 
Can you see what the problem is? I've emailed my HPC gurus who say the issue is not at our end?
 
Thanks 
 
James 

again your help is much appreciated
 
The whole command and  output is here 
 
gatk --java-options "-Dsamjdk.sra_libraries_download=true" HaplotypeCaller -R /mnt/scratch/DGE/MOPOPGEN/jstudd/jstudd/reference_genomes/human_g1k_v37.fasta -I SRR5115250.sra -O SRR5115250.vcf
Using GATK jar /opt/gridware/apps/gatk/4.0.0.0/gatk-package-4.0.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsamjdk.sra_libraries_download=true -jar /opt/gridware/apps/gatk/4.0.0.0/gatk-package-4.0.0.0-local.jar HaplotypeCaller -R /mnt/scratch/DGE/MOPOPGEN/jstudd/jstudd/reference_genomes/human_g1k_v37.fasta -I SRR5115250.sra -O SRR5115250.vcf
19:18:12.628 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/gridware/apps/gatk/4.0.0.0/gatk-package-4.0.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
19:18:25.499 INFO  HaplotypeCaller - ------------------------------------------------------------
19:18:25.500 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.0.0.0
19:18:25.501 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
19:18:25.502 INFO  HaplotypeCaller - Executing as jstudd@dav001.prv.davros.compute.estate on Linux v3.10.0-327.3.1.el7.x86_64 amd64
19:18:25.503 INFO  HaplotypeCaller - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_66-b17
19:18:25.503 INFO  HaplotypeCaller - Start Date/Time: 23 April 2018 19:18:12 BST
19:18:25.503 INFO  HaplotypeCaller - ------------------------------------------------------------
19:18:25.503 INFO  HaplotypeCaller - ------------------------------------------------------------
19:18:25.504 INFO  HaplotypeCaller - HTSJDK Version: 2.13.2
19:18:25.504 INFO  HaplotypeCaller - Picard Version: 2.17.2
19:18:25.505 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 1
19:18:25.505 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
19:18:25.505 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
19:18:25.505 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
19:18:25.505 INFO  HaplotypeCaller - Deflater: IntelDeflater
19:18:25.506 INFO  HaplotypeCaller - Inflater: IntelInflater
19:18:25.506 INFO  HaplotypeCaller - GCS max retries/reopens: 20
19:18:25.506 INFO  HaplotypeCaller - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
19:18:25.506 INFO  HaplotypeCaller - Initializing engine
java.io.IOException: Server returned HTTP response code: 403 for URL: http://trace.ncbi.nlm.nih.gov/Traces/sratoolkit/sratoolkit.cgi
ngs-java: Failed to download ngs-sdk from NCBI
ngs-java: Loading of ngs-sdk library failed
INFO    2018-04-23 19:18:26     SRAAccession    SRA initialization failed. Will not be able to read from SRA
19:18:26.586 INFO  HaplotypeCaller - Shutting down engine
[23 April 2018 19:18:26 BST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.23 minutes.
Runtime.totalMemory()=1526202368
Exception in thread "main" gov.nih.nlm.ncbi.ngs.error.LibraryNotFoundError: Failed to load 'ngs-sdk' - No installed library was found, auto-download failed - connection problem
Please check your network connection, and check if you need proxy configuration. Contact your IT department or email sra-tools@ncbi.nlm.nih.gov for assistance.
        at gov.nih.nlm.ncbi.ngs.LibManager.loadLibrary(LibManager.java:335)
        at gov.nih.nlm.ncbi.ngs.Manager.<init>(Manager.java:103)
        at gov.nih.nlm.ncbi.ngs.NGS.<clinit>(NGS.java:120)
        at htsjdk.samtools.sra.SRAAccession.checkIfInitialized(SRAAccession.java:96)
        at htsjdk.samtools.sra.SRAAccession.isValid(SRAAccession.java:138)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.isSra(SamReaderFactory.java:438)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:403)
        at htsjdk.samtools.SamReaderFactory.open(SamReaderFactory.java:105)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:227)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:162)
        at org.broadinstitute.hellbender.engine.GATKTool.initializeReads(GATKTool.java:318)
        at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:556)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:160)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)
Caused by: gov.nih.nlm.ncbi.ngs.error.cause.ConnectionProblemCause: auto-download failed - connection problem
        at gov.nih.nlm.ncbi.ngs.LibManager.searchLibrary(LibManager.java:658)
        at gov.nih.nlm.ncbi.ngs.LibManager.loadLibrary(LibManager.java:332)

**Comment by kwrodarmer** [comment]
@Sames-Jtudd - can you send a summary of your discussions with the GATK people to us at sra-tools@ncbi.nlm.nih.gov?

**Comment by Sames-Jtudd** [comment]
So the problem appears to be with the link 
http://trace.ncbi.nlm.nih.gov/Traces/sratoolkit/sratoolkit.cgi
 which returns 'Illegal type of request' when you browse to it.
It doesn't seem possible to download this file manually from this either?
If I had the file locally I assume that GATK would work? Is there any way to download this?

**Comment by kwrodarmer** [comment]
The problem is **not** with the cgi. Please understand that the SRA Toolkit and NGS work for millions of people across the globe. The issue is explained in our README.md:

> IMPORTANT ANNOUNCEMENT
> 
> As was announced in OMB memorandum M-15-13 on June 8, 2015, NCBI and all Federal systems will  be transitioning to using *HTTPS-only protocols before the end of 2016*. This change will affect any software that uses NCBI APIs such as the E-utilities or NCBI software toolkits such as sra-tools, ncbi-vdb or ngs.

GATK is using an old version of NGS that does not use HTTPS when connecting to Federal systems, such as the CGI you mention. My interest in hearing about your contact is so that I can talk with them to coordinate their obtaining the latest NGS.

The GATK we make available is also old, but it uses the latest NGS. What we need is to each upgrade to each other's latest version.

**Comment by kwrodarmer** [comment]
In the meantime, we should have the ability to cause your old NGS to stop trying to contact NCBI to check for software updates. You should install the latest *ncbi-vdb* and *ngs* packages on your system, and then you may have some text files to edit.

I'll ask the engineer who wrote that particular portion of NGS to provide specific instructions. @klymenko, could you answer whether this is possible, and if so, explain the steps necessary to keep the old NGS Java code from seeking the latest software and instead use a manual installation?

**Comment by Sames-Jtudd** [comment]
Thanks for the link

So I extracted that file and used the java options you provided and I have the same error.

‘Caused by: Failed to load 'ngs-sdk' - Library is incompatible, NGS auto-download is disabled’

Any ideas appreciated.

Thanks

Full output here

gatk --java-options "-Djava.library.path=ngs-sdk.2.9.0-linux/lib64" HaplotypeCaller -R pathtoref/GCF_000001405.25_GRCh37.p13_genomic.fna -I SRR5115250.sra -O SRR5115250.vcf

Using GATK jar /opt/gridware/apps/gatk/4.0.3.0/gatk-package-4.0.3.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Djava.library.path=ngs-sdk.2.9.0-linux/lib64 -jar /opt/gridware/apps/gatk/4.0.3.0/gatk-package-4.0.3.0-local.jar HaplotypeCaller -R /mnt/scratch/DGE/MOPOPGEN/jstudd/jstudd/reference_genomes/refseq_build_GRCh_37p13/ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.25_GRCh37.p13/GCF_000001405.25_GRCh37.p13_genomic.fna -I SRR5115250.sra -O SRR5115250.vcf
11:11:40.110 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/gridware/apps/gatk/4.0.3.0/gatk-package-4.0.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
11:11:50.352 INFO  HaplotypeCaller - ------------------------------------------------------------
11:11:50.353 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.0.3.0
11:11:50.354 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
11:11:50.355 INFO  HaplotypeCaller - Executing as jstudd@dav002.prv.davros.compute.estate on Linux v3.10.0-327.3.1.el7.x86_64 amd64
11:11:50.355 INFO  HaplotypeCaller - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_66-b17
11:11:50.356 INFO  HaplotypeCaller - Start Date/Time: 30 April 2018 11:11:40 BST
11:11:50.356 INFO  HaplotypeCaller - ------------------------------------------------------------
11:11:50.356 INFO  HaplotypeCaller - ------------------------------------------------------------
11:11:50.356 INFO  HaplotypeCaller - HTSJDK Version: 2.14.3
11:11:50.357 INFO  HaplotypeCaller - Picard Version: 2.17.2
11:11:50.357 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
11:11:50.357 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:11:50.358 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:11:50.358 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:11:50.358 INFO  HaplotypeCaller - Deflater: IntelDeflater
11:11:50.358 INFO  HaplotypeCaller - Inflater: IntelInflater
11:11:50.358 INFO  HaplotypeCaller - GCS max retries/reopens: 20
11:11:50.358 INFO  HaplotypeCaller - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
11:11:50.358 INFO  HaplotypeCaller - Initializing engine
ngs-java: DLL download was disabled
ngs-java.2.9.0: Loading of ngs-sdk library failed
INFO    2018-04-30 11:11:51     SRAAccession    SRA initialization failed. Will not be able to read from SRA
11:11:51.616 INFO  HaplotypeCaller - Shutting down engine
[30 April 2018 11:11:51 BST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.19 minutes.
Runtime.totalMemory()=1534066688
Exception in thread "main" java.lang.LinkageError: Failed to load SRA native libraries and auto-download is disabled. Please re-run with JVM argument -Dsamjdk.sra_libraries_download=true to enable auto-download of native libraries
        at htsjdk.samtools.sra.SRAAccession.isValid(SRAAccession.java:141)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.isSra(SamReaderFactory.java:449)
        at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:414)
        at htsjdk.samtools.SamReaderFactory.open(SamReaderFactory.java:105)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:227)
        at org.broadinstitute.hellbender.engine.ReadsDataSource.<init>(ReadsDataSource.java:162)
        at org.broadinstitute.hellbender.engine.GATKTool.initializeReads(GATKTool.java:318)
        at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:556)
        at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:160)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:132)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: Failed to load 'ngs-sdk' - Library is incompatible, NGS auto-download is disabled
Please enable auto-download or install ngs and ncbi-vdb manually: https://github.com/ncbi/ngs/wiki/Downloads
Library path: ngs-sdk
        at gov.nih.nlm.ncbi.ngs.LibManager.loadLibrary(LibManager.java:386)
        at gov.nih.nlm.ncbi.ngs.Manager.<init>(Manager.java:103)
        at gov.nih.nlm.ncbi.ngs.NGS.<clinit>(NGS.java:120)
        at htsjdk.samtools.sra.SRAAccession.checkIfInitialized(SRAAccession.java:96)
        at htsjdk.samtools.sra.SRAAccession.isValid(SRAAccession.java:138)
        ... 14 more
Caused by: gov.nih.nlm.ncbi.ngs.error.cause.DownloadDisabledCause: NGS auto-download is disabled
        at gov.nih.nlm.ncbi.ngs.LibManager.searchLibrary(LibManager.java:750)
        at gov.nih.nlm.ncbi.ngs.LibManager.loadLibrary(LibManager.java:332)
        ... 18 more

**Comment by klymenko** [comment]
I gave you a different instruction.
Use `https://ftp-trace.ncbi.nlm.nih.gov/sra/ngs/1.3.0/ngs-sdk.1.3.0-linux.tar.gz` , not `2.9.0` .

**Comment by Sames-Jtudd** [comment]
Nice editing. 

That's all working now. Thank you for your help I do appreciate it. 

Hopefully the next version of GATK will be updated accordingly, I cant help but think this should have been easier.
