### ISSUE TITLE
strange downloads

### ISSUE THREAD

**Issue by stueber** [ncbi/sra-tools#133]
When I download SRA data sets with fastq-dump strange things
happen.

First trial:
fastq-dump -Z ERR2040600 > ERR2040600.fastq
Results in a fastq formatted file where the forward and reverse reads are appended.

Second trial:
fastq-dump -Z ERR2040600 -split-3 > ERR2040600.fastq
Results not in splitted files but in a single interleaved fastq formatted file where
the forward and reverse reads are separate and given the same name and not
marked with 1 or 2.

Both versions are useless. 

Sorry, this tool should be improved or at least issue some warnings when it does
meaningless things.

Kurt

**Comment by klymenko** [comment]
Remove -Z option.

**Comment by stueber** [comment]
OK.
fastq-dump ERR2040600 -split-3 > ERR3040600
now produces three files: ERR2040600_1.fastq, ERR2040600_2.fastq and ERR2040600,
the last one with some log messages.

fastq-dump ERR3040600 > ERR3040600
still silently produces a pasted file...

well, some improvement :-)

**Comment by kwrodarmer** [comment]
> still silently produces a pasted file...

What is a "pasted" file, in this case?

```
fastq-dump ERR3040600 > ERR3040600
```
You don't want to be using any shell redirection: the command you want is just
```
fastq-dump --split-3 ERR3040600
```
That will improve the tool even more!

**Comment by stueber** [comment]
Dear kwrodarmer,

with a "pasted file" I mean that forward and reverse reads are fused to result in a pseudoread:

Korrekt:

@ERR2040600.1 FCC0CG3ACXX:8:1101:1718:1875 length=90
NATCATCAGGTTGTACAAAAATATCTTTTTTTCATCAATCCAAAGCTACAAAAAGGTTTTATGAGATTAAAAAGGTCCGTTGAGCGCCTC
+ERR2040600.1 FCC0CG3ACXX:8:1101:1718:1875 length=90
#1=DDFFDHHHHHHIIJJJJJJJJIIJJJJJJGDHGGIIIJGIJJJJJJIJJGIJJFHIIJJIEHHHFHFFFFFDEEEDBDDDDDDDDDD
@ERR2040600.1 FCC0CG3ACXX:8:1101:1718:1875 length=90
CTCCCATTTCTCTATTTTCTTTAGTTCTTTACTAGAGCAATTATGATCTGGAAGTCGATCCGGGGCAAGTGTTCGGATCTATTATGACAT
+ERR2040600.1 FCC0CG3ACXX:8:1101:1718:1875 length=90
@CCFFEFFHHHHHIJJIJJJJJJJIJIJJJIIJJJHJJJJJJGIJGIJIIIIIJHIIIJJJJIJJJGHHEFFFFDDDDDDDEEDDDDDDD

Here both reads are kept separate

but the "pasted"  version looks like this:

@ERR2040600.1 FCC0CG3ACXX:8:1101:1718:1875 length=180
NATCATCAGGTTGTACAAAAATATCTTTTTTTCATCAATCCAAAGCTACAAAAAGGTTTTATGAGATTAAAAAGGTCCGTTGAGCGCCTCCTCCCATTTCTCTATTTTCTTTAGTTCTTTACTAGAGCAATTATGATCTG
GAAGTCGATCCGGGGCAAGTGTTCGGATCTATTATGACAT
+ERR2040600.1 FCC0CG3ACXX:8:1101:1718:1875 length=180
#1=DDFFDHHHHHHIIJJJJJJJJIIJJJJJJGDHGGIIIJGIJJJJJJIJJGIJJFHIIJJIEHHHFHFFFFFDEEEDBDDDDDDDDDD@CCFFEFFHHHHHIJJIJJJJJJJIJIJJJIIJJJHJJJJJJGIJGIJII
IIIJHIIIJJJJIJJJGHHEFFFFDDDDDDDEEDDDDDDD

This of course is only found out hours later after you tried to map these "reads" to the reference genome.

greetings

Kurt

**Comment by kwrodarmer** [comment]
Ah, now I understand. These are what NCBI calls "**spots**" and they were the original default access mode for **fastq-dump**. They can contain technical as well as biological reads. An example of such a sequence can be found in SFF format.

**fastq-dump** is one of our oldest tools, and has accumulated a _lot_ of option over the years. Many were driven by the thousand-genome project. The default means of generating fastq was to retrieve the entire sequence as it was stored in SFF. There are options to split the _spot_ into reads, and options to exclude technical pseudo reads. None of the options can be changed, nor can the default, because thousands of people across the world use this tool in automated pipelines.

We are introducing a new fastq tool where the default is essentially the _split-3_ behavior, and makes better use of modern hardware. Once it is released, we will make an announcement.

**Comment by stueber** [comment]
In the Wikipedia article about the FASTQ-format (see https://en.wikipedia.org/wiki/FASTQ_format)
you can see the following sentences:

Citation:
"Notably in the above output the paired-end information was lost when the data was extracted from the NCBI SRA using fastq-dump with default settings.

Further to note, with newer fastq-dump the extracted sequences have double-length and it turns out fastq-dump concatenates sequence of the forward and reverse reads together into non-sense."

End citation.
So others have noticed this behaviour also :-)

It is OK this this program can not be changed, but appropiate messages should appear in the log-files.
thanks four your replies.

Kurt

**Comment by kwrodarmer** [comment]
Well, it seems you are in good company then!
