### ISSUE TITLE
fastq-dump cache

### ISSUE THREAD

**Issue by igordot** [ncbi/sra-tools#15]
I noticed that if I specify an accession number with fastq-dump, it will download the intermediate SRA files into ~/ncbi/public/sra. Is there a way to change that directory? Also, is there a way to automatically delete those files upon successful FASTQ generation?

**Comment by kwrodarmer** [comment]
See the [Toolkit-Configuration](https://github.com/ncbi/sra-tools/wiki/Toolkit-Configuration) page. This will explain both how to disable caching altogether and how to establish a root directory for the cache. Note that we do not currently attempt to move or salvage current cache, so if you change the directory, previous contents will be orphaned there. If you intend to change directory, you can use `cache-mgr` to empty out the current location beforehand.

There are no commands for automatically discarding cached files after use because they can be used by multiple tools, and across multiple sessions. You can clean up cache using the `cache-mgr` tool.

**Comment by Zepeng-Mu** [comment]
I am having the same question. What are the differences between `.sra` and `.sra.cache` files? I am getting "disk quota exceeded" error when using fastq-dump, does this mean that the downloading has failed?

**Comment by kwrodarmer** [comment]
Yes - when you have exceeded your disk quota, that is typically within the cache area.

When you access any part of an SRA file, it will be entered into your designated workspace cache directory with an extension of `.sra.cache` which shows it is a partial file. If you access enough of the data to complete the entire file, it will be renamed `.sra` without the `.cache` extension. This indicates a complete standalone file.

These files are cached in your workspace, which by default will be within your home directory. Almost nobody has enough space in their home, so it is important to configure your toolkit immediately to tell it where to place these files.

**Comment by Zepeng-Mu** [comment]
Thanks! I got several `.sra.cache`, but the size of `fastq.gz` does not seem to be significantly from those with `.sra`. Also, the downloading process was not halted even with disk quota exceeded error.

**Comment by Adonyo-Emmanuel** [comment]
The best approach is to switch off the local cache policy from the SRA toolkit:
use this "./vdb-config -i" from the bin directory and achieve your configurations.
Thank you

**Comment by kwrodarmer** [comment]
@Adonyo-Emmanuel - different cases warrant different measures. For some people working on most runs with a reasonable network, it makes sense to use on-demand retrieval. This is especially true if performing slicing or other operation that would be penalized without on-demand retrieval and caching. I'd caution against giving out this advice without qualifying when it makes sense and when it doesn't.

With version 2.10.0, we introduced a new caching scheme designed to work better with cloud storage. The 2.9.x series was designed to work with POSIX file systems and during this year we saw a shift to object stores for the SRA itself.
