### ISSUE TITLE
Unhelpful Error Message in `VDBManagerOpenDBRead`

### ISSUE THREAD

**Issue by Miserlou** [ncbi/sra-tools#150]
```
Shell call to fasterq-dump failed with error message: 2018-09-18T18:05:02 fasterq-dump.2.9.1 err: cmn_iter.c cmn_iter_open_db().VDBManagerOpenDBRead( 'ERR517891.sra' ) -> RC(rcVFS,rcMgr,rcOpening,rcDirectory,rcNotFound)
2018-09-18T18:05:02 fasterq-dump.2.9.1 err: sorter.c run_producer_pool(): row_count == 0!
fasterq-dump.2.9.1 err: sorter.c execute_lookup_production() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
2018-09-18T18:05:02 fasterq-dump.2.9.1 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
```

We're having occasional failures when calling `fasterq-dump` on pre-downloaded files. We get the above error message - what does it mean? The file exists on disk, and there is even a check that the file exists in the script which invokes fasterq-dump.

Also, I'm not sure if this is a red herring or not, but it seems like the vast, vast majority of samples which have these errors are `ERR`, not `SRR`.  Does these files come from different servers?

What's going on here?

**Comment by kwrodarmer** [comment]
Hi @Miserlou ,

Would you mind providing the command line exactly as you typed it? If you want it to remain confidential, you can take this offline by writing to sra-tools@ncbi.nlm.nih.gov .

It is possible that the ERRs have more problems than the SRRs, only due to the potential difference in source files and loading mechanism. It will not be related to different servers.

Let us get your command line and we can try to reproduce your issue here. Thanks!

**Comment by Miserlou** [comment]
Thanks for the quick reply!

The command invoked is pretty simple, ex:

```
fasterq-dump /var/ebs/ERP009909/ERR963186/ERR963186.sra -O /var/ebs/processor_job_2185
```

although it's run inside of a Docker container. Most annoyingly, the problem is intermittent, although frequent.

**Comment by Miserlou** [comment]
More specifically - what does this error actually mean? It seems like all of the logging inside this project is not human-friendly.

**Comment by kwrodarmer** [comment]
So the current version of `fasterq-dump` has difficulty with explicit paths containing the `.sra` extension. The convention for our tools is to utilize VDB name resolution. We will address it in the next release.

For now, you can get things to work by renaming your SRA files to remove the `.sra` extension or place them in the designated workspace and utilize VDB name resolution.

**Comment by kwrodarmer** [comment]
The error report means something to us, but doesn't give you any actionable information, it's true. This tool is still being refined and emits outputs even more cryptic than others, but in general most of our tools emit rather tersely coded error information.

Yet the very first line states that when trying to find ERR517891.sra, the result is that it cannot be found locally or via any network service. With this line alone we are able to see that the tool has extracted the leaf file name instead of using the entire path (bug), and did not fully extract the accession (ERR517891). It tells us that in this case, we need to respect the path you gave to the object and not concern ourselves with the name for purposes of locating input.

For purposes of output, the tool is looking only at the leaf name. Perhaps it should strip the `.sra` from the leaf name before creating `.fastq` output, and this is another outstanding issue we have.

The remaining lines give very specific information that is helpful only to the developer of the tool.

**Comment by Miserlou** [comment]
This apparently worked! Most of the time!

Thanks for your swift reply.

**Comment by Rachael-rq** [comment]
I just would like to point out that this issue seems still there for version2.9.4 and  2.10.0
`2019-11-20T20:32:19 fasterq-dump.2.9.4 err: cmn_iter.c cmn_iter_open_db().VDBManagerOpenDBRead( 'SRR8454764.sra' ) -> RC(rcVFS,rcMgr,rcOpening,rcDirectory,rcNotFound)
2019-11-20T20:32:19 fasterq-dump.2.9.4 err: sorter.c run_producer_pool(): row_count == 0!
2019-11-20T20:32:19 fasterq-dump.2.9.4 err: sorter.c execute_lookup_production() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
2019-11-20T20:32:19 fasterq-dump.2.9.4 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
`

**Comment by dfguan** [comment]
Hello, 

Still have this error in fasterq-dump 2.10.8,  we are using the following command to dump the sra, 

```
fasterq-dump --split-3 -e 6 -O SRAs/SRR7107871/SRR7107871.sra
```
but it pops out this error message: 

fasterq-dump.2.10.8 err: cmn_iter.c cmn_iter_open_db().VDBManagerOpenDBRead( 'SRR7107871.sra' ) -> RC(rcVFS,rcMgr,rcOpening,rcDirectory,rcNotFound). 
fasterq-dump.2.10.8 err: sorter.c run_producer_pool(): row_count == 0!
fasterq-dump.2.10.8 err: sorter.c execute_lookup_production() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
fasterq-dump.2.10.8 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid) 
fasterq-dump quit with error code 3

We have no clue to solve it, so we would be grateful if you can help. 

Thanks, 

Dengfeng.

**Comment by roni-fultheim** [comment]
Same here, 
fasterq-dump.2.10.8 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)

Prefetched sra files from dbGaP fine, cannot convert into FASTQ
