### ISSUE TITLE
Some fasterq-dump executations run forever / take an extremely long time

### ISSUE THREAD

**Issue by Miserlou** [ncbi/sra-tools#159]
We're executing a _lot_ of fasterq-dumps. Some small percentage of these appear to get caught in infinite loops, or at least very-long loops. A normal fasterq-dump only takes a few hours, but this one appears to be going on for nearly 3 hours.

![screen shot 2018-10-03 at 11 35 40 am](https://user-images.githubusercontent.com/139987/46421793-eb83a200-c700-11e8-8424-4097d919b5e9.png)

Any ideas what might cause this?

**Comment by kwrodarmer** [comment]
I have an idea, but have not tested it. The content of this run contains a large amount of trailing Ns. And now, a little background.

`fasterq-dump` attempts to replicate many of the behaviors of `fastq-dump`. The latter performs single-spot operations, including spot assembly and filtering based upon quality values, sequence length, and N content. This is not an enormous extra burden on `fastq-dump` because it is not streamlined for any other than individual spot processing.

`fasterq-dump` is faster precisely because it performs bulk retrieval and joins. It would really prefer to simply deliver the contents of the run, rather than doing you the favor of filtering them on output. I hypothesize that the amount of filter processing it has with runs like this are degrading its performance into something closer to the older tool.

We can test this next week.

**Comment by Miserlou** [comment]
Not completely related, but I've been able to 2x fasterq-dump speed by using a temporary ramdisk:

```
ubuntu@ip-10-0-40-173:~/ramdisk$ time ./sratoolkit.2.9.2-ubuntu64/bin/fasterq-dump SRR2063294 -O /home/ubuntu/ramdisk/out/ --temp /home/ubuntu/ramdisk/temp/
spots read      : 22,149,672
reads read      : 44,299,344
reads written   : 44,299,344

real    2m1.476s
user    3m56.148s
sys    0m40.960s
ubuntu@ip-10-0-40-173:~/ramdisk$ rm out/*
ubuntu@ip-10-0-40-173:~/ramdisk$ time ./sratoolkit.2.9.2-ubuntu64/bin/fasterq-dump SRR2063294 -O /home/ubuntu/ramdisk/out/ --temp /home/ubuntu/ramdisk/tmpfs/
spots read      : 22,149,672
reads read      : 44,299,344
reads written   : 44,299,344

real    0m54.802s
user    2m55.784s
sys    0m28.636s
```

**Comment by klymenko** [comment]
@Miserlou, did you `prefetch` first? Do you still need help?
