### ISSUE TITLE
dbGap access controlled fastq-dump not working

### ISSUE THREAD

**Issue by inodb** [ncbi/sra-tools#16]
Using version 2.5.4 binaries on MacOS 64 bit
```bash
$ for f in prefetch fastq-dump; do $f --version; done  | grep 2
prefetch : 2.5.4
fastq-dump : 2.5.4
```
I can download public SRA fastq files:
```
$ fastq-dump -X 5 -Z SRR390728 2> /dev/null | head -1
@SRR390728.1 1 length=72
```
But somehow access controlled dbGaP data is not working:
```
$ [~/ncbi/dbGaP-8463] fastq-dump -X 5 -Z SRR988442
2015-09-30T21:12:14 fastq-dump.2.5.4 err: item not found while constructing within virtual database module - the path 'SRR988442' cannot be opened as database or table
```
The prefetching is working:
```
$ [~/ncbi/dbGaP-8463] prefetch -v SRR988442
2015-09-30T20:26:41 prefetch.2.5.4: 1) Downloading 'SRR988442'...
2015-09-30T20:26:41 prefetch.2.5.4:  Downloading via http...
[..]
2015-09-30T20:27:39 prefetch.2.5.4: 1) 'SRR988442' was downloaded successfully
```
But I can't fastq-dump the resulting file:
```
$ [~/ncbi/dbGaP-8463] fastq-dump -Z -X 5 ./sra/SRR988442.sra
2015-09-30T21:30:05 fastq-dump.2.5.4 err: item not found while constructing within virtual database module - the path './sra/SRR988442.sra' cannot be opened as database or table
```
Any clue?

**Comment by inodb** [comment]
This is the result from vdb-validate:
```
$ vdb-validate --verbose /Users/debruiji/ncbi/dbGaP-8463/sra/SRR988442.sra
2015-09-30T21:32:57 vdb-validate.2.5.4 info: Validating  encrypted file '/Users/debruiji/ncbi/dbGaP-8463/sra/SRR988442.sra'...
2015-09-30T21:32:57 vdb-validate.2.5.4 info: Encrypted file '/Users/debruiji/ncbi/dbGaP-8463/sra/SRR988442.sra' appears valid
2015-09-30T21:32:57 vdb-validate.2.5.4 err: path not found while opening directory within file system module - Failed to VFSManagerOpenFileReadDecrypt(/Users/debruiji/ncbi/dbGaP-8463/sra/SRR988442.sra)
```

**Comment by kwrodarmer** [comment]
From what you wrote, it's not clear that you are executing fastq-dump or vdb-validate from within the dbGaP protected workspace. This is required for the tools to be able to locate the decryption key.

**Comment by inodb** [comment]
Thanks for the prompt reply. Updated the cmd line prompt in the previous messages to show the working directory.

**Comment by kwrodarmer** [comment]
From the same directory, please run the tool "test-sra" and capture stdout to a text file, and send it to sra-tools@ncbi.nlm.nih.gov (rather than posting it here).

**Comment by klymenko** [comment]
unset VDB_PWFILE

**Comment by inodb** [comment]
Excellent! That worked like a charm! Thanks a lot for fixing this so quickly

**Comment by kwrodarmer** [comment]
Somewhere on the web, a rumor was started that using $VDB_PWFILE was a solution to something. For anyone else reading this, please do not try to use this as a solution. *Everyone* should unset this variable in their environment.

**Comment by pchines** [comment]
One should also unset other VDB_* environment variables, e.g. VDB_CONFIG.  In my case fastq-dump was working, but prefetch was not, for a dbGaP protected file, with error message "path not found while resolving tree - cannot get cache location for SRR..."  Clearing the VDB_CONFIG environment variable made it work.

**Comment by bartg01** [comment]
I'm suffering exactly the same issue as inodb (but in linux and with version 2.5.7). I tried to unset VDB_PWFILE but still not solved, any other idea?
Thanks in advance.

**Comment by kwrodarmer** [comment]
If you have read all of the documentation and are still having a problem, then we should take an approach of diagnosing the issue. If you have not yet read our documentation, then please start with that.

Otherwise, document the relevant portions of your shell session in a text file and send it to sra-tools@ncbi.nlm.nih.gov . We need to see the working directory and the exact command line and exact response from the tools. Typically, from the same directory, we recommend running the tool `test-sra` that will check out your configuration, your network, accessibility of NCBI, and in the case of controlled access, your keys.

**Comment by kwrodarmer** [comment]
There are several problems.

1. You are using Ubuntu and downloaded the latest software, but didn't "install" it in any way, so the tools are not in your $PATH.
2. You have an old installation of the SRA Toolkit (2.3.5) that used to come with Ubuntu that is there and in your $PATH. It is taking over all operations, and it is obsolete software that will no longer work.
3. You copied `fastq-dump` to a new location. I can't tell from the description whether you brought over the entire directory, including its configuration, or just the tool. You need to update $PATH to get it to work the way you want.

The most up-to-date documentation on SRA Tools can be found on this GitHub repository. Look at our Wiki to get help on using dbGaP.

**Comment by modarzi** [comment]
@kwrodarmer 
Hi, 
Thanks for your comment. 
1-based on your advise, I add fastq-dump directory in the PATH. Now when I run _env_ then I see below:

OLDPWD = /home/cli-sim01/ncbi/dbGaP-12485/sratoolkit.2.9.2-ubuntu64/bin

So, can I done your first advise correctly?

2- For your second comment, I can't understand your mean. because I downloaded latest version of sratoolkit from below link:
https://www.ncbi.nlm.nih.gov/sra/docs/toolkitsoft/
and in that link, under "NCBI SRA Toolkit latest release compiled binaries and md5 checksums" I downloaded "Ubuntu Linux 64 bit architecture". For this reason, I think my sratoolkit must be latest version.am I say wrong?
3- For your 3rd comment, could please give me more explanation?

I deeply appreciate if you share your comment with me.

Best Wishes,
Mohammad

**Comment by kwrodarmer** [comment]
You should obtain the software from https://github.com/ncbi/sra-tools/wiki/Downloads .

If you have updated the `$PATH` environment variable, you should see that in your environment - you have shown `$OLDPWD`. I don't see evidence of having set up `$PATH`.

The SRA Toolkit relies upon configuration. Since most of our users are unable to install the toolkit "properly" without administrator privileges, we often locate our configuration based upon the location of the tools. If you were to move the tool without also moving its configuration files, the tools will no longer be able to locate them. You can see more at:
https://github.com/ncbi/sra-tools/wiki/Toolkit-Configuration
