### ISSUE TITLE
Error using fasterq-sump.2.9.2 - block-size in local file 131072 does not match requested value

### ISSUE THREAD

**Issue by voichek** [ncbi/sra-tools#165]
Hi,

I am using fasterq-dump with the following command:
`fasterq-dump -t /X/tmp SRR5663958 -e 8`

And I get the following massages:
1. Many time I get this massage: `2018-11-22T15:44:10 fasterq-dump.2.9.2 warn: block-size in local file 131072 does not match requested value 32768`
2. `system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )`

Is it a cause for concern, or can I just disregard it?

Best,
Yoav

**Comment by ArdaCet** [comment]
I am having the same warning, when I try to run the fastq-dump. However, it seems its downloading converting the sra file to fastq.

**Comment by kwrodarmer** [comment]
@voichek - It helps us to try to keep our support tickets to the current release. We've just released 2.10.5. Could you update to the latest version?

The tool will present a summary of its processing results. If the tool completes execution and presents its results, and especially if its exit code is 0, then you can be assured that no hard-errors have occurred. We run into a high number of network-related errors that are reported when observed to help diagnose problems, but at the same time our code works very hard to work around these problems and usually is able to back up and retry failing operations until they succeed.

Again, the clue you are looking for is the report at the end of the run. If you don't get there, it would mean the tool had aborted due to an error. If you do, then you can be confident in its message.

**Comment by kwrodarmer** [comment]
also see: https://github.com/ncbi/sra-tools/wiki/Network-and-Connection-Errors

**Comment by klymenko** [comment]
@voichek , do you still need help?
