### ISSUE TITLE
"reset by peer" failures

### ISSUE THREAD

**Issue by jimkress65** [ncbi/sra-tools#174]
I'm using prefetch.2.9.2 on a Win 7 Pro workstation.  I'm trying to download SRA files.  I keep getting the "reset by peer" error.  Here is an example of my command line output:

I:\NCBI_Data\January\bin>prefetch -X 200G cart_XXX.krt
Downloading kart file 'cart_XXX.krt'
Checking sizes of kart files...

Downloading the files...

2019-01-27T01:40:43 prefetch.2.9.2: 5) Downloading 'XXX'...
2019-01-27T01:40:43 prefetch.2.9.2:  Downloading via https...
2019-01-27T02:18:59 prefetch.2.9.2 sys: connection canceled while reading file w
ithin network system module - mbedtls_ssl_read returned -80 ( NET - Connection w
as reset by peer )
2019-01-27T02:18:59 prefetch.2.9.2 int: connection canceled while reading file w
ithin network system module - Cannot KStreamRead: https://gap-download.be-md.ncb
i.nlm.nih.gov/sragap/x
2019-01-27T02:19:02 prefetch.2.9.2: 5) failed to download XXX

I:\NCBI_Data\January\bin>

What do I do to fix this?

Also, when I execute the prefetch command, I get this window popping up twice:

![image](https://user-images.githubusercontent.com/20668486/51797111-f7253800-21cb-11e9-8be6-41eb39e007bf.png)

Thanks.

Jim Kress

**Comment by jimkress65** [comment]
Interesting to note, if I use the https url (for example https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/8C839F67-AC75-47C2-AD67-02CD619837CD/SRR3147065) the file downloads with no problem.

**Comment by kwrodarmer** [comment]
The **SRA Toolkit** uses a different mode of accession typically than do the _wget_ and _curl_ style tools, but our servers are able to handle this without issue. This is known to not be true for all proxies, however, and the fact that you report `prefetch` getting shut down by _the server_ on every attempt hints that it might not be our server you are actually talking with.

We cannot know from the report above what is really going on, other than to say that there is clear evidence that it is happening **outside** of our tools _(connection reset by **PEER**)_ and that, I'm afraid, is the Wild, Wild West. We have a tool called `test-sra` that will probe for many of the conditions known to cause problems. I suggest you run this tool and send the output to our mailing address: sra-tools@ncbi.nlm.nih.gov .

Incidentally, posting the information as you did is in violation of your dbGaP usage agreement, since you revealed sensitive information to the world. Any time you have dbGaP-related questions that involve sending transcripts of sessions or other types of sensitive information, you should never post it on social media but send it directly to our mailing address.

**Comment by kwrodarmer** [comment]
I probably should have pointed you to our Wiki page about network errors. It's not complete, but there are a few things explained:

https://github.com/ncbi/sra-tools/wiki/Network-and-Connection-Errors

**Comment by jimkress65** [comment]
Thanks for your reply.

"When you say that you used the https URL, it's not clear what you mean by "use". What tool was used to retrieve it?"

I copy and pasted the URL in the error message into the address box of my browser (Firefox) and hit <ENTER>.  The download started immediately

I'll run the test-sra tool and send you the info.

I do not believe the dbGaP data was at risk since no one else has the security key necessary to access the data.  Nor did I know I could send the error message directly to your mailing address.  

However, I understand your concern and will not post that info again.  It was my understanding that completeness of understanding of the necessitated that info.  I will be sure to transmit any additional information in the manner you requested.  I also modified my post to remove the offending information.

**Comment by kwrodarmer** [comment]
> I do not believe the dbGaP data was at risk since no one else has the security key necessary to access the data.
You are correct, and I did not mean to sound bureaucratic about it. Technically, there currently are two levels to the security surrounding dbGaP objects, where one is the authority to access downloaded data that remains private as you mention, and the other is the authority to download, which you did reveal. It's best to keep both of them private.

But to the issue, I see that you just used your browser as a user-agent. So now we need to examine more about your environment to see if you have direct access to our servers or are being proxied, etc. The transcript shows quite clearly that every attempt by `prefetch` is being dropped by whatever server is answering the call for a connection. It's **possible** that this is on our end, since dbGaP servers have more stages involved, and we would need to look at this possibility. It's also possible that there could be some other software in the middle that we don't know about.

**Comment by jimkress65** [comment]
No.  I do not use a proxy.  I use a software firewall on my workstation and a hardware firewall for my internet connection.  My ISP is my cable company.

FYI, I have been able to download dbGaP data with earlier versions of the sra-toolkit.  I never had any issues like this.  My only concern was the very slow speed of transmission.

**Comment by kwrodarmer** [comment]
Okay, thanks. To help you further _(if you need any help)_, please write us by email and we can go further during the week. To improve download speeds, you can try using the Aspera mode of `prefetch` if you haven't already.

**Comment by jimkress65** [comment]
The problem with Aspera  is (afaik) it costs money and I cannot afford it.

**Comment by kwrodarmer** [comment]
The aspera client is free. You can install it for your web browser and it will be available for `prefetch` to utilize.

**Comment by jimkress65** [comment]
Thanks for the help.  I obtained and installed the correct aspera software and it appears to be working.
