### ISSUE TITLE
[fasterq-dump] problem with memory size

### ISSUE THREAD

**Issue by krostifangers** [ncbi/sra-tools#177]
Hello
I tried to download SRX647501 genome reads. I used fasterq-dump to do it, with -t option directed to a SSD with more than 900Gb available and a -O option directed to the same SSD in another folder. See below the following command-line : 
fasterq-dump SRX647502 -t /media/krostif/OTHER_DATA/temp/ -O /media/krostif/OTHER_DATA/Truffes/ -x -p
I first get this message (following the -x option)
cursor-cache : 5,242,880 bytes
buf-size     : 1,048,576 bytes
mem-limit    : 52,428,800 bytes
threads      : 6
scratch-path : '/media/krostif/OTHER_DATA/temp/'
output-format: FASTQ split 3
output-file  : '/media/krostif/OTHER_DATA/Truffes/SRX647502.fastq'
output-dir   : '/media/krostif/OTHER_DATA/Truffes/'
join   :|-------------------------------------------------- 100.00%
concat :|------------------- 38.06%
When fasterq-dump tried to concatenate files, I got the following error : 
2019-01-31T14:53:38 fasterq-dump.2.9.3 err: file excessive while writing file within file system module - system file too large error
2019-01-31T14:53:38 fasterq-dump.2.9.3 err: file excessive while writing file within file system module - system file too large error
2019-01-31T14:53:38 fasterq-dump.2.9.3 err: copy_machine.c push2q().KQueuePush() -> RC(rcCont,rcQueue,rcInserting,rcQueue,rcReadonly)
38.08%2019-01-31T14:53:48 fasterq-dump.2.9.3 err: you have exhausted your space
2019-01-31T14:53:49 fasterq-dump.2.9.3 err: file excessive while writing file within file system module - system file too large error
It probably has something to do with cursor-cache, buf-size or mem-limit, but I do not know how to change these parameters
How to fix it please?
Thank you in advance
Christophe
PS : I'm on a Debian 9 Stretch with 8 CPU and 32 Gb RAM

**Comment by kwrodarmer** [comment]
Your **first** problem actually starts with the fact that you are using an _experiment_ accession rather than a _run_ accession. You should be trying to dump **SRR1508529** rather than the SRX. That will change things.

Try that and see what happens about memory.

**Comment by krostifangers** [comment]
thank you for your quick answer. However when I try with the Run name, I get the following error
fasterq-dump SRR1508529 -t /media/krostif/OTHER_DATA/temp/ -O /media/krostif/OTHER_DATA/Truffes/ -x -p
2019-02-01T14:40:35 fasterq-dump.2.9.3 err: path invalid while creating directory within file system module - error with https open 'https://sra-download.ncbi.nlm.nih.gov/traces/sra20/SRR/001473/SRR1508529'
2019-02-01T14:40:35 fasterq-dump.2.9.3 err: invalid accession 'SRR1508529'

I do not understand, as the https address works on my web browser ...
thank you for your help
Christophe

**Comment by kwrodarmer** [comment]
Can you ensure that the paths you provided are good, especially that they exist?
``mkdir -p /media/krostif/OTHER_DATA/temp /media/krostif/OTHER_DATA/Truffes``
I assume you must have already, but the error being reported is actually saying that the tool is attempting to create a new directory - quite possibly in the temporary space - where it will be writing files, and that an OS error is returned while creating the directory. The OS is saying that the path provided is invalid, which is something that can occur if the path is really bad or if some portion of it is missing.

What the tool will be doing internally is the programmatic equivalent of running `mkdir`. So as an example: If I were to be in some current directory _(say, my $HOME directory)_ and executed
``mkdir blah`` 
it would probably work as long as blah didn't already exist. But if I tried
``mkdir blah/blah2`` it would **fail** to create `blah2` due to the fact that `blah` didn't exist. I suspect that this is what's happening. The tool is likely to be trying to create a directory under one of the paths you gave but that one of the parent directories is missing. Since I didn't write the tool, I don't have the details of what's happening there, so this is speculation.
