### ISSUE TITLE
fasterq-dump for win64

### ISSUE THREAD

**Issue by jimkress65** [ncbi/sra-tools#179]
Why is there no version of fasterq-dump in the win64 distribution package?  It's in the Linux package but not Windows.

**Comment by kwrodarmer** [comment]
It's just a matter of support. The main use case for fasteq-dump has been for larger Linux hosts. Better stated, it is aimed at pipelines rather than personal computers. Your interest has been noted, and if we get enough requests, we can evaluate working on the Windows port.

**Comment by jimkress65** [comment]
Unfortunately, the specification/ documentation for the sra-tools led me to believe fasterq-dump was available in the Win64 download package.  In as much as my work is wholly contained on a Win 7 Pro workstation and I was counting on the fasterq-dump to generate the fastq files now,  is there a way I can get a win64 version?  Can I compile a version from source code using Microsoft Visual Studio ?

Thanks.

**Comment by ghrasko** [comment]
I also register my interest for fasterq-dump for win64.

**Comment by 7670367** [comment]
I am also interested in fasterq-dump for Win64. Also, please note the lack of fasterq-dump for Win64 in the documentation for fasterq-dump (https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump), so that people don't have to spend time googling this problem only to learn it doesn't exist. Thanks.

**Comment by klymenko** [comment]
2.11.0 release includes fasterq-dump for Window. Please try.
