### ISSUE TITLE
ascp: failed to open ssh session., exiting.

### ISSUE THREAD

**Issue by hrafehi** [ncbi/sra-tools#187]
Hi,

I am trying to use aspera-connect-3.1.0 to download data from dbGAP, in linux. However, I am getting the following error:

```
ascp: failed to open ssh session., exiting.

Session Stop  (Error: failed to open ssh session.)
```

I have used this version successfully in the past. Any thoughts on why this is happening?

Thanks,

Haloom

**Comment by klymenko** [comment]
Please mail your question to sra-tools@ncbi.nlm.nih.gov

**Comment by kwrodarmer** [comment]
Please utilize the `prefetch` tool for retrieving data. See

https://github.com/ncbi/sra-tools/wiki/HowTo:-Access-SRA-Data

For several years now we have been advising against the direct use of `ascp` for many reasons. Now there is another reason that we need to document...

For the moment, you should only use prefetch to retrieve files. The issue you are running into is that some data are being stored on media that is not amenable to Aspera's protocol. For these files, prefetch will use `https` rather than `fasp` protocol.
