### ISSUE TITLE
The problems about fasterq-dump 

### ISSUE THREAD

**Issue by wloof** [ncbi/sra-tools#203]
Hi,
The problems are about fasterq-dump.

1. If I sed the temp dir. `--temp` will clear the temp dir, maybe it was a  potential disaster.
`-t|--temp`   where to put temp. files dflt=curr dir

2. Is it possible to add a "-A" option to the `fasterq-dump`? Although this has been indicated in the documentation, it is only a suggestion.

3. I am facing the following problem.
I have downloaded the sra file via `prefetch` and need to convert it to fq format via `fasterq-dump`. When `prefetch` downloads the sra files, it has already downloaded additional sequence files needed. 
But, when I use `fasterq-dump`, I still have problems with the network.
Is it possible to set the `fasterq-dump` to directly use the locally downloaded file?

> 2019-05-15T14:29:15 fasterq-dump.2.9.1 err: cmn_iter.c cmn_read_String( #95529358 ).VCursorCellDataDirect() -> RC(rcNS,rcNoTarg,rcValidating,rcConnection,rcNotFound) 
2019-05-15T14:29:15 fasterq-dump.2.9.1 err: sorter.c write_to_store().pack_read_2_4na() failed RC(rcVDB,rcNoTarg,rcWriting,rcFormat,rcNull)                         12.92%
2019-05-15T14:29:16 fasterq-dump.2.9.1 sys: connection not found while validating within network system module - Failed to Make Connection in KClientHttpOpen to 'sra-download.ncbi.nlm.nih.gov:443'
2019-05-15T14:29:16 fasterq-dump.2.9.1 err: connection not found while validating within network system module - error with https open 'https://sra-download.ncbi.nlm.nih.gov/traces/refseq/CM000685.1'                                                                                                                                      ------ 24.95%
2019-05-15T14:29:26 fasterq-dump.2.9.1 err: sorter.c run_producer_pool().join_and_release_threads -> RC(rcVDB,rcNoTarg,rcWriting,rcFormat,rcNull)             24.99%
2019-05-15T14:29:27 fasterq-dump.2.9.1 err: sorter.c execute_lookup_production() -> RC(rcVDB,rcNoTarg,rcWriting,rcFormat,rcNull)
merge  : 
2019-05-15T14:29:27 fasterq-dump.2.9.1 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcWriting,rcFormat,rcNull)

**Comment by kwrodarmer** [comment]
It is difficult to advise you based upon the description you gave. If you download runs first using `prefetch`, it should download any reference sequences that are required. From what you gave us, you are missing `CM000685.1` which should have been downloaded by prefetch. If you tell us more about how you downloaded, it may help. If you downloaded under a different account from the one you are trying to `fasterq-dump` under, this could be the problem.

We can try to look more at the issue tomorrow, but in the meantime you may want to use the latest version (2.9.6) rather than what you have, since it has several improvements and bug fixes.

**Comment by wloof** [comment]
> 
> 
> It is difficult to advise you based upon the description you gave. If you download runs first using `prefetch`, it should download any reference sequences that are required. From what you gave us, you are missing `CM000685.1` which should have been downloaded by prefetch. If you tell us more about how you downloaded, it may help. If you downloaded under a different account from the one you are trying to `fasterq-dump` under, this could be the problem.
> 
> We can try to look more at the issue tomorrow, but in the meantime you may want to use the latest version (2.9.6) rather than what you have, since it has several improvements and bug fixes.

Only some of the error information is shown above.
When using prefetch to download the sra file, any reference sequences that are required have been downloaded, included `CM000685.1`.
But, I test the  latest version (2.9.6), there is no problem.
And the version(2.9.1) also have no problem.

**Comment by kwrodarmer** [comment]
If you have downloaded the run using `prefetch` and you claim it downloaded `CM000685.1` and have configured your toolkit and are running `fasterq-dump` under the same account as you used to `prefetch`, then `fasterq-dump` would be finding `CM000685.1` locally and not going out to the network. As you showed above, it is attempting to go out to the network, which means `CM000685.1` can't be found locally, which means it either wasn't downloaded, wasn't fully downloaded, was put in some other place, or downloaded under some other account.

Please `cd` to the same working directory used when you ran `fasterq-dump`, run the following command (substitute the run accession for $ACC)
`` 
test-sra $ACC > test-sra-output.txt 
`` 

Send the output file `test-sra-output.txt` to us at sra-tools@ncbi.nlm.nih.gov and we will take it from there.

**Comment by kwrodarmer** [comment]
Hello @wloof ,

We received your email - thank you. We were unable to respond because somehow your return address was not useable. But here is the response we tried to send:

The report shows that you are missing the reference files.

Now please run the prefetch command again, and send us the shell output as a text file, like this:

`` 
prefetch SRR3182447 > prefetch-out.txt 2>&1 
`` 

Then, you can send the "prefetch-out.txt" file to sra-tools@ncbi.nlm.nih.gov

Thank you,
SRA Toolkit Team
