### ISSUE TITLE
a little question about prefetch when using ascp model

### ISSUE THREAD

**Issue by xiaoshen19930901** [ncbi/sra-tools#207]
when i using this command

nohup prefetch  -t ascp --max-size 1000G -a  "/home/sjshen/.aspera/connect/bin/ascp|/home/sjshen/.aspera/connect/etc/asperaweb_id_dsa.openssh" --option-file SRR_Acc_List.txt &

the error is 
2019-07-10T08:35:23 prefetch.2.8.1 err: file not found while copying file - cannot download 'SRR065639' using requested transport

https can work but ascp can not.
I have used before, it could be right

so what is the problem ???

thank you !!!!

**Comment by kwrodarmer** [comment]
The problem is that the run you requested is not available for access by ascp.


The SRA is a living database and constantly changing. The surprise here is that this run now resides within storage that cannot be served by Aspera. HTTPS is your transport of choice.


SRA Toolkit Team

________________________________
