### ISSUE TITLE
How to use MSVS build the sra-tools

### ISSUE THREAD

**Issue by linjiahao962889027** [ncbi/sra-tools#210]
When I use MSVS build the sra-tool, the MSVS told me that "It can't find the source file kapp/main, can't find the source file klib and can't find the source ...". So I want to know how to use MSVS build it. Because of my teacher's request, I need to read the code of fastq-dump. So I hope who can give me some help. Thank you !!!

**Comment by aboshkin** [comment]
sra-tools depends on 2 other repositories, ngs and ncbi-vdb (see the links below). Please clone them side by side with sra-tools and build them (first ngs, then ncbi-vdb) using the same combination of configuration and platform (e.g. Debug/x64) as you intend to use for sra-tools.

[(https://github.com/ncbi/ngs)]
[https://github.com/ncbi/ncbi-vdb]

**Comment by linjiahao962889027** [comment]
> sra-tools depends on 2 other repositories, ngs and ncbi-vdb (see the links below). Please clone them side by side with sra-tools and build them (first ngs, then ncbi-vdb) using the same combination of configuration and platform (e.g. Debug/x64) as you intend to use for sra-tools.
> 
> https://github.com/ncbi/ngs
> https://github.com/ncbi/ncbi-vdb

Thank you very much. But I have an another problem about it, I use the VS2019 to open the ngs-sdk.sln(VS2013), then I use VS2019 "Retarget solution", but it still always shows "ERROR (code: MSB8020)"，the explain is that" The build tools for Visual Studio 2013 (Platform Toolser = 'v120' ) cannot be found. To build using the v120 build tools, please install Visual Studion 2013 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution"". But today I don't know how to install the build tools, the visual studio installer does not provided the build tools or visual studio 2013.

**Comment by aboshkin** [comment]
@linjiahao962889027 , I am afraid the toolkit cannot be readily built with MSVS2019. Please keep in mind that we do not officially support building from source files on Windows. We publish executables built internally using MSVS2013, and, as a courtesy to developers who want to attempt to build from source on Windows at their own risk, we maintain and source control the project files for MSVS2010 and MSVS2013.  

It appears that since you are tasked with reading the code of fastq-dump, actually building it is not necessary. However, if you must build a working executable and have no access to a MSVS2010 or MSVS2013 installation,, I suggest you turn to Linux, where building from source files is supported. Note that Windows 10 has Linux subsystem built in; it can be used to build and run the tools.

**Comment by linjiahao962889027** [comment]
Thank you very much. You are right, I only need to know the code of the "fastq-dump". Because my teacher hope me can write a program to analysis the "SNP/indel"(the whole process), I need to read the code to know how to get the fastq files from SRA files. Thank for your help, very very thank you. @aboshkin
