### ISSUE TITLE
Fasterq-dump not finding SRA files sometimes - invalid accesion

### ISSUE THREAD

**Issue by aleighbrown** [ncbi/sra-tools#215]
This happened to me previously, but when I tried again a few hours later it seemed resolved. 

`fasterq-dump.2.9.6 err: path not found while creating directory within file system module - error with https open 'https://sra-download.ncbi.nlm.nih.gov/traces/sra73/SRR/008051/SRR8244477
fasterq-dump.2.9.6 err: invalid accession 'SRR8244474`

However, this is a valid acession, I'm sure of it.

Running on a cluster, so that could be the source of error, not sure

**Comment by kwrodarmer** [comment]
The accession is valid. We'll investigate.

**Comment by aleighbrown** [comment]
Any news on this? 

I'm also geetting the same error with fastq-dump

**Comment by kwrodarmer** [comment]
Please be patient - most of my team is on vacation, those that remain are in the middle of an intense release. Sorry for the delay.

**Comment by aleighbrown** [comment]
No worries, it appears to be working again this afternoon. Like I said the problem seems to be intermediatant. 

We're in the UK and it's running on a kind of shakey cluster; so this could very well be a problem on our end, just found the error message itself kind of confusing if it was some kind of connection issue.

**Comment by karolisr** [comment]
I am getting the same error still. Here is the command I am running:

`fasterq-dump --threads 4 --split-3 --outdir . --temp . SRR2899626`

**Comment by wraetz** [comment]
Other than the network issues we are having:
Please note:

  1.  –split-3 is default on fasterq-dump (but not on fastq-dump), you can omit it
  2.  –outdir . is not recommended, just omit it
  3.  –temp . is also not recommended, just omit it ( fasterq-dump will use a temp. subdir in your working directory and delete it after it is done )

**Comment by chatterjee89** [comment]
Just provide the path and you should get it.
If you're in the folder with the file, add ./ before the SRA file and fasterq-dump should recognize it:
`fasterq-dump ./SRR8949135`

That's how I got it.

**Comment by klymenko** [comment]
@aleighbrown , do you still have this issue?

**Comment by eam12** [comment]
I am having the same issue. I successfully downloaded the files for accession number ERR3181874 20 minutes ago, but now when I try I get: 

> 2020-07-06T22:18:04 fasterq-dump.2.10.4 err: invalid accession 'ERR3181874'

I'm using sra-tools version 2.10.4 and the code I'm using is:

`fasterq-dump ERR3181874 --split-files --skip-technical --threads $PBS_NP`

The exact same thing also happened to me earlier today when I was doing a trial download of SRR000001.

**Comment by bsiranosian** [comment]
We're having this issue as well on 2.10.8. 

It would also be great to have a fix to https://github.com/ncbi/sra-tools/issues/146 so this error can be caught easily.

**Comment by Davidwei7** [comment]
Hello, I am having the similar problem with the previous posts.

I downloaded the Sra files with prefetch command, and now doing the sra to fastq conversion with fasterq-dump. 

My command worked fine half hour ago, but the temp files were stored at home directory which does not have enough space. So I used -t parameter to changed to the scratch place, then re-run it with the same script, and it gives me error message of this: fasterq-dump.2.10.8 err: invalid accession '/scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955128/SRR5955128.dbGaP-22022.sra.

Do you think it is the same intermittent issue as the previous post described it? and maybe I wait till tomorrow to try it again?

BW,

David

**Comment by kwrodarmer** [comment]
@wraetz - would you be able to help out here?

**Comment by wraetz** [comment]
Hello David,

I think there is a misunderstanding here: Maybe I am wrong, but it looks to me like you moved the sra-file into the scratch-space.
That is not what the scratch-space is, it is an directory where the tool can put temporary stuff while it is working on the conversion. After the work is done the tool will clean up this scratch-space.
In order to tell you what went wrong - please copy the complete command-line into this thread.

**Comment by Davidwei7** [comment]
Hello Sir/Madam, 

Thank you very much for getting back to me. 

So I run the job on my uni cluster, and it has 150GB home space and 1TB space on a scratch directory. I stored all the prefetched SRA files in the scratch directory, and ran the fasterq-dump command from my home directory with giving the path to fasterq-dump to find where the SRA files are. 

My command is this:
awk '{print "fasterq-dump "$1" --ngc /home/skgtjzw/prj_xxxxxx.ngc /scratch/scratch/skgtjzw/workspace/ncbi/srafolder/"$1"/"$1".dbGaP-22022.sra -O /scratch/scratch/skgtjzw/workspace/ncbi/srafolder/fasterq_dump -t /scratch/scratch/skgtjzw/workspace/ncbi/srafolder/fasterq_dump"}' sample.lst > Fasterq_dump2.sh

Then i run the Fasterq_dump2.sh at the home directory /home/skgtjzw. And it gave me the error messages I posted earlier. I have a feeling that the path i gave to fasterq-dump could not find where the SRA files are, and went on to dbGaP to download the files again. Because it was talking a quite long time to do one file. 

Then I tried to run fasterq-dump command in the directory where the SRA files are (in the /srafolder/SRRXXXXXX/SRRXXXXXXX_dbGaP-220222.sra) and it seems to work fine and did not have any errors. 

So I think I must be really unfamiliar with how to use fasterq-dump and whether my path writing was correct, and whether it could only work under the directory where the SRA files are easily found?

Best Wishes, 

David

**Comment by wraetz** [comment]
Let me take it apart:
fasterq-dump ... the tool ---> OK
"$1" ... the accession to be converted ---> problem, quoting in the middle of an already quoted command ...
--ngc /home/name/prj_xxxxx.ngs ... where to find the key for decryption ---> OK
/scratch/scratch/name/workspace/ncbi/srafolder/"$1"/"$1".dbGaP-22022.sra ---> 2 problems! here you give it a 2nd accession and we have the quoting in the middle of an already quoted command
-O /scratch/scratch/name/workspace/ncbi/srafolder/fasterq-dump ... where to put the result ---> OK
-t /scratch/scratch/name/workspace/ncbi/srafolder/fasterq-dump ... problem! output and scratch should not overlap or be the same.

Here is how it should work:

fasterq-dump /scratch/scratch/name/workspace/ncbi/srafolder/$1/$1.dbGaP-22022.sra --ngc /home/name/prj_xxxxx.ngs -O /scratch/scratch/name/workspace/ncbi/srafolder/results -t /scratch/scratch/name/workspace/ncbi/srafolder/temp

I am assuming that:
/scratch/scratch/name/workspace/ncbi/srafolder/$1/$1.dbGaP-22022.sra is the accession to convert
you have created the folders:
/scratch/scratch/name/workspace/ncbi/srafolder/results
and
/scratch/scratch/name/workspace/ncbi/srafolder/temp

If you give it just an accession like 'fasterq-dump $1' the tool will try to go out over the internet to find the accession on a remote server and completely ignore what you have downloaded with prefetch!

**Comment by Davidwei7** [comment]
Hello Sir/Madam, 

Thank you for your input. 

I tried your suggestions, but it still does not seem to find the file. 

command:
fasterq-dump ~/scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955121/SRR5955121.dbGaP-22022.sra --ngc /home/skgtjzw/prj_xxxxxxx.ngc -O /scratch/scratch/skgtjzw/workspace/ncbi/srafolder/fasterq_dump_result -t /scratch/scratch/skgtjzw/workspace/ncbi/srafolder/temp

2020-12-09T15:09:03 fasterq-dump.2.10.8 err: name not found while resolving query within virtual file system module - failed to resolve accession '/home/skgtjzw/scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955121/SRR5955121.dbGaP-22022.sra' - Cannot resolve accession ( 404 )
2020-12-09T15:09:03 fasterq-dump.2.10.8 err: invalid accession '/home/skgtjzw/scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955121/SRR5955121.dbGaP-22022.sra'

Any further suggestions?

Best Wishes, 

David

**Comment by wraetz** [comment]
can we first check if the file does actually exist:

$stat /home/skgtjzw/scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955121/SRR5955121.dbGaP-22022.sra

please send me the output of this command

**Comment by Davidwei7** [comment]
Hello Sir/Madam, 

Thank you for your input. 

$stat /home/skgtjzw/scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955121/SRR5955121.dbGaP-22022.sra does not exist, i think the /scratch is in parallel with the /home.  The correct path should be /scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955121/SRR5955121_dbGaP-22022.sra, and the $/scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955121/SRR5955121_dbGaP-22022.sra
output: -bash: /scratch/scratch/skgtjzw/workspace/ncbi/srafolder/SRR5955121/SRR5955121_dbGaP-22022.sra: Permission denied

I think my previous script misplaced the SRR5955121_dbGaP-22022.sra with SRR5955121.dbGaP-22022.sra 

I changed to the right format, and now it is working. 

Your suggestion worked.  Thank you so much. 

Hope you have a good day. 

Best Wishes, 

David

**Comment by paul-sud** [comment]
I have been having the same issue intermittently over the past several days. I have been experiencing errors like the following:
```
2020-12-11T19:19:41 fasterq-dump.2.10.8 err: empty while validating file within network system module - error with https open '***'
```

I am trying to download a decent chunk of data one by one in a loop (some 500-odd accessions) and roughly 3/4 of them are failing with this error. I am using sratoolkit version `2.10.8` and executing a command in the following form: `fasterq-dump SRA***`. I'm pretty sure the accessions are valid because when I rerun the command they are able to retrieve the files without issue, seems like some sort of intermittent network issue.

**Comment by Benjamin-Lee** [comment]
I'm also getting this but only on my local machine, not on the Biowulf cluster. That makes me think its some sort of network issue as well. Happy to help or provide more info.

**Comment by klymenko** [comment]
@paul-sud, @Benjamin-Lee, please try [our new 2.10.9 release](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).
We improved tolerance against network failures.

**Comment by paul-sud** [comment]
I tried again with 2.10.9 but still experienced quite a high error rate.

**Comment by klymenko** [comment]
@paul-sud, try `prefetch` first.

**Comment by paul-sud** [comment]
> @paul-sud, try `prefetch` first.

Thanks for the tip. I managed to get what I needed just naively retrying but if I need to download more files I'll definitely try using `prefetch` as you suggest.
