### ISSUE TITLE
error when make install

### ISSUE THREAD

**Issue by qiaowei-vvjoe** [ncbi/sra-tools#216]
hi
I am now install sratools first time.When I make install there is error.I really don't know it is just because I haven't the permission?Thanks so much in advance.

$ make install
Checking make status of tools...
NOTE - copycat cannot be built: It requires our internal library 'libkff' which requires 'libmagic' and its development headers.
NOTE - pacbio-load cannot be built: It requires our internal library 'libkdf5' which requires 'libhdf5' and its development headers.
NOTE - remote-fuser cannot be built:  it requires 'fuse' library and its development headers.
Installing executables to /usr/local/ncbi/sra-tools/bin/...
mkdir: cannot create directory ‘/usr/local/ncbi’: Permission denied
make[1]: *** [installexes] Error 1
make: *** [install] Error 2

**Comment by aboshkin** [comment]
Yes. you need write permission to /usr/local/. Try 'sudo make install' if you are allowed. Otherwise, you may try to install into a different (writeable) directory by running 'configure --prefix=<pathToInstallationDirectory>' and then 'make install', all from the sra-tools root directory. Run 'configure -h' for full details.
