### ISSUE TITLE
'Segmentation fault' error for faster-dump

### ISSUE THREAD

**Issue by VicenteFR** [ncbi/sra-tools#242]
Hi,

I am trying to use fasterq-dump to download an accession no raw data as follows
`fasterq-dump SRR8893737 -t </path/to/scratch/tmp> -e 12`
but I keep getting next error:

```
2019-11-01T01:55:47 fasterq-dump.2.10.0 err: cmn_iter.c cmn_read_uint8_array( #31632385 ).VCursorCellDataDirect() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted) 
2019-11-01T01:55:47 fasterq-dump.2.10.0 err: row #31632385 : Q[1].len(50) + Q[2].len(49) != Q.len(0) 
2019-11-01T01:55:47 fasterq-dump.2.10.0 fatal: SIGNAL - Segmentation fault 
```

It seems to be related to this [issue](https://github.com/ncbi/sra-tools/issues/221#issue-485812890), but I am struggling to understand what's going on.
I would appreciate any help.
Thanks so much!

**Comment by wraetz** [comment]
Hi,
What is going on is this: there are problems on the server-side sending the data to you.
We are working on a solution that will not create a seg-fault, but terminate the application with a more descriptive error-message.
What you can do right now is to download the accession ( SRR8893737 ) with prefetch.
Then use fasterq-dump by pointing it to the downloaded file:
fasterq-dump </absolute/path/to/SRR8893737.sra> -t <…> -e 12
Out of curiosity : do you have enough cpu's to run 12 threads in parallel? Using more than 6 threads results in very little speed-up.

**Comment by llx174** [comment]
Hi! I met the same error as above when I tried to transformed sra files into fastq using fasterq-dump  but through the tool of IBM-aspera to download raw sequence data just as the code below:
`   ascp -v -i ~/.aspera/connect/etc/asperaweb_id_dsa.openssh -k 1 -T -l200m anonftp@ftp-trace.ncbi.nlm.nih.gov:/sra/sra-instant/reads/ByRun/sra/SRR/........./........./.........(online address) .sra /..........(my local directory) `
 I didn't use prefetch because of its low download rate compared to aspera. Should I have to use prefetch to re-download the raw-data to avoid the segmentation fault ? If there is faster way to download rawdata as well as avoiding error?
Appreciate for your help, thanks!

**Comment by kwrodarmer** [comment]
You should know a few things... First, prefetch is not slower than Aspera, since versions up to 2.9.6 used Aspera for its download when requested and available. Second, the URL you are using has been deprecated for years and will stop working. And third, the majority of SRA storage now resides on systems that are not supported by Aspera.

You always want to use `prefetch` rather than `ascp` because it does a **lot** more than just downloading the data: it downloads the complete data set required to process.

All of that said, segmentation faults are bugs. We will work on your report to fix it. You are best served in this case by using `prefetch` to retrieve the runs you want and then using `fasterq-dump` on them locally.

**Comment by klymenko** [comment]
@VicenteFR , do you still have problems?
