### ISSUE TITLE
ncbi/sra-tools

### ISSUE THREAD

**Issue by LongHu-code** [ncbi/sra-tools#243]
fasterq-dump.2.9.6 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )

**Comment by LongHu-code** [comment]
Did you meet this problem before?

> fasterq-dump.2.9.6 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )

**Comment by andrewmaksymowsky** [comment]
We've recently noticed an uptick in the number of connection timeouts to ncbi.nlm.nih.gov when running sratoolkit at our site as well. Wondering if this is just an issue with the software or if something else has changed.

**Comment by kwrodarmer** [comment]
> Wondering if this is just an issue with the software or if something else has changed.
Something else has changed, yes. The archive was moved to new storage that has significantly different behavior and performance characteristics. We are making changes to the software to compensate to the extent possible.

**Comment by andrewmaksymowsky** [comment]
Thank for the follow up. I've tried updating to the latest version of sra-toolkit and while the download can now make it further on average, I still run into the following error:
prefetch.2.10.0 int: timeout exhausted while reading file within network system module - Cannot KStreamRead: https://sra-download.ncbi.nlm.nih.gov/traces/refseq/CM000671.1

This happens with sratoolkit/2.10.0 and using the following command: prefetch -v SRR1766940
I've tried using different transport options (http, fasp, aspera,...) with the same result. Is there a way to increase the timeout or do we need to wait for a fix ?

Thanks !

**Comment by kwrodarmer** [comment]
The timeouts are intended to be configurable. That said, we made a pretty large overhaul of internals for the 2.10.0 release and need to perform another review to see if there are edge cases being hit. In particular, the URL you hit should not be having timeouts because it is stored on more traditional systems. But it goes through servers that are affected by the new system.

We made one change that was necessary to move into cloud environments, which was the ability to reduce the wait time around connection attempts _(and this is where we might have one of the edge cases I mentioned)_. But your report shows that the connection had succeeded and a read was in progress. The refseq files are trivially small by comparison, so the timeout should be a new symptom of related storage.

A word about aspera download: ascp does not work for bucket storage as far as we are aware. I don't know if there is any fix being considered, but I suspect not because bucket storage is inherently hostile to the aspera algorithm. When accessing buckets, you won't get better than https.

We do have configuration available for timeouts. I will try to look them up and post something - perhaps not directly here, but in a Wiki page or something.

**Comment by andrewmaksymowsky** [comment]
Fantastic thank you !

**Comment by kwrodarmer** [comment]
You will be a guinea pig on this, I just wrote it directly. Let me know what to fix:

https://github.com/ncbi/sra-tools/wiki/06.-Connection-Timeouts

**Comment by andrewmaksymowsky** [comment]
Documentation looks good to me and also seems to have solved my problem. Increasing the timeouts as per the instructions you've provided above leads to my downloads succeeding. Thanks again !
