### ISSUE TITLE
fastq-dump: Wide character in subroutine entry

### ISSUE THREAD

**Issue by dariober** [ncbi/sra-tools#248]
Hi- `fastq-dump` and `fasterq-dump` v2.10.0 give me the error:

```
fastq-dump SRX3653195 
Wide character in subroutine entry at /home/dario/miniconda3/envs/tmp-fastq-dump/bin/fastq-dump line 764.
```

Version 2.9.6 works fine. If it matters, I installed sra-tools via conda. It happens both on Ubuntu 18 and Centos 7.

Dario

**Comment by kwrodarmer** [comment]
What happens if you use a run accession rather than experiment? Try SRR6676681.

**Comment by dariober** [comment]
@kwrodarmer - thanks for replying. Indeed, using the run accession SRR works. I guess the question now is whether querying with the experiment ID is supposed to work or not...?

**Comment by kwrodarmer** [comment]
So that's a slightly more difficult answer right now...

First, it should never have the issue you reported. This is coming from Perl, and we are not using Perl in the next release.

But the issue around the non-run accession resolution is currently in flux: we were heading toward resolving all SRA accession types, but may need to integrate with some other changes at NCBI over the coming months - so for the time being we are backing off in the next release 2.10.1.

So we have not yet resolved how we're going to deal with container accessions, whether within the SRA Toolkit or a different service. That will be resolved before long.
