### ISSUE TITLE
fastq-dump requires network access, even with local files

### ISSUE THREAD

**Issue by pchines** [ncbi/sra-tools#25]
Newer versions of fastq-dump apparently attempt to access NCBI resources via some network port (not standard http), even when all of the required resources are local (retrieved with prefetch).  This is not similar to previous behavior (v2.3.3), and makes it difficult to spread out the work of converting SRA files on a large cluster where the compute nodes don't have access to outside networks.  Perhaps an option could be added to skip the attempted network access (e.g. --no-network)?  If it is absolutely essential that this access take place, please let us know which port needs to be forwarded.

One reason that submitting to a cluster is necessary is that fastq-dump is slow (see issue #24) and grows to use a huge amount of memory (either a memory leak or cachind unnecessary data).

**Comment by kwrodarmer** [comment]
So several things to notice here. You mention

> newer versions of fastq-dump apparently attempt to access NCBI resources via some network port (not standard http).

Yes - we have been performing download on demand for some time now. See [Download On Demand](https://github.com/ncbi/sra-tools/wiki/Download-On-Demand) and [VDB Name Resolution](https://github.com/ncbi/ncbi-vdb/wiki/Name-Resolution-Process). **However**, you are running on the Biowulf cluster which uses **HTTP proxy servers** (as do many if not most clusters).

Biowulf sits in the NIH campus within walking distance of the NCBI servers. Using HTTP access via proxy is the way we designed Biowulf access to the SRA, using HTTP as a sort of substitute for NFS. The setup is fairly recent, and while there may still be some kinks that result from having the proxy servers in the loop, you should not need to `prefetch` data. That said, if you run `vdb-config` you can turn on/off network access as well as setting your own cache areas.

Last of your issues is that `fastq-dump` is slow, grows to use huge amount of memory, etc. Since you've read issue #24, you will see that speed is data dependent, and in the case mentioned we were unable to reproduce the user's behavior. `fastq-dump` does not have a memory leak, but utilizes VDB which does perform look-ahead caching just like the Linux kernel. The difference is that when we perform look ahead caching, the space is accounted to the running process.

My suspicion is that you probably should not be dumping fastq in the first place, but unless we have some information about what you're trying to accomplish, we won't be able to help.

**Comment by pchines** [comment]
Thank you for your response. This was not a request for help with a particular situation, and I was not running these programs on the Biowulf cluster.  I appreciate your pointer to vdb_config as the place I can disable network access (or, I see, configure a proxy).

But now that you bring it up, I will follow up on the issues you raised, because I think they are highly relevant to users of this software, and thus to its future development.  I need FASTQ because my intention is to re-align the sequence, and none of the aligners I want to use reads directly from SRA files. In fact, I don't know of any that do.

You will find, when you talk to users outside of NCBI, that obtaining FASTQ sequence is one of the most commonly performed operations on an SRA file.  You should consider optimizing for this very common use case.  And while I appreciate the value of look-ahead cache, I do not think it is at all reasonable that extracting sequence from a 30Gb SRA archive should require 7Gb of RAM and take nearly 48 hours. I acknowledge that this is, certainly, data (and OS, and hardware) dependent. But this file is whole-genome human genomic sequence--again, a very common use case, and one that will become more common in the future.  Is there an option (in vdb-config or elsewhere) to limit the size of the look-ahead cache?
