### ISSUE TITLE
Confusion about prefetch download [SRX vs SRR]

### ISSUE THREAD

**Issue by rohitsuratekar** [ncbi/sra-tools#253]
I am using prefetch to get raw data for downstream RNA-seq analysis. When I was using `Prefetch 2.9.6.1`  downloaded files has **SRX** ID. For example,

`prefetch --verbose SRX4720625`

Above command gave me **SRX4720625.sra** 

However, just recently I upgraded to `Prefetch 2.10.0` and same command now gives me runs file of given SRX id (i.e. **SRR7882015.sra** file.).

When I did `fasterq-dump` on both files, they gave me same files with different ids! (SRX4720625.sra_1.fastq, SRX4720625.sra_2.fastq AND SRR7882015.sra_1.fastq and SRR7882015.sra_2.fastq)  However, I have not tested this with SRX ids with multiple runs. 

Are these same files with different names ? How can I get relation data between SRX and SRR ids?

**Comment by seandavi** [comment]
I have an *under-development* API available (http://api.omicidx.cancerdatasci.org/redoc) that is updated monthly that can help answer questions about relationships between IDs. In this case, you can use this url:

- http://api.omicidx.cancerdatasci.org/sra/experiments/SRX4720625/runs

In this case, there is only one SRA Run (SRR) associated with the experiment `SRX4270625`. If you have an SRR identifier, instead, there will always be only one SRX associated:

- http://api.omicidx.cancerdatasci.org/sra/runs/SRR7882015

Note that the entire experiment record, study record, and sample record are also included, making retrieval of all SRR metadata a one-stop affair. 

In your specific case, there is a one-to-one relationship between SRX and SRR.

**Comment by kwrodarmer** [comment]
Hello - I should probably write a Wiki page about this.

The SRA container model is that an experiment is given an SRX _(or ERX or DRX)_ prefix and an identifying number. An experiment can contain multiple runs, given SRR _(or ERR or DRR)_ prefix and each with their own number. In the early days of NGS technology, we tended to receive experiments with a number of runs in each. Modern technology and usage has tended to produce experiments consisting of only a single run. As a result, _some_ experiment accessions map to exactly 1 run, while others map to multiple runs.

During the time period of the 2.9.x releases, a change was made to NCBI's name resolver service that silently began to honor experiment accessions as if they had been given as run accessions when there was a one to one mapping. Previously, only run accessions were accepted. Tools such as `fasterq-dump` do not know or attempt to interpret what type of accession is provided on the command line, but rely on the name resolver service. However, they used the accession provided by the user to create the name of output file, giving the behavior you note above. This behavior is in error, because only runs have fastq data - not experiments.

With the 2.10.0 and availability of SRA in commercial clouds, there was another change in behavior. Name resolution now happens via NCBI's SRA Data Locator _(SDL)_ service. Our tools no longer use the user-provided accession in producing output file names, but instead use the resolved information. SRX resolves to SRR, and thus we get the proper name for output now.

**Comment by rohitsuratekar** [comment]
@seandavi Thank you. It is very useful resource. I will check it out. Currently I was using 'SRA_Accessions.tab' file from entire [metadata](https://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/) with simple id search.

@kwrodarmer This name resolution process is little bit described in [wiki](https://github.com/ncbi/ncbi-vdb/wiki/Name-Resolution-Process) but didn't mention anything about how the naming was handled. Is there any tool/way to get metadata associated with given experiment (SRX/ERX..)? I can see some third party tools like API mentioned above or [SRAdb](https://bioconductor.org/packages/release/bioc/html/SRAdb.html) package in R.

**Comment by seandavi** [comment]
@rohitsuratekar, I am the author of SRAdb. The OmicIDX API described above is the replacement for SRAdb and includes full metadata for all SRA accessions including studies, samples, experiments, and runs; biosample records are also available.

**Comment by rohitsuratekar** [comment]
@seandavi This was an unexpected surprise :)

**Comment by saketkc** [comment]
I have a command-line tool that fetches metadata and downloads `.sra` files from NCBI:
https://github.com/saketkc/pysradb

```
> pysradb srx-to-srr SRX4720625 --detailed 
experiment_accession run_accession study_accession experiment_title                                        experiment_desc                                         organism_taxid  organism_name library_strategy library_source  library_selection sample_accession sample_title instrument   total_spots total_size  run_total_spots run_total_bases run_alias      sra_url                                                                                 experiment_alias source_name               tissue                    developmental stage gfp status    genetic background
SRX4720625           SRR7882015    SRP162234       GSM3396533: wt_GFPpos_24hpf_rep1; Danio rerio; RNA-Seq  GSM3396533: wt_GFPpos_24hpf_rep1; Danio rerio; RNA-Seq  7955            Danio rerio   RNA-Seq          TRANSCRIPTOMIC  cDNA              SRS3805811       N/A          NextSeq 500  47867961    3470385670  47867961        7230485009      GSM3396533_r1  https://sra-download.st-va.ncbi.nlm.nih.gov/sos2/sra-pub-run-4/SRR7882015/SRR7882015.1  GSM3396533       FACS-sorted embryo cells  FACS-sorted embryo cells  24 hpf              GFP positive  wild type    
```
Here's a quick run-through of the potential use cases @rohitsuratekar has been looking for: https://colab.research.google.com/drive/1qlxFidFqY-xTFOXGQKtyXoKX8zA68oIG
It requires an active internet connection.

**Comment by swati-mahapatra** [comment]
> I have an _under-development_ API available (http://api.omicidx.cancerdatasci.org/redoc) that is updated monthly that can help answer questions about relationships between IDs. In this case, you can use this url to fetch all SRRs associated with the SRX:
> 
> * http://api.omicidx.cancerdatasci.org/sra/experiments/SRX4720625/runs
> 
> There is only one SRA Run (SRR) associated with the experiment `SRX4270625`. If you have an SRR identifier, instead, there will always be only one SRX associated which you can find by hitting the associated SRR url:
> 
> * http://api.omicidx.cancerdatasci.org/sra/runs/SRR7882015
> 
> Note that for SRR records in the API, the entire experiment record, study record, and sample record are also included, making retrieval of all SRR metadata a one-stop affair.
> 
> In your specific case, there is a one-to-one relationship between SRX and SRR, but the general case is that SRX has _one-or-more_ SRRs.

Hello, I have a similar issue where an PRJNA id is prefetching SRR id of another study. I tried accessing the [http://api.omicidx.cancerdatasci.org/redoc](url). However, the site can't be reached. Could you please share an updated link?  Thanks!
