### ISSUE TITLE
How to prefetch .sra file only

### ISSUE THREAD

**Issue by yhg926** [ncbi/sra-tools#264]
Hi,  when i use command "prefetch 'Aceession' ", it will also download other files (might be references?) besides .sra file, usually, .sra download quickly, but other files very slow and often failed, and i do not need them. I also try fastq-dump, it can only download fastq files, but it also often failed. I can kill the process after prefetch .sra file for single accession, but it is not efficient for many accessions. I am wondering if there efficient way to prefetch .sra files only?
Thanks!

**Comment by kwrodarmer** [comment]
Could you tell us a little more about your situation, like which version of prefetch you are using?

Here is some background: prefetch will retrieve the SRA plus any needed references. The references are needed in order to complete the dataset needed to use the SRA file. Without them, there is little point in downloading the SRA file itself.

But if you are using version 2.10.x, it may download additional files such as the original submission unless you give it a type selection argument to limit the download to SRA and needed references files only.

**Comment by yhg926** [comment]
my version is prefetch : 2.10.0,  I am developing reference-free/alignment-free tool for fastq files comparison, there is no need for me to download references, all i need is the fastq raw data. 
So how should i set the arguments?

**Comment by kwrodarmer** [comment]
That's interesting and good to hear!

SRA objects that have been aligned against some set of references are also compressed against those references, meaning that we reduce or eliminate redundant data stored within the SRA object itself. This makes the references necessary just to reconstruct the reads you need to obtain fastq.

I misstated the need to indicate file type with prefetch, because by default it looks for 'sra' files only. You should not have to do anything else.

**Comment by yhg926** [comment]
Thank you!, I have another question now. My accessions are all human samples, it seems prefetch download the same references again and again for all accessions. is it possible only download references once and let all .sra file share the same references ?

**Comment by kwrodarmer** [comment]
Please try version 2.10.2, in case you haven't so far. If `prefetch` is repeatedly downloading reference files, that may indicate a bug. If you still see this behavior, we will create an internal ticket to track it down.

Thank you for your reports!

**Comment by yhg926** [comment]
just installed version 2.10.2, but it aks run "vdb-config --interactive", i run, save and exit, but it still can not continue on, and report this messages:  
~/tools/sratoolkit.2.10.2-ubuntu64$ bin/prefetch
This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive
For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
