### ISSUE TITLE
Using fasterq-dump, are resulting files validated (corruption checks)?

### ISSUE THREAD

**Issue by leagleag** [ncbi/sra-tools#285]
Hi,
I guess the title speaks for itself, I am wondering if fasterq-dump validate in any way. Maybe a temporary sra file is Md5? checked, but I am not certain. How safe is it to use the fastq files?
I was not able to find this information in the documentation.
Thanks

**Comment by kwrodarmer** [comment]
SRA stores data in VDB database files that contain md5 checksums on the files themselves and CRC32 on each individual blob. There is a tool called `vdb-validate` that will test all checksums for integrity, and VDB itself validates the checksums on every blob fetch.

When you run `fasterq-dump`, there can be some noisy output. But if you get a report of success, it is quite reliable.

**Comment by leagleag** [comment]
Thanks for the prompt answer. So I understand that `fasterq-dump` is not doing any sort of checksums. (?)

Since I really appreciate this new tool, I am running the following: `fasterq-dump SRR_ID -t DEST_DIR --split-3 --sra_cache_dir CACHE_DIR`
To my understanding this command leaves me with 1 to 3 fastq files in DEST_DIR. The cache directory is emptied as expected. However, running `vdb-validate` seems to require a SRR_ID.sra file which is not present.
That would mean that one course of action would be to use `prefetch` to obtain the sra file which is redundant since `fasterq-dump` actually does the job.
Consequently, I am thinking of checking the md5 sum of the fastq files. Would that be the best way to go here?

**Comment by leagleag** [comment]
Just to close this. The solution is to use `vdb-validate` on the `.sra.cache` files written by `fasterq-dump`. The trick was to know they existed in the first place. Thanks

**Comment by kwrodarmer** [comment]
>  So I understand that fasterq-dump is not doing any sort of checksums. (?)

It is testing checksums as it reads. It is not able to check md5 checksums that are on entire files, but it checks per-blob CRC.

`vdb-validate` operates on local copies rather than remote copies. There is essentially zero validity to running it on remote, given:

1. we run it before releasing it to the public
2. it serves to detect corruption in copies
3. any validation over the network would only validate that ephemeral download with no bearing on any further downloads

So `vdb-validate` only makes sense on static data, which you obtain by running `prefetch`.
