### ISSUE TITLE
Discrepancy between SRA Toolkit website and Wiki?

### ISSUE THREAD

**Issue by bretonics** [ncbi/sra-tools#29]
In terms of downloading SRA files...

**NCBI's [handbook](http://www.ncbi.nlm.nih.gov/books/NBK158899/) documents:**
> For multiple simultaneous downloads of SRA data, or for high-volume downloads, we recommend using command line utilities such as wget, FTP, or Aspera’s ‘ascp’ utility. 

It also gives an example to download SRA data using the SRA Toolkit using `fastq-dump` not `prefetch`.

**Wiki:**
>At the risk of starting this page off on a negative note, please do not download data using generic tools such as ftp, wget, etc. Doing so can create incomplete images and complicate problem diagnosis.
>
>The supported means of downloading SRA data is to use the tool prefetch included in the SRA Toolkit.

#### What's the difference in downloading using `fastq-dump` vs `prefetch`? 
I thought `fastq-dump` was to be used once the SRA file was downloaded.

**Comment by kwrodarmer** [comment]
The NCBI handbook is an older documentation system that we are slowly cleaning up. The most current information will be found on our github Wiki, whenever there is a conflict.

The difference between downloading using `fastq-dump` and `prefetch` is that one of them is a format converter and the other is strictly a downloader. What this means depends upon the environment.

All SRA tools have the ability to resolve a run accession into a URL for remote access, which can be used to retrieve data across HTTP. `prefetch` has this in addition to the ability to use `Aspera`. The difference is that while Aspera is *much* faster than HTTP, the data cannot be used until the whole file has been downloaded. HTTP on the other hand is used to process data as they arrive, and does not require downloading an entire file.

So use `prefetch` with the Aspera option if:
1. you intend to dump the entire run
2. you have disk space available
3. Aspera performs much better for you than HTTP

Use direct on-demand download if:
1. you do not need 100% of the run data
2. you don't have so much disk space

If you use `fastq-dump` to convert an entire run, you will be using close to all of the data in the run file. But other uses may not need everything, e.g. looking at reads under a certain region of a chromosome or performing frequency analysis where you don't need quality values. These latter cases would generally favor direct download by the tool rather than `prefetch`.
