### ISSUE TITLE
A question about using fastq-dump to download a subset of reads

### ISSUE THREAD

**Issue by lauraht** [ncbi/sra-tools#297]
Hello!

I have a question regarding fastq-dump and would appreciate your advice:

We want to download only a small subset of reads (5000 reads) from an SRA Run by using fastq-dump. We can use -N and -X options to dump a range of consecutive spots (reads). However, we do not know in what order SRA stores reads. Does SRA store reads in the order of genomic coordinates or store reads randomly?

We want to download 5000 reads from an SRA Run with random sampling, so that these 5000 reads can be somewhat representative of all reads in the SRA Run. We cannot download all reads due to limited disk space and time (we have a huge number of SRA Runs that need to be downloaded). If SRA stores reads randomly, using -N and -X options in fastq-dump would give us a random sampling of reads. However, if SRA stores reads in the order of genomic coordinates, I was wondering if there is any way we can download 5000 reads from an SRA Run with random sampling by using fastq-dump or some other tool?

I would greatly appreciate your help.

Thank you very much!

**Comment by wraetz** [comment]
As I understand your question, you are asking if the reads in a SRA run are sorted by reference position. That depends on the format the submitter did send to us.

The majority of the SRA runs have been submitted as fastq-files. We load these files into a SRA run in the order they appear in the submitted file. It might be that the submitter did align his data and sent us the aligned data in fastq-format or the submitter sent us unaligned data from his sequencing machine. We do not know what the submitter did to produce the submitted fastq-files.

We are also receiving bam-files from submitters, when loading these into SRA runs we do sort the reads in reference-order to make it easier to retrieve them for instance for pileup.

The answer to your question is: they might be in random order - but you cannot be sure.

What I would suggest for you is this: use vdb-dump!
'vdb-dump SRRXXXXXX -r' will give you the row-count.
Pick N random numbers between 1 and the row-count.
Then you can make N calls to fastq-dump each for 1 row, like this:
'fastq-dump SRRXXXXXX -N 123 -X 123 -Z' ( in case 123 is one of you random picks )
This will be slow but faster than retrieving the whole run.

A second way of doing it is using vdb-dump like this 'vdb-dump SRRXXXXXX -R 123 -C READ'
This way the quality column is not touched which will make it faster. You will be even faster if you use an option-file. This is a simple text file, where you write for each random pick '-R NNN' into it.
Then you run 'vdb-dump SRRXXXXXX -C READ -X --option-file yourfile.txt'
This will be faster because you pay only once for the tool-internal initial checks.

A third option is to use the ngs-interface. You can use it from python or c++. Examples can be found in the ncbi/ngs repository.

**Comment by wraetz** [comment]
As I understand your question, you are asking if the reads in a SRA run are sorted by reference position. That depends on the format the submitter did send to us.
The majority of the SRA runs have been submitted as fastq-files. We load these files into a SRA run in the order they appear in the submitted file. It might be that the submitter did align his data and sent us the aligned data in fastq-format or the submitter sent us unaligned data from his sequencing machine. We do not know what the submitter did to produce the submitted fastq-files.
We are also receiving bam-files from submitters, when loading these into SRA runs we do sort the reads in reference-order to make it easier to retrieve them for instance for pileup.
The answer to your question is: they might be in random order - but you cannot be sure.
What I would suggest for you is this: use vdb-dump!
'vdb-dump SRRXXXXXX -r' will give you the row-count.
Pick N random numbers between 1 and the row-count.
Then you can make N calls to fastq-dump each for 1 row, like this:
'fastq-dump SRRXXXXXX -N 123 -X 123 -Z' ( in case 123 is one of you random picks )
This will be slow but faster than retrieving the whole run.
A second way of doing it is using vdb-dump like this 'vdb-dump SRRXXXXXX -R 123 -C READ'
This way the quality column is not touched which will make it faster. You will be even faster if you use an option-file. This is a simple text file, where you write for each random pick '-R NNN' into it.
Then you run 'vdb-dump SRRXXXXXX -C READ --option-file yourfile.txt'
This will be faster because you pay only once for the tool-internal initial checks.
A third option is to use the ngs-interface. You can use it from python or c++. Examples can be found in the ncbi/ngs repository.

**Comment by lauraht** [comment]
Hi @wraetz,

Thank you so much for your information and advice! They are very helpful. I really appreciate it!

I first tried your first suggestion: pick N random numbers between 1 and row-count, and make N calls to fastq-dump each for 1 row. I found that this approach takes a long time to finish. For N=5000, calling fastq-dump for 5000 times took 1 hour and 22 minutes to finish.

Then, I tried your second suggestion: use vdb-dump with an option-file (writing each random pick '-R NNN' into it): `vdb-dump SRRXXXXXX -C READ --option-file optionFile -f fastq`. This approach is fast. For N=5000, it took <1 minute to finish.

So the second approach is pretty nice. However, I found that vdb-dump does not seem to have those important options in fastq-dump, such as --split-files, --skip-technical, --clip, and --read-filter. I was wondering if there are any options in vdb-dump that could do the same tasks as the above options in fastq-dump?

For paired-end reads, the --split-files option in fastq-dump is quite useful. So for paired-end reads, when we pick 5000 random numbers between 1 and row-count and then use vdb-dump with an option-file for those 5000 random picks, what happens to read mates (read pairs)?

I’d appreciate your further advice.

Thank you very much for your help!

**Comment by lauraht** [comment]
Thank you very much @wraetz!

I tried to use ` -C READ,READ_START,READ_LEN,READ_TYPE` to replace ` -C READ` in vdb-dump. However, the output fastq file is exactly the same as the output fastq file by using ` -C READ`. I do not see any additional information.

I found that the output fastq file from vdb-dump is the same as the output fastq file from fastq-dump with the default setting (without specifying options). For a paired-end dataset, when using fastq-dump with the default setting, I got the read length which exactly doubles the read length by using `--split-files`.  Also, the sequence of a read from using fastq-dump with the default setting (or from using vdb-dump) is the combination/merge of the left sequence and the right sequence of the corresponding read from using `--split-files`--- is this the basic rule in fastq-dump? 

If we want to split the merged sequence from vdb-dump into the left and right sequences, we just split at the exact middle point of the merged sequence, is that right? I found that MATLAB has a function called seqsplitpe() which can do this split; is this function good for this split?

On the other hand, does fastq-dump have anything like `--option-file` and `-R NNN` as in vdb-dump?

Thank you so much for all the help!

**Comment by kwrodarmer** [comment]
If you are handy with Python _(or Java or C++)_, you can write to our APIs to achieve any of these ends.

Assuming you are only interested in tools, I can say that there was a time when we were emphasizing SRA's ability to access any read at low cost, but in recent years the storage technology has shifted from random-access high-performance- to object-stores. This is less noticeable when retrieving whole runs, but exhibits detrimental performance when attempting to access individual reads as you've described.

Note that this is not a change in the software or the storage format, but rather the underlying hardware.

You can achieve something more of what you want if you first download data to a more traditional, random-access POSIX filesystem using `prefetch` and then running your queries against the downloaded data. Unfortunately, this means you have to download the entire run, so you have to choose between optimizing time or space.

**Comment by lauraht** [comment]
Hi @kwrodarmer,

Thank you very much for your response!

If I understand this correctly: “_but in recent years the storage technology has shifted from random-access high-performance- to object-stores. This is less noticeable when retrieving whole runs, but exhibits detrimental performance when attempting to access individual reads as you've described_”, you mean the recent storage technology slows down fastq-dump for downloading individual read, right?

I would appreciate it if you could confirm the following questions:
(1) For a paired-end dataset, the sequence of a read from using `vdb-dump` is always the combination/merge of the left sequence and the right sequence of the corresponding read from using `fastq-dump --split-files`, right?
(2) If we want to split the merged sequence from `vdb-dump` into the left and right sequences, we can always split at the exact middle point of the merged sequence, is that right?

If the answers to the above two questions are “yes”, I can proceed with the second approach that @wraetz suggested (i.e. using `vdb-dump` with `--option-file` and `-R NNN`).

Thank you very much for your help!

**Comment by wraetz** [comment]
The answer to your questions (1) and (2) is unfortunately: No.

(1) The merged sequence is the combination of the left and the right sequence as you call it, but it might also contains technical (linker) sequences. That is why you need the READ_TYPE column to skip these.

(2) You cannot split just in the middle. Event if it looks like that in an example accession. You need to look at the READ_START and READ_LEN column to detect what part of the merged READ you have to pick.

**Comment by lauraht** [comment]
Hi @wraetz,

Thank you very much for your answers!

But when I use ` -C READ,READ_START,READ_LEN,READ_TYPE` in `vdb-dump`, I did not get any additional information in the output fastq file. The output fastq file is exactly the same as the output fastq file by using `-C READ` only. Any ideas on this?

Are the technical (linker) sequences located in the middle between the left and right sequences? We cannot split in the middle just because there might be linker sequences between the left and right sequences, right? Usually what are the normal lengths of linker sequences? 

I only use those 5000 reads to get k-mer distribution instead of performing actual RNA-seq downstream analyses. So I would like to get an idea about the normal lengths of those linker sequences--- if they are very short, their impact on k-mer distribution might not be that big.

I randomly selected 8 paired-end datasets (8 SRA Runs) to download 5000 reads from each. I found that for all 8 datasets (8 SRA Runs), the result of splitting at the exact middle point of the sequences from `vdb-dump` is the same as the result of running `fastq-dump --split-files`. So, is it true that for the majority of the paired-end datasets (SRA Runs), the sequences could be split at the middle point (i.e. only a smaller percentage of paired-end datasets have linker sequences)?

Since there are many technical details involved, I was wondering if there is any tool or function in sra-tools package that can perform splitting paired-end sequences? I would greatly appreciate it if you could help provide some program or function that can correctly split the paired-end sequences from `vdb-dump`.

Thank you so much for all your help!

**Comment by wraetz** [comment]
vdb-dump will not produce splitted fastq for you. You have to do that in your code. You have to write code which takes to output of vdb-dump (not in fastq-mode!) and do the splitting yourself!
The commandline woud be:
{code}
vdb-dump SRRXXXXXX -C READ,READ_START,READ_LEN,READ_TYPE,(INSDC:quality:text:phred_33)QUALITY -f tab --option-file rows.txt > values.txt
{code}

You have to take the tab-separated file and produce the splitted fastq yourself.

**Comment by lauraht** [comment]
Hi @wraetz,

Thanks for the clarification!

However, I found that the vdb-dump approach (i.e. using --option-file and -R NNN to list reads IDs) is only fast when dumping the first 5000 reads (taking <1 minute). When randomly selecting 5000 reads over the full range of the read count and listing them in the option file, vdb-dump took a long time to finish.  For example, for a dataset with 57,047,129 reads, randomly selecting 5000 reads between 5001 and 57047129 and listing them in the option file, vdb-dump took 13-20 minutes to finish. Since we have a huge number (250K) of datasets, taking 13-20 minutes to finish just one dataset would not be feasible. I wonder why the speed has such a big difference.

Thanks!

**Comment by wraetz** [comment]
You are right about the speed difference. The problem here is random access: All sra-tools use a library underneath them to access the data. No matter what tool you use ( or use the library directly ) you will see the same timing - because the tools are just a 'thin' layer on top of the vdb-library, which is doing most of the work. This library (and the design of the storage layer it implements ) is tuned for sequential access to the data. Random access is possible - but it comes at a cost: runtime. You may get slightly better results if you are sorting your random numbers in the option-file. At a certain threshold you may be better off if you are downloading the whole archive with prefetch and then run your random selection by using vdb-dump against the absolute path of the downloaded accession. 
example:
prefetch SRRXXXXXX
vdb-dump /home/$USER/wherever_you_downloaded_it_to/SRRXXXXXX -C READ,...…

**Comment by wraetz** [comment]
Another thought to speed it up. Do you really need the quality-values in fastq? Quality is the most 'expensive' aka biggest column in the data-set. If you can omit it from the request to vdb-dump and replace it in you script with a default value the same length as the READ-column, you will see a speed-up.

**Comment by lauraht** [comment]
Thanks @wraetz!

Actually, I already sorted the random numbers in the option file and got this runtime.

I also tried prefetch. However, prefetching the entire dataset itself takes a quite long time already. For example, for a 2.6Gb dataset, prefetch took 5 minutes to finish. And for a 4.9Gb dataset, prefetch took 7 minutes to finish. This is one of the reasons that I was trying to avoid downloading the entire dataset.

I also tried not including the QUALITY column in vdb-dump, and this speeds up by about 50%. However, it still took 6-9 minutes to finish one dataset, which is still not feasible for dumping 250K datasets, unfortunately.

Thanks!

**Comment by wraetz** [comment]
I am sorry to hear that. But it looks like you are stuck between two approaches ( prefetch vs. vdb-dump ) which are both too slow for the 250K datasets. Have you thought about using the cloud? We have replicated our dataset in the cloud on AWS and GCP. If you launch N virtual machines in the same region where our data is located - you can parallelize.

**Comment by lauraht** [comment]
Thanks @wraetz for the suggestion!
I will think about it.

**Comment by jaum20** [comment]
> A second way of doing it is using vdb-dump like this 'vdb-dump SRRXXXXXX -R 123 -C READ'
> This way the quality column is not touched which will make it faster. You will be even faster if you use an option-file. This is a simple text file, where you write for each random pick '-R NNN' into it.
> Then you run 'vdb-dump SRRXXXXXX -C READ --option-file yourfile.txt'

tried this but got:

`vdb-dump.3.2.1 err: data excessive while inserting argument list - Too many occurrences of option '--rows'`

"yourfile.txt' have 5000 lines of -R  + a random nuber between 1 and row-count:

e.g.: 

```
-R 75292
-R 118588
-R 394494
-R 815813
```

**Comment by durbrow** [comment]
@jaum20 There is a limit to the number of `-R`'s (500 IIRC). But `-R` can accept a comma separated list of rows, try combining multiple rows at a time, e.g. `-R 75292,118588,394494,815813`.
