### ISSUE TITLE
fasterq-dump without network connection

### ISSUE THREAD

**Issue by willtownes** [ncbi/sra-tools#302]
I'm aware that fasterq-dump can operate on an SRA file on the local file system (eg if I already downloaded it using prefetch). However, in my computing environment only the login node has access to the internet. If I want to submit jobs to non-login nodes to run fasterq-dump on a large number of SRA files, I get the error "Failed to call external services.", which I believe indicates that fasterq-dump is still trying to access the internet even when I am asking it to process a local file. Can I somehow get fasterq-dump (or even just fastq-dump) to work on local SRA files without trying to access the internet? If not, I'm going to have to just run everything on the login node which will probably get me in trouble with the systems administrators.

**Comment by willtownes** [comment]
For others with the same problem, I created a [question on biostars](https://www.biostars.org/p/426430/) and the response indicates that sra tools version 2.9.6-1 does not require internet access, whereas the newer version 2.10.4 DOES require internet access. 

To the developers/maintainers of sra tools, please give us the ability to run the new version without internet access! Many research computing environments where fastq-dump and fasterq-dump are going to be run do not allow internet connections on the heavy-duty nodes.

**Comment by kwrodarmer** [comment]
The situation has become significantly more complicated over the last several months. In order to give you a proper answer, it would help if you could supply us with an example of the accessions you are accessing and how you are doing it. If there is anything confidential in that, you are welcome to write to us at sra-tools@ncbi.nlm.nih.gov

**Comment by willtownes** [comment]
Here's a reproducible example from a linux system. I install sra-tools:
```
module load anaconda3
conda activate fwt
conda install sra-tools
```
This installs sra-tools version 2.10.3. Next, with internet enabled, I prefetch a small SRA file
```
prefetch SRR000001
```
I now switch to a node without internet access and try fasterq-dump
```
fasterq-dump SRR000001 -O test 
```
It throws the following error
```
Failed to call external services.
```
I now return to the node with internet access and confirm the command works. 
```
fasterq-dump SRR000001 -O test 
ls test
rm test/*
```
This works successfully, populating the test folder with 3 fastq files, which I then remove for the next test.

Next, I downgrade sra-tools to version 2.9
```
conda install sra-tools=2.9
```
This installs version 2.9.6. I now switch to the node without internet access
```
fasterq-dump SRR000001 -O test 
```
This works successfully, populating the test folder with 3 fastq files.

**Comment by kwrodarmer** [comment]
So where did prefetch download the file, to your current directory? Can you try passing a path to the downloaded file to `fasterq-dump` rather than just giving the accession?

**Comment by lyijin** [comment]
i can independently confirm will's observations.

my repro:

(getting the precompiled binaries)
```
wget "http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.4/sratoolkit.2.10.4-ubuntu64.tar.gz"
tar zxvf sratoolkit.2.10.4-ubuntu64.tar.gz
```


(setting up the test)
```
cd ~/test
~/tools/sratoolkit.2.10.4-ubuntu64/bin/prefetch SRR000001 -O prefetch/
```

(fasterq-dump WITH internet connection)
```
foobar@EMU-RI:~/test/prefetch$ ~/tools/sratoolkit.2.10.4-ubuntu64/bin/fasterq-dump ~/test/prefetch/SRR000001/SRR000001.sra
```

> 2020-03-25T04:34:11 fasterq-dump.2.10.4 err: name not found while resolving query within virtual file system module - failed to resolve accession '/home/foobar/test/prefetch/SRR000001/SRR000001.sra' - Cannot resolve accession ( 404 )
> spots read      : 470,985
> reads read      : 1,883,940
> reads written   : 707,026
> reads 0-length  : 468,635
> technical reads : 708,279

hmm, the 404 looks like it's accessing the internet for... something.

at this point, i removed the fastq files produced from `fasterq-dump`; then i FORCIBLY DISCONNECTED my machine from the internet.

(fasterq-dump WITHOUT internet connection)
```
foobar@EMU-RI:~/test/prefetch$ ~/tools/sratoolkit.2.10.4-ubuntu64/bin/fasterq-dump ~/test/prefetch/SRR000001/SRR000001.sra
```

> Failed to call external services.

as a side-note, perhaps this might be because i didn't set up my `vdb-config --interactive` properly? i set a directory for user-repository but didn't set any for process-local. i set prefetch downloads to "current directory", but i disabled the default behaviour by specifying `-O` in `prefetch`.

i disabled local file-caching for the test. i'm assuming this does not affect `fasterq-dump` if i fed it locally-grown, grass-fed files?

**Comment by jfmrod** [comment]
Hi everyone, sorry to hijack the thread here. I have a similar/related problem, ideally I would prefer to run fastq-dump without an internet connection (so I can run the command on cluster nodes), I sidestepped the problem by giving the nodes access to the internet.

The problem now seems to be that the NCBI servers that fastq-dump is contacting are blocking my connections when a lot of jobs start simultaneously. I previously download the sra files via aspera (I am aware not all runs are available anymore over aspera).

**Comment by jfmrod** [comment]
If anyone stumbles on this problem, my fix for now was to add a random delay of up to 1 minute before executing fastq-dump such that the requests are not dropped by the NCBI server.

something like:

sleep $(( RANDOM/300 ))

works perfectly if you are using bash.

Of course it only works if you have internet access from your cluster nodes.

**Comment by amizeranschi** [comment]
@kwrodarmer is there any update on this issue? 

@lyijin I also got the error (`Failed to call external services.`) when local caching was disabled, but things worked fine when it was enabled (`vdb-config -s "cache-enabled=true"`).

I've been using `vdb-config` non-interactively, like this:

```
rm -rf ~/.ncbi   ## this deletes the previous config; make sure to have a back-up if needed
vdb-config --restore-defaults
vdb-config -s "/repository/user/main/public/root=."
vdb-config -s "cache-enabled=true"
```

**Comment by kwrodarmer** [comment]
So I suppose it would make sense to write a Wiki page about this. I hope we can get time to do so.

When the SRA started, our main mode of locating database objects was to search the filesystem according to some rules and configuration files. Later on, we introduced remote file retrieval to the tools themselves for on-demand access. The process was
1. look for objects locally under user's account
2. look for objects on shared filesystems - the "site" repository
3. look for objects remotely at NCBI - over the network

Later on, some very large run submissions began to contain morbid malformations that sometimes are the result of bad aligners but also can be the result of intentional manipulations. These affected our software's cache predictions and introduced severe random access that increase processing times by an order of magnitude. Since we do not tell submitters what to put into their runs, we instead introduced a mechanism to cache the expensive seeks into a secondary object, identified by a ".vdbcache" extension. These objects could be added retroactively, so the primary object was not aware of the cache.

Because our default mechanism of locating files was to search the filesystem, there would be no mechanism to indicate whether a vdbcache object was available or not, other than by searching for it too. This meant that even if you had downloaded a run SRRxxxxxx and apparently had no further need for network access, we probably would try if no vdbcache file could be found locally, since we would probe to see if one might exist remotely.

By now, we have so many objects in the SRA that it is ineffective to search multiple filesystems (especially over SMB) and we have expanded the meaning of a run accession so that it includes not only ETL but original and derived versions. We attempt to contact the SRA metadata database to learn what we need to know about an SRA object while processing.

The SRA and the SRA Toolkit have evolved from simple CLI tools that operate in transparent ways to complex tools that interoperate with a backend. Our move to the cloud has only increased the complexity as we try to preserve as much backward compatibility as possible at the same time that we introduce new features.

As we go forward, we will try to smooth out the bumps that have been introduced, but may not be able to address everyone's needs simultaneously.

**Comment by durbrow** [comment]
This is probably because `path_to_sra_file/SRR000001.sra` exists and `path_to_sra_file/SRR000001` does not.

**Comment by chubukov** [comment]
I recently used cloud data delivery, which delivered two files for each SRR accession: `{accession}.1` and `{accession}.vdbcache.1`.

When I run `sam-dump /path/{accession}/{accession}.sra` there is a huge amount of network activity that's generated. How do I ensure that the local cache file is being used? Or are there additional considerations?

**Comment by durbrow** [comment]
You don't want to `sam-dump /path/{accession}/{accession}.1`. If you are in the same directory that you ran `prefetch {accession}` in, then `sam-dump {accession}` will do what you are expecting.

**Comment by chubukov** [comment]
@durbrow thank you! it would be fantastic to add that to the documentation, was totally not clear to me.

**Comment by klymenko** [comment]
IF YOU WANT TO WORK WITHOUT NETWORK CONNECTION == YOU DON'T WANT TO ENABLE REMOTE ACCESS
=>
run `vdb-config -i` and make sure `Enable Remote Access` is not checked.

But make sure you used prefetch first.
Having just sra run files is not always enough.

**Comment by klymenko** [comment]
@chubukov, see https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump
