### ISSUE TITLE
how to import ngc file and decrypt dbgap data

### ISSUE THREAD

**Issue by clagiamba** [ncbi/sra-tools#307]
Hi,

I am trying to decrypt a "data.ncbi_enc" file, and I have a project key downloaded from the dbGaP website “get dbGaP repository key”, e.g. "prj_00000.ngc", which I placed in the same directory as my "data.ncbi_enc". 

I was trying to follow these guidelines: 
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=dbgap_use#s-4 
But I see that the --import has been deprecated in vdb-config. 
When I run "vdb-config -i", a dialog box starts with the following TABs: 

"SRA configuration
save exit discard default 
MAIN CACHE AWS GCP NET TOOLS"

I do not see anywhere an "Import Repository Key" as shown here: 
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=dbgap_use#s-3

What can I try? 
Thank you

**Comment by gokceneraslan** [comment]
Oh, I'm experiencing exactly the same!

**Comment by gokceneraslan** [comment]
vdb-config -i screenshot:

![image](https://user-images.githubusercontent.com/1140359/78842380-d068b100-79cd-11ea-8560-1cc4ddf00754.png)


vdb-config --import output:

![image](https://user-images.githubusercontent.com/1140359/78842439-f0987000-79cd-11ea-85d4-e12798d6005a.png)

**Comment by gokceneraslan** [comment]
@kwrodarmer any ideas?

**Comment by kwrodarmer** [comment]
I apologize for the lack of response!

There were a **huge** number of changes made to the 2.10.x series in order to operate within commercial clouds. Many of the new technical requirements caused several changes in the user experience that we were unable to preserve. One of the biggest of these changes is around how we handle permissions and tokens.

The SRA Toolkit used to import an NGC file and associate it with a dbGaP project, which was in turn associated with a workspace with a root directory in your filesystem. What we have now is that you specify the NGC file on the command line when invoking the tool, and it no longer needs to be performed within a dedicated workspace. Within the cloud, you will use JWT permission tokens rather than the NGC.

So what you need to do now is to use the ngc parameter when accessing dbGaP from outside of a cloud VM. You no longer need (or are able) to import it into configuration.

Many of the download operations using prefetch will make use of the new "accession directory" that came from the cloud effort. If you prefetch SRRxxyyzz it will now create a directory called SRRxxyyzz in your current working directory and the files you retrieved will be inside of that. So an associated SRA file will be under SRRxxyyzz/SRRxxyyzz.sra.

I hope this gets you started, and we'll try to follow through with a more explanatory response.

**Comment by hermidalc** [comment]
@kwrodarmer I'm using SRA Toolkit 2.10.3 and I still cannot get things to work.  I'm a dbGaP designated download for a specific project and I downloaded my dbGaP repository key .ngc file for that project from the portal.  However, when I attempt to prefetch a run from that study and specifying the `--ngc` option and file I still get an access denied error:

```bash
$ prefetch SRR10841921 --ngc prj_xxxxx_Dxxxxx.ngc 
2020-04-13T20:34:17 prefetch.2.10.3 err: query unauthorized while resolving query within virtual file system module - failed to resolve accession 'SRR10841921' - Access denied - please request permission to access phs000452 / DS-M in dbGaP ( 403 )
```

What am I doing wrong?

**Comment by skripche** [comment]
Hello,

Please update to 2.10.5 version of the toolkit as there were some fixed in 2.10.4 relating to NGC file usage. 

Also, if you had the 2.9.X or earlier version of the toolkit installed you will need to delete your old configuration file and have vdb-config utility create a new one by running the "vdb-config -i" command and test your settings again.

**Comment by hermidalc** [comment]
> Hello,
> 
> Please update to 2.10.5 version of the toolkit as there were some fixed in 2.10.4 relating to NGC file usage.
> 
> Also, if you had the 2.9.X or earlier version of the toolkit installed you will need to delete your old configuration file and have vdb-config utility create a new one by running the "vdb-config -i" command and test your settings again.

Thanks @skripche  and @kwrodarmer.  May I ask though, on bioconda the latest available is [2.10.3](https://anaconda.org/bioconda/sra-tools), would you be able to create a new package for latest 2.10.5 so I can use this as part of my larger workflows and envs?

**Comment by agrueneberg** [comment]
I appreciate the addition of the `--ngc` parameter to `vdb-decrypt` (it's **infinitely** better than setting up workspaces and importing keys), but please update the documentation at https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=std accordingly.

**Comment by Caffeinated-Code** [comment]
I agree with @agrueneberg here. The --ngc parameter is so much easier to use! We just need the dbGAP project repository .ngc key

To sum it up at the risk of being redundant,
**Decrypting non-SRA data**
# Individual .ncbi_enc files,
_vdb-decrypt <Absolute Path to prj_00000.ngc>  <data.ncbi_enc file>_
# Directory containing .ncbi_enc files,
_vdb-decrypt <Absolute Path to prj_00000.ngc> <pathToDir>_

**Decrypting SRA data**
https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data

**Comment by klymenko** [comment]
@clagiamba, do you still need help?

**Comment by clagiamba** [comment]
Hi, I am sorry for not following up, I did the steps that were suggested here and it worked great! Thank you so much!
