### ISSUE TITLE
download original format of 10X data

### ISSUE THREAD

**Issue by blsfoxfox** [ncbi/sra-tools#309]
Hi,

I am working with some 10X data from https://www.ncbi.nlm.nih.gov/sra/?term=SRR7765424.
I am suggested to find the original format bam file like this one, https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR7536866.

May I know how to download that from sra-tools 2.10.5? I have ngc file and have tested that I can download sra files or sam files, but not sure how to specify the original format data.

Thanks,
Bb

**Comment by kwrodarmer** [comment]
The NGC file is useful for accessing "controlled access" (dbGaP) data. To obtain original submissions to dbGaP, you must instead obtain a JWT version of your access permissions (not the NGC), and you must execute from within a compatible cloud region. You should configure your toolkit to provide compute environment tokens.

When you run `prefetch` you should use the `--perm` option rather than the `--ngc` and pass a path to your JWT object.

**Comment by blsfoxfox** [comment]
I got it, thanks for the information!

**Comment by munrosa** [comment]
@kwrodarmer we need to download the same type of 10X original submission data from dbGaP but we need to download to our own protected data instance for analysis. Is there a direct download option instead of using a cloud provider?

**Comment by kwrodarmer** [comment]
We only make original submission data available in the cloud. dbGaP data, being controlled, have some technical limitations that come from support available from cloud providers. (And I'm in a meeting with one right now talking about this very issue!)
