### ISSUE TITLE
sam-dump missing information about paired-end reads

### ISSUE THREAD

**Issue by ericjanfoss** [ncbi/sra-tools#324]
I have been trying to download sam files for paired-end alignments for the 8 accessions from SRR7749697 to SRR7749704.  I have tried a variety of things, including downloading the .sra object and using this command:  

sam-dump --header --output-file  SRR7749697.sam  SRR7749697.sra

(Ideally, I would like to get two fastq files, _1.fastq and _2.fastq, for each sample, as raw unaligned fastq files for each sample, but I understand that these aren't available.)  

The sam-dump command above gives me a sam file, but all of the information about the paired-end reads is missing.  For example, RNEXT is always "*", and PNEXT and TLEN are all 0.  This shouldn't be, since these are paired-end reads.  Can someone help me with this?

Thanks very much. 

Eric

**Comment by osris** [comment]
try using fastq-dump utility like this:
 fastq-dump --split-files SRR7749697 
i am not sure why all samflag values are set to 0. i'll have to check the submitted file

**Comment by osris** [comment]
@ericjanfoss  i checked the original source bam file. it's flags were set to 99 and 163 , but those are defaults you get when specifying 2 fastq files for a bowtie alignment.  there are no matching RNAME values in the files. it looks like the 2 fastq files used for input came from 2 different lanes of the same illumina plate, but there are no pairs.  SRA processing uses matching RNAME values to check for pairing - doesn't trust the flag value because they are frequently wrong.  SRA recalculates samflags, CIGAR, RNEXT, PNEXT, and TLEN based on what is actually found by verifying alignments.

**Comment by ericjanfoss** [comment]
Hi Osris, 

I had tried the fastq-dump statement as you wrote it; it gives two fastq files of unequal size (almost equal, but not quite).  All of the numbers indicating read numbers in the _1 and _2 file were non-overlapping and sort of interleaved.  I was told that this is was what happens when the underlying file is a bam file rather than a fastq file.  I also messed around with the "--split-3" option with no success.  

I think your second answer must be the key to the problem.  Thanks very much for looking into it so promptly.  I really appreciate it. 

Eric

**Comment by osris** [comment]
interleaved reads has nothing to do with source formatting.  if you use fastq-dump for real paired reads without the --split-files option, then the pairs will be interleaved, so that every successive 8 line block contains a pair.  these look sort of interleaved because of the order of reads in the source bam which did not quite alternate between mate1 and mate2 reads - close, but not quite.  probably a quirk of the aligner parsing process and SRA parsing of the bam file. yes, the _1 and _2 files contain non-overlapping read ids.   SRA recorded from the input that about half of these are read1 and half read2, but never found the matching pair so there are no matching names. this data is not actually paired.  probably a mistake in the bowtie command line from the submitter

**Comment by ericjanfoss** [comment]
Thanks very much, Osris.  This all makes sense.  

Eric
