### ISSUE TITLE
fastq-dump and fasterq-dump

### ISSUE THREAD

**Issue by mshelomi** [ncbi/sra-tools#334]
I want to download SRA files to my computer

fastq-dump -O /path-to-storage-harddrive/ SRR1172394
gives me errors like: 
fastq-dump.2.10.5 err: unknown while updating file within file system module - unknown system error 'File too large(27)'
fastq-dump.2.10.5 sys: unknown while updating file within file system module - KCacheTeeFileInitNew - failed to set file size of '/path-to-storage-harddrive/SRR1172394.sra.cache' to 7463401280 bytes
fastq-dump.2.10.5 sys: unknown while updating file within file system module - KCacheTeeFileOpen - failed to open cache file /path-to-storage-harddrive/SRR1172394.sra.cache' 

Same with fasterq-dump

What does it mean?

**Comment by kwrodarmer** [comment]
The error output is cryptic, yes. But what we see in there is that your operating system reported "File too large" when we were creating a cache file. This means that your system cannot create a file of the required size (7,463,401,280 bytes or 7GB). Modern systems do not have this limitation, so to help you further we will need information about your system.

Without knowing the exact cause, it looks like you could solve the problem by using a more modern system. You may have some luck trying to download the file first by using
```
prefetch SRR1172394
```

If that does not help, you can run a diagnostic tool and send us the result. Since no-one should never post information about your system in a public forum, please run the command
```
test-sra SRR1172394 > test-sra-issue-334.txt
```
and then send the output (text file) to sra-tools@ncbi.nlm.nih.gov and we will help you further via email.

**Comment by mshelomi** [comment]
Thanks! The output of test-sra is the same as above.

The problem might be that I am trying to write to an external hard drive, so there is a limit to the file size that I can download.
What is the recommended workaround? And what is the difference between fastq-dump and prefetch?  I plan to align the SRA files to a genome fasta file with Bowtie2, so what exactly do I need to download?

**Comment by kwrodarmer** [comment]
Some filesystems (e.g. FAT16) cannot represent files greater than 4G in size. FAT16 is commonly used for small external drives because it can be used with just about any OS, but it has limitations on the maximum file size as well as the maximum total capacity of the drive.

You can reformat your drive with something else. If you're running Linux, you can use a variety of filesystems, e.g. ext3 or ext4.
