### ISSUE TITLE
Prefetch: no error message but can't find the downloaded file (already checked home/username/ncbi)

### ISSUE THREAD

**Issue by jenniferyjlin** [ncbi/sra-tools#339]
Hi, I'm using a server hosted by DigitalOcean (ubuntu 18.04) to run the code in the latest version of sra-toolkit (sratoolkit.2.10.7-ubuntu64). 

I ran
**./prefetch --output-directory /home/jennifer/ SRR10611700** 
in order to download the src files but I got no message showing the file was successfully downloaded nor any error message showing what's the problem.

I'm not sure if the file was downloaded. If it is, where is the file? I've already checked **/home/jennifer/** and  **home/jennifer/ncbi** but none of these places contains the file.

**Comment by wangyongquan666** [comment]
i also

**Comment by kwrodarmer** [comment]
We will investigate how this is possible (to receive no messages), because `prefetch` is one of the tools that generates the most human-readable output.

By the way, SRR10611700 is human, and you are not using an authorization token for download, which is required to access dbGaP. Please read https://github.com/ncbi/sra-tools/wiki/03.-Quick-Toolkit-Configuration and https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data if you haven't already.

**Comment by klymenko** [comment]
@jenniferyjlin, @wangyongquan666, do you still need help?
