### ISSUE TITLE
SRR2194574

### ISSUE THREAD

**Issue by darwinchangz** [ncbi/sra-tools#351]
Hello, I'm having issues with the fastq-dump speed of a specific file (SRR2194574) in a set of files. The speed is about 10x slower than that of its related files. Is this a specific storage issue or network issue? It's not just an issue with file size, it's the network speed of the fastq-dump that isn't present in any of the other samples in the same group.

**Comment by kwrodarmer** [comment]
We will take a look. Before I investigate, though, could you tell me how you downloaded the run or if you are downloading on-demand?

Also, `fasterq-dump` can be faster in many cases.

**Comment by darwinchangz** [comment]
With the software I have, fasterq-dump is not an option. I've tried it earlier. 

fastq-dump --split-files --skip-technical --gzip --ngc "$ngc" SRR219574

I've used this option for all the files in the group and this one has progressed the slowest by a significant amount

**Comment by kwrodarmer** [comment]
You should not use the `--gzip` option: you will get better performance by running the gzip tool itself on output.

It would be good to know why `fasterq-dump` is not an option, since it is a replacement for `fastq-dump` which is our most ancient tool.

I have not investigated SRR219574 _(it is 1AM here and we won't be open until Monday morning)_, but if it turns out to be a particular class of run, you should first ensure you download it using `prefetch` to make sure you get some pre-cached information.

**Comment by kwrodarmer** [comment]
Hi @darwinchangz - did something change?

**Comment by darwinchangz** [comment]
Not 100% sure, but it seems better now. Whether it was my end or sra's end I'm not sure, but the download is faster.

**Comment by kwrodarmer** [comment]
Okay, great to hear. Let us know if the problem comes back.
