### ISSUE TITLE
Indexing for blastn_vdb

### ISSUE THREAD

**Issue by taltman** [ncbi/sra-tools#353]
I'm trying to understand better some of the tools in the SRA toolkit, like `sra-search` and `blastn_vdb`. Unfortunately, I cannot find any documentation for these tools, aside from a few words in the command-line help output.

In particular, I'm trying to understand `blastn_vdb`. As far as I can tell, it considers the SRA file(s) to be the "database", and the multi-FASTA nucleotide file to be the "query". Aside from downloading the SRA files, is `blastn_vdb` also indexing their contents? Does it index it from scratch every time one searches against a set of SRAs, or is this index persisted somewhere, like in a cache? If the SRAs are not being cached, then can the "query" be indexed?

Thanks,

~Tomer

**Comment by taltman** [comment]
Just checking in. Any insight into how `blastn_vdb` is extracting sequences from the VDB files and indexing them would be very helpful. Thanks in advance!

**Comment by kwrodarmer** [comment]
Hi @taltman  - yes, we're working on it. We're trying to knock down variables to get you running. Expect a new release shortly that we'll need to evaluate to see if it helps or if there are other issues that arise.

`blastn_vdb` (the blast tool set) has been modified. It was opening a database connection preemptively because that's a useful thing to do sometimes, but when you throw a huge number of VMs at the database, it starts to complain. You discovered that, so we are turning off the pre-open. There were changes to VDB as well.

So please hang in, and we'll be with you ASAP.

**Comment by taltman** [comment]
@kwrodarmer Awesome, thank you so much for digging into the issue! I appreciate everyone's help.

Just to note that this issue is distinct from the other issue created regarding database connection errors I was getting when running large numbers of `blastn_vdb` jobs from a single server. This is more of a request for documentation on some of the `blastn_vdb` internals.

Thanks!

**Comment by kwrodarmer** [comment]
Alright, let me take a pass at it, but then I'll turn it over to the blast team.

`blastn_vdb` treats one or more SRA runs as the "database" for a query, as you mentioned. Blast doesn't index the database, but indexes the query (FASTA) and uses that to scan the database. It does index from scratch every time, but this isn't where your time would be lost, assuming you find it going up in smoke over downloads.

VDB defaults changed between 2.9 and 2.10 to no longer cache runs permanently. You can still set that up, but you get the effect you want by using `prefetch` so that the runs stay around in the file system.

**Comment by klymenko** [comment]
@taltman, do you still need help?

**Comment by taltman** [comment]
My apologies for not following up sooner. Thanks for confirming my understanding of how `blastn_vdb` switches the notion of what is the "query" and what is the "target" or "database", relative to plain-vanilla NCBI Blast+.

I'm a bit confused when you write that "Blast doesn't index the database". Are you referring to `blastn_vdb` or plain-vanilla NCBI Blast+ `blastn`? I thought that with plain-vanilla NCBI Blast+, you have to run makeblastdb before you're able to search the FASTA sequences (which I assume involves indexing for faster retrieval). 

My experience profiling `blastn_vdb` was that the query time scales well with the size of the "database" (being the one or more SRA runs), and that it scales poorly (super-linear) with the size of the "query" (the input FASTA). If `blastn_vdb` is indexing the query, I'd expect it to scale well with the increase in the "query" size, and poorly with the increase of the "database". 

I'd appreciate it if you could clarify those parts for me. Thanks!

... and happy holidays!

**Comment by klymenko** [comment]
@taltman, send your question to blast-help@ncbi.nlm.nih.gov

**Comment by taltman** [comment]
I could, but then I think they'll send me back here, as I'm describing behavior that I see in `blastn_vdb` that differs from plain-vanilla NCBI Blast+ `blastn`.

**Comment by klymenko** [comment]
`blastn_vdb` and `tblastn_vdb` are made by blast team.
We can answer your questions about how SRA data is fetched - it's done by our library.

**Comment by taltman** [comment]
Ah, sorry for the confusion. I though that it was a custom build from the SRA team. I'll send my questions there going forward.

Thanks again, and happy holidays!

**Comment by klymenko** [comment]
Yes, we build the code made by blast team.
