### ISSUE TITLE
vdb-decrypt cannot decrypt bam files from dbGaP

### ISSUE THREAD

**Issue by ma-tongji** [ncbi/sra-tools#356]
Hi there,

I tried to decrypt a bam file with ngc key, but it fails. Here's the error message
```
#  sratoolkit.2.10.7-centos_linux64/bin/vdb-decrypt --ngc prj_25652.ngc  SRR10720553/S10_possorted_genome_bam.bam
```
```
2020-06-10T02:32:40 vdb-decrypt.2.10.7: Decrypting file in place S10_possorted_genome_bam.bam
2020-06-10T02:32:40 vdb-decrypt.2.10.7 err: size incorrect while constructing file within cryptographic module - error constructing decryptor
2020-06-10T02:32:40 vdb-decrypt.2.10.7: skipping S10_possorted_genome_bam.bam
2020-06-10T02:32:40 vdb-decrypt.2.10.7: exiting: success
```
Do you have any idea how to fix this? Thanks

**Comment by ma-tongji** [comment]
Hi kwrodarmer,

Thanks for the reply. I downloaded the bam with the "fusera" program. The original filename is S10_possorted_genome_bam.bam, and I also validated md5 the same as the original file.

But I failed to process this file with samtool or any other tools. With head command I see a NCBInenc marker at the start of the file. Do you have any idea how to deal with this file?
![ss.png](https://i.loli.net/2020/06/12/qH4au5PliVnQCRB.png)

**Comment by kwrodarmer** [comment]
This is very interesting! Not for you, obviously.

You used "fusera." Did you run from within a commercial cloud? I encourage you to send an email to sra-tools@ncbi.nlm.nih.gov and reproduce your exact commands so that we can help debug the situation.

The details you provide show that you received an encrypted dbGaP file. These can only be accessed using vdb-decrypt or another SRA Toolkit tool that is capable of decrypting, provided that you have an associated NGC file to provide for decryption.

That said, from the description you give, I am not quite sure how you ended up where you are! Please send the full details to NCBI at the email I provided so that we can understand it more fully.

**Comment by ma-tongji** [comment]
Hi kwrodarmer,

Thanks. I have send an email about the detail procedure how I get the bam file.
