### ISSUE TITLE
faste-dump

### ISSUE THREAD

**Issue by elbakrifz** [ncbi/sra-tools#366]
when I used fastq-dump --split-files SRR6369642, I receive srapath.2.10.1 int: transfer incomplete while writing file within network system module - cannot Get Cloud Location

**Comment by kwrodarmer** [comment]
In order to help you out, you should update to the latest software on our download page:
https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit

Then, we will need to know your execution environment, e.g. what OS, type of system, are you in a cloud (AWS, GCP), etc. Please write back with more details.
