### ISSUE TITLE
fastq-dump failed

### ISSUE THREAD

**Issue by elbakrifz** [ncbi/sra-tools#374]
I used this command fastq-dump --split-files SRR6369642
I got 2020-07-01T16:36:37 srapath.2.10.1 int: transfer incomplete while writing file within network system module - cannot Get Cloud Location
Read 1564712 spots for SRR6369642
Written 1564712 spots for SRR6369642
and when I use fastq-dump --split-files SRR6369659
I got : 2020-07-01T16:50:07 srapath.2.10.1 int: transfer incomplete while writing file within network system module - cannot Get Cloud Location
2020-07-01T17:44:30 fastq-dump.2.10.1 err: timeout exhausted while waiting condition within process system module - failed SRR6369659

**Comment by durbrow** [comment]
You may want to `prefetch` the data first. The `prefetch` tool is much better at handling network issues, for example, it can resume a failed download.

As an aside, unless there is a reason you can not, you might want to use `fasterq-dump`. It really is *much* faster than `fastq-dump`.

**Comment by klymenko** [comment]
@elbakrifz , please try [our new 2.10.9 release](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).
We improved tolerance against network failures.

**Comment by picsaver** [comment]
> @elbakrifz , please try [our new 2.10.9 release](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software). We improved tolerance against network failures.

thank your folks update this tool , but the error "timeout exhausted while waiting condition within process system module" is still met when using the last version (3.0.0). 

[error message] `2022-08-04T12:25:09 fastq-dump.3.0.0 err: timeout exhausted while waiting condition within process system module - failed SRR14851095`

My question is, Can `fastq-dump` resume the failed download like as `prefetch`?  Thank u~

(I do not use `prefetch` because it  cannot split the target into several pieces to download parallel, but `fastq-dump` can )
