### ISSUE TITLE
fasterq-dump with --outfile parameter not setting an extension to single-end files

### ISSUE THREAD

**Issue by probalica19** [ncbi/sra-tools#388]
Hi, 

I've noticed that parameter `--outfile` (SRA fasterq-dump v2.10.8) behaves differently with single-end and paired end data.

Running `fasterq-dump --outfile test123 SRR12215007` results in one file named `test123` (no .fastq extension), but when I run `fasterq-dump --outfile test123 SRR980482` i get two output files named `test123_1.fastq` and `test123_2.fastq`, with both files having appropriate extensions. 

Is this the expected behaviour?

Thank you!

**Comment by wraetz** [comment]
Yes this is the expected behavior. In the case of single-end source accessions, or you force the tool into producing only one file ( --concatenate-reads, which was the default for the older fastq-dump tool  ) the tool takes the outfile-parameter verbatim and does not add or remove anything to/from the given filename. However if the accession is paired, the tool be default produces 2 files. And in the case there are unpaired reads in the accession it even produces 3 files. In this case the tool adds '_1.fastq' and '_2.fastq' ( optional '_3.fastq' ) to the given filename - to mark which half of the read the file contains.

**Comment by wraetz** [comment]
I have to correct myself a little bit regarding _3.fastq: this file is named just .fastq!
your options with an example are:

Option 1: 'fasterq-dump SRR000001'
produces: SRR000001_1.fastq, SRR000001_2.fastq and SRR000001.fastq

Option 2: 'fasterq-dump SRR000001 -o something'
produces: something_1.fastq, something_2.fastq and something

Option 3: 'fasterq-dump SRR000001 -o something.fastq'
produces: something_1.fastq, something_2.fastq and something.fastq

I think the best option for you is option 3.

**Comment by uros-sipetic** [comment]
Hey @wraetz  , I noticed a similar behavior, let me write up the example:
1. If I run fasterq-dump with a SRA accession ID from which I expect single end reads, depending on the --outfile parameter, this is how it behaves:
* fasterq-dump SRR000001          ->          produces SRR000001.fastq
* fasterq-dump --outfile my_sample SRR000001          ->          produces my_sample (not my_sample.fastq)
2. 1. If I run fasterq-dump with a SRA accession ID from which I expect paired end reads, depending on the --outfile parameter, this is how it behaves:
* fasterq-dump SRR000002          ->          produces SRR000002_1.fastq & SRR000002_2.fastq
* fasterq-dump --outfile my_sample SRR000002          ->          produces my_sample_1.fastq & my_sample_2.fastq

I think @probalica19 was having issue when running fasterqdump, with the SRA accession ID from which single end reads are expected, and the --outfile parameter is provided, where it doesn't append the '.fastq' suffix, but in all other situations it does so

**Comment by uros-sipetic** [comment]
Also @wraetz, I remember the behavior you speak, where the fastq-dump (and probably fasterq-dump) would produce those three different FASTQ files, which is what the --split-3 option did, correct?
However, it seems that the latest version of SRA toolkit (2.10.8) doesn't behave that way. I didn't follow the recent release for some time, so please forgive if I'm getting anything wrong, but by running this latest version, everything seems to be working how I would expect it, without the need to set any parameters (nor --split-files nor --split-3): if I expect single end reads, I get one file, and if I expect paired-end reads, I get two files

**Comment by wraetz** [comment]
The difference is between fastq-dump and fasterq-dump. Not just the latest version.
fastq-dump has to be told to produce 2/3 files with --split-3.
fasterq-dump does this by default, and has to be told not to split if somebody wants that.

**Comment by uros-sipetic** [comment]
Oh cool, thanks
So is the behavior described above expected? In the case where you expect single end reads with fasterq-dump, and you use the --outfile option, that the '.fastq' suffix is not added?

**Comment by kwrodarmer** [comment]
Hi @uros-sipetic,

> and you use the --outfile option, that the '.fastq' suffix is not added?

Yes, that is the behavior. The issue is slightly more complicated, however.

Normally, people don't use the `--outfile` option, but they let the tool generate it from the accession. If someone goes to the trouble of giving us the desired name, we respect that and don't try to rename it to anything else. If you want the `.fastq` extension, just provide it to the tool.

It gets more complicated where we have to produce the split files, because we can't use your provided file name for 2 or 3 different files, of course. So in that case, we do modify your specification.

**Comment by uros-sipetic** [comment]
Thanks @kwrodarmer. 
The reason for wanting to use the --outfile option is because of another 'inconsistent' behavior between fastq-dump and fasterq-dump, when running for SRA files (not accession ID).
Namely, running this command:
`fastq-dump SRR000001.sra` 
will produce the SRR000001.fastq file (presuming it contains just single-end reads)
However, running this command:
`fasterq-dump SRR000001.sra` 
will produce a file named SRR000001.sra.fastq

This '.sra' remains in the names of FASTQ files when using fasterq-dump and running from SRA files. This was one the reasons for wanting to use the --outfile parameter (to just set it to the SRR000001 for example, in this case), in order to automatize a pipeline where both SRA files and accession IDs can come along, containing both paired-end reads or single-end reads only

**Comment by kwrodarmer** [comment]
Ah, I see! I'll create a bug report for that and have it fixed. Is there a reason you're appending the `.sra` to the input? The tool is designed to work on the filename without extension.

**Comment by uros-sipetic** [comment]
Not actually me that appending those extension, usually those types of files come to me/us for analyzing. I suppose people like or need to have extensions in their file system, so we get FASTQs, BAMs or SRA files to analyze

**Comment by kwrodarmer** [comment]
Oh the files have the extension in their file system. But SRA Tools work on accession more than filename. We expect people to give us the raw accession and let us locate the file with it. Regardless - we'll update `fasterq-dump` to remove `.sra` before generating `.fastq` extensions.

**Comment by klymenko** [comment]
@probalica19, do you still need help?

**Comment by sgsutcliffe** [comment]
If I understand this issue correctly, if there is an accession that has both paired and single-end reads. There is no way to use `--outfile` and have all three files with the `.fastq` extension? An example would be for something like this [ERR1109373](https://www.ebi.ac.uk/ena/browser/view/ERR1109373)
