### ISSUE TITLE
Different raw data size

### ISSUE THREAD

**Issue by dahun73** [ncbi/sra-tools#397]
Hello,

I'm using sra-tools, actually fastq-dump now.
I have some questions for download data in ncbi.

In NCBI, raw data size is written for 395Mb.
![image](https://user-images.githubusercontent.com/52641420/90090719-ba924080-dd5f-11ea-89ec-6a2b36faf3ec.png)
But when I downloaded rawdata using fastq-dump, it is 718Mb.
![image](https://user-images.githubusercontent.com/52641420/90090825-f3cab080-dd5f-11ea-9d00-c49a2b1288ee.png)

It is ChIP-seq data, so it is single-end. What is the real size of these raw data?? And why it is different? 

Thanks!

**Comment by wraetz** [comment]
What you call "NCBI, raw data" is a compressed archive. The size of it is shown in the run-selector.
When you are "downloading", you are actually decompressing this archive.
Then you are re-compressing the produced plaintext fastq-file into a XXX.fastq.gz.
The actual plaintext fastq-file is even bigger...
Why are we not showing the uncompressed size on our web-site?
Because there are many different ways to create fastq from it. And fastq is not the only option ( there is also sam-dump and sra-pileup ). All of these tools have many options - each of them producing a different output-file. We would have to list a lot of sizes...

**Comment by dahun73** [comment]
Thank you for reply!

I understand your reply! But I downloaded this fastq using 'fastq-dump --gzip' option. I mean it's the same compressed fastq. In the run-selector, samples are shown with compressed size. Why do they have huge different size eventhough they are same compressed fastq. Is it just the difference of the compress method like gz, bzip or zip?

**Comment by wraetz** [comment]
your wrote: 'they are same compressed fastq;.
They are not. A sra-archive aka what is shown in the run-selector - is a special format developed by NCBI. It is about twice as efficient in compressing if used on raw fastq. It is even more efficient if the data has been aligned. In this case we are recording just the difference to the reference-sequence. That is also the reason why some archives are stand-alone and others need reference-files in order to be converted.

**Comment by klymenko** [comment]
@dahun73, do you still need help?

**Comment by abhishekajmani** [comment]
I am also facing this issue. I am able to follow the chat, however, using the chat I am unable to figure out a way to ensure that the file I have downloaded is complete or is downloaded fully. I would appreciate your efforts in helping us if you can suggest a method to compare the size of file mentioned on the website vs the size of the file we obtain after the file is downloaded irrespective of the compression and other such thingsIwhich happens while we download the data. In my case, I downloaded the data through SRA tool kit. I used the following command to download the data as suggested in one of the youtube tutorials. fastq-dump --gzip --defline-qual '+' SRR8185411
I downloaded the file with RUN number SRR8185411 and I got the size of file on my computer as **684.8 MB (68,48,05,986 bytes)**, however, I don't have any idea whether it used 1024 or 1000 as conversion factor for kb, mb etc. Also, I tried converting using these conversions factors, but I failed miserably to compare the size of the files. The size of the file as mentioned in the SraRunTable.txt downloaded through the SRA website for the same file is 634030820 bytes. 
The version of Conda I used is Conda 4.9.2
The file I downloaded or the format I got on my computer is SRR8185411.fastq.gz

**Comment by klymenko** [comment]
@abhishekajmani, do you use `prefetch`?

If the exit code `fastq-dump` is `0` and its last last message of `fastq-dump` is `Written NNN spots for SRR8185411` - then `fastq-dump` is compete.

**Comment by abhishekajmani** [comment]
Thank you for replying Sir. I want to say that as you suggested, I will try this. Actually, I did not check the exit code of fastq-dump, however, I remember that one message appeared "* spots downloaded". So, I think as per your answer my fastq-dump command was complete.

**Comment by abhishekajmani** [comment]
Sir, out of curiosity I want to ask if one file contains N spot as mentioned on the website and if during download, the message appears that N spot downloaded. I want to confirm that if we can compare the number of spots to know if the file has been downloaded properly.

**Comment by klymenko** [comment]
@abhishekajmani, about prefetch see https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump

I asked somebody from SRA support to answer your question about number of spots.

**Comment by abhishekajmani** [comment]
fastq-dump --gzip --defline-qual '+' SRR8185412
        

Read 16556385 spots for SRR8185412
Written 16556385 spots for SRR8185412

Today, now only after seeing your answer I tried downloading this file. I find your answer to be very useful and knowledgeable. Further, it has given me guidance as to how to find if the file has been downloaded properly. I hope that others will also be benefited by your answer to my questions. 

Once again many  many thanks for answering in a nice manner. You are a nice person. Nice experience of coming across you Sir.

**Comment by lapointr** [comment]
Yes, as you found the number of spots can be used to determine whether you have successfully downloaded your fastq files. If the number of spots reported by fastq-dump matches the number of spots listed for this Run, then download was successful. There are exceptions to this - you can dump a subset of spots using the -X flag, or spots can be removed from the sequence set after processing because the reads were too short or filtered out. But these are relatively rare cases and you can generally use the message indicating the number of spots that were read and written to infer that your  fastq-dump download is complete.
