### ISSUE TITLE
Error while using fastq-dump to convert sra to fastq

### ISSUE THREAD

**Issue by XinmingTu** [ncbi/sra-tools#434]
Hi,  It doesn't work when I use the `fastq-dump` to convert sra file to fastq file.
Actually, It stopped after runing for a long time. 
My `fastq-dump` version is `2.10.8` 
The command line is 
```
>>fastq-dump  --split-files  ./SRR5815723.sra
2020-10-29T11:42:43 fastq-dump.2.10.8 err: transfer canceled while allocating buffer within file system module - Cannot KHttpFileTimedReadChunked
2020-10-29T11:42:46 fastq-dump.2.10.8 err: data corrupt while selecting function within transform module - failed ./SRR5815723.sra
```

I used `prefetch` to download the data and before using `fastq-dum` I use the `vdb-validate` to check the sra file. There is no error.

Thanks for your help!

**Comment by wraetz** [comment]
After running prefetch, you should have not only the sra-file locally on your computer - but also the references it uses.
Prefetch puts them together into a directory. The fact that the tool went out over the internet to fetch the references on the fly - tells me that the file got separated from the references.

after prefetch your SRR581723 - directory should look like this:
-rw-r--r-- 1 user user   48187713 Oct 30 10:01 NC_000067.6
-rw-r--r-- 1 user user   44772776 Oct 30 10:01 NC_000068.7
-rw-r--r-- 1 user user   39264260 Oct 30 10:01 NC_000069.6
-rw-r--r-- 1 user user   38205846 Oct 30 10:01 NC_000070.6
-rw-r--r-- 1 user user   37160175 Oct 30 10:01 NC_000071.6
-rw-r--r-- 1 user user   36737100 Oct 30 10:02 NC_000072.6
-rw-r--r-- 1 user user   35629347 Oct 30 10:02 NC_000073.6
-rw-r--r-- 1 user user   31550119 Oct 30 10:02 NC_000074.6
-rw-r--r-- 1 user user   30434686 Oct 30 10:02 NC_000075.6
-rw-r--r-- 1 user user   31901008 Oct 30 10:02 NC_000076.6
-rw-r--r-- 1 user user   29809278 Oct 30 10:02 NC_000077.6
-rw-r--r-- 1 user user   29353383 Oct 30 10:02 NC_000078.6
-rw-r--r-- 1 user user   29411466 Oct 30 10:02 NC_000079.6
-rw-r--r-- 1 user user   30498950 Oct 30 10:02 NC_000080.6
-rw-r--r-- 1 user user   25278452 Oct 30 10:02 NC_000081.6
-rw-r--r-- 1 user user   23862320 Oct 30 10:02 NC_000082.6
-rw-r--r-- 1 user user   23039298 Oct 30 10:02 NC_000083.6
-rw-r--r-- 1 user user   21967330 Oct 30 10:02 NC_000084.6
-rw-r--r-- 1 user user   14626628 Oct 30 10:02 NC_000085.6
-rw-r--r-- 1 user user   41147055 Oct 30 10:02 NC_000086.7
-rw-r--r-- 1 user user   22204948 Oct 30 10:02 NC_000087.7
-rw-r--r-- 1 user user      25237 Oct 30 10:02 NC_005089.1
-rw-r--r-- 1 user user 6283288159 Oct 30 10:01 SRR5815723.sra

$ md5sum *
83ace9a2da16f7fbe5672c00d002ec9d  NC_000067.6
a83eb13ee43e2a73c0bfd8d45e41b9ab  NC_000068.7
b7072c48d8868d20cd8b623e3e0ab9d2  NC_000069.6
371992e324353a6c316a1df3e0f2b5e8  NC_000070.6
4797e5cb3bf81dbe9cd9e4ae83ccbcc3  NC_000071.6
773c6f2c859b7cdd393f4ff35a707afc  NC_000072.6
7fbbeb4e7139434b32d47a3fdecfcf0d  NC_000073.6
3f29fb3bfb4adff69f94c2eeb985f4c8  NC_000074.6
f734b84de1db9fcbd22a7cbb59569f6c  NC_000075.6
157c946aca98919344b757ad99056cbe  NC_000076.6
d4c9aa55f99b491c92bd66adf8f4f67c  NC_000077.6
3129946e2491529a0c3e9fdfdcd158e3  NC_000078.6
928c878178890394e54071b8e180bbcf  NC_000079.6
c05fbeeb7f85b42da0ebfa83ca34afe2  NC_000080.6
a3d08633e19f1c9ddaf3d68167588e9f  NC_000081.6
a74aded2e00e2dea15980e4dc3029962  NC_000082.6
ea6f9b658b359db9f355bec2f157d341  NC_000083.6
4b5a57251137b0ac1300d4225568f7df  NC_000084.6
1187d5199e07d3dfc2477ca0de3e77b8  NC_000085.6
8feeaf47f1258bff5336586c0be77226  NC_000086.7
1c0c3acaa20ff198d357b3aad29ff544  NC_000087.7
0accc8a9400138e8382118e8d28eeb96  NC_005089.1
b8cb492ce9869af12a494a9309752e9f  SRR5815723.sra

Now instead of 'cd SRR5815723' and 'fastq-dump --split-files ./SRR5815723.sra' you should instead:
$fastq-dump --split-files ./SRR5815723
In other words give the directory with all the downloaded files in them to the tool.

By the way the fastq-file will be approximately 10 times bigger than the sra-file. In this case it will produce about 44 GB.
Also: --split-files has no effect on this accession there is only one read per spot! aka it is single-ended.
Also: the new fasterq-dump tool is much faster doing the same job. It uses temporary space on your machine and multiple threads for the speed-up. the command would be: '$fasterq-dump ./SRR5815723' You do not need 'split-files' because it is the default for fasterq-dump.

here is what happens on my machine:
$ time fastq-dump --split-files ./SRR5815723
Read 117379705 spots for ./SRR5815723
Written 117379705 spots for ./SRR5815723

real    12m32.036s
user    12m10.108s
sys     0m23.248s

$md5sum SRR5815723_1.fastq
bae06c99c495a7d82de97f9efa961f91  SRR5815723_1.fastq

**Comment by XinmingTu** [comment]
Thanks for your reply! Great, I didn't know that before. Thanks for your help. I will try it later!

**Comment by klymenko** [comment]
@XinmingTu.  please try [our new 2.10.9 release](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).
We improved tolerance against network failures.
