### ISSUE TITLE
inconsistent sam-dump behavior

### ISSUE THREAD

**Issue by BKU-Technion** [ncbi/sra-tools#442]
Hello,

I downloaded SRR7480216 from PRJNA74863 using Amazon Web Services to my EC2 machine.
I use ubuntu 20.04 and sratoolkit.2.10.8.
When trying to convert the SRA format I get inconsistent behavior of  sam-dump. 
Running the same command fails at different places in the file, here are some errors I get:
 
sam-dump.2.10.8 int: timeout exhausted while waiting condition within process system module - VCursorCellDataDirect( row#30627841 . idx#3 . READ ) char_ptr failed

sam-dump.2.10.8 err: transfer canceled while allocating buffer within file system module - Cannot KHttpFileTimedReadChunked: to=480
sam-dump quit with error code 3

2020-11-30T09:57:22 sam-dump.2.10.8 int: data corrupt while selecting function within transform module - VCursorCellDataDirect( row#186486785 . idx#3
. READ ) char_ptr failed

2020-11-30T10:11:31 sam-dump.2.10.8 err: transfer canceled while allocating buffer within file system module - Cannot KHttpFileTimedReadChunked: to=24
0
sam-dump quit with error code 3

Thanks,

Guy

**Comment by kwrodarmer** [comment]
The exact steps and commands would be helpful in understanding what is going on, because your description has contradictions.

> I downloaded SRR7480216 from PRJNA74863 using Amazon Web Services to my EC2 machine.

How did you download the run? You must use `prefetch` in order to retrieve the complete run.

> sam-dump.2.10.8 int: timeout exhausted while waiting

This would indicate that sam-dump.2.10.8 is accessing data across the network rather than from your EC2 machine, which goes back to the question of how you downloaded data.

**Comment by BKU-Technion** [comment]
Thanks for the prompt reply.
I followed the instructions in this link https://www.ncbi.nlm.nih.gov/sra/docs/dbgap-cloud-access/
mounted SRR7480216  using fusera.
Copied the directory to a local directory.
Unmounted fusera and ran the command below inside the local directory. 
sam-dump --output-file SRR7480216.sam SRR7480216&

**Comment by kwrodarmer** [comment]
Okay - so that is very helpful!

Rather than using `fusera`, you should follow a separate path that involves obtaining a "JWT cart" object from NCBI and using `prefetch` to copy your data. You may be able to complete your download by running `prefetch` again. I will ask our engineers to provide a step-by-step guide. Please wait for further instructions.

**Comment by BKU-Technion** [comment]
I found this explanation https://www.ncbi.nlm.nih.gov/sra/docs/sra-aws-download/#the-sra-toolkit-in-aws
should I use it ?
Thanks again for the help.

**Comment by klymenko** [comment]
Yes, follow Youtube Video Tutorial and instruction on https://github.com/ncbi/sra-tools/wiki
