### ISSUE TITLE
Prefetch "failed to resolve accession" error

### ISSUE THREAD

**Issue by t-carroll** [ncbi/sra-tools#444]
Hello,

We are attempting to download original submission files from a dbGaP repository phs001818, following your AWS configuration instructions [here](https://github.com/ncbi/sra-tools/wiki/04.-Cloud-Credentials). After obtaining appropriate access permissions and configuring the toolkit, we were able to download 19 out of 26 files successfully using prefetch. However, for the 7 remaining accessions, prefetch failed with the following message: 

`2020-10-27T08:39:22 prefetch.2.10.8 err: name not found while resolving query within virtual file system module - failed to resolve accession 'SRR9730807' - no data ( 404 )`

This issue occurs with accessions SRR9730807, SRR9730808, SRR9730810, SRR9730811, SRR9730813, SRR9730815, and SRR9730818, even though we are able to download the other files in the same repository with the same approach (e.g. SRR9730809). Any ideas of how we could troubleshoot this further and download the original submission files for these 7 accessions via AWS?

I also reached out to sra@ and sra-tools@ncbi.nlm.nih.gov last month but haven't heard back yet, in case the further details in those emails would be useful. Thanks for your help in resolving this.

**Comment by klymenko** [comment]
@t-carroll, what command do you execute?

**Comment by DaGaMs** [comment]
The only way I could get _some_ files to download was this:

```bash
for acc in `cat accessions.lst`; do 
    prefetch -X 100G -O $PWD -p -f yes --location AWS -T tenx --perm cart.jwt -L 6 $acc
    vdb-decrypt --decrypt-sra-files --ngc ../s3bucket/prj_25285.ngc -L 6 ${acc}*.sra
    mv ${acc}*.sra ${acc}.bam
done
```

This worked on most files from this repository, but not all. The ones @t-carroll mentioned above didn't download. Any idea why those specific files didn't work?

**Comment by klymenko** [comment]
First, `.sra` files are not `.bam`.

Second, you specify `--location AWS`.
There is possibility that these files are not available on AWS.

Do the following instead:

Run `vdb-config -o`;
hit `A` to go to `AWS` tab;
make sure:
`accept charges for AWS` is not checked,
`report cloud instance identity` is checked.

Then run the same `prefetch` command without `--location`  argument.
This way data will be fetched from AWS if they are available there,
from other location otherwise.

**Comment by DaGaMs** [comment]
Maybe the rationale behind this isn't clear: the problem is that tenx sequencing data contain a barcode in the original output files which is needed to demultiplex the files into single cells. For reasons that I don't understand, this information is lost when the files are converted to `.sra`. We can download the `.sra` files "the normal way", but they are a useless pile of reads that cannot be sorted back into the cells they came from. The only way to get the raw data seems to be via AWS, see [this issue](https://github.com/ncbi/sra-tools/issues/309).

As you can see from the `prefetch` code above, I'm requesting data in `TENX` format. This should be a bam file, but `prefetch` saves them with the extension `.sra`. I presume this is a bug. In any case, from my understanding, they only way to get the correct files is via AWS, so removing the `--location` would not solve the issue.

**Comment by klymenko** [comment]
`SRR9730807` has bam file in cold store. I asked our support team to suggest you how to get it.

**Comment by DaGaMs** [comment]
Thanks for that. Just in case that was missed from Tom's initial message, it's not only SRR9730807 but also SRR9730808, SRR9730810, SRR9730811, SRR9730813, SRR9730815, and SRR9730818 that we had problems with.

**Comment by klymenko** [comment]
Please give us examples of accession when your `prefetch` command succeed.

**Comment by t-carroll** [comment]
Here are the 19 accessions from this repository that we succesfully downloaded files for using this command:
SRR10587093
SRR10587095
SRR10587097
SRR10587099
SRR9730802
SRR9730803
SRR9730804
SRR9730805
SRR9730806
SRR9730809
SRR9730812
SRR9730814
SRR9730816
SRR9730817
SRR9730819
SRR9730820
SRR9730821
SRR9730822
SRR9730823

**Comment by klymenko** [comment]
I sent a request about "TenX" "type" for those accessions to SRA support team.

**Comment by skripche** [comment]
Hello,

Source files are not available for retrieval yet from cold storage in the cloud for dbGaP studies. Once, that functionality is available you will be able to get the source files in your cloud bucket. TenX is not a file format so you will need to select "bam" as the file format. The initial functionality will be through the a web interface and the toolkit functionality will come at a later time.

**Comment by klymenko** [comment]
It looks like some of those runs have type `TenX`, and some - just `bam`.

**Comment by klymenko** [comment]
@t-carroll, do you still need help?
