### ISSUE TITLE
Prefetch "Redirected!!!" error (acsp)

### ISSUE THREAD

**Issue by EBosi** [ncbi/sra-tools#45]
Hi,
prefetch is failing and I can't understand why.
I'm using prefetch with the following command line:
`prefetch -t ascp -a "~/.aspera/connect/bin/ascp|~/.aspera/connect/etc/asperaweb_id_dsa.openssh" SRR765378`

I'm getting this error:

```
Redirected!!!

2016-11-07T09:14:41 prefetch.2.3.5 err: name incorrect while evaluating path within network system module - Scheme is 'https'
2016-11-07T09:14:41 prefetch.2.3.5 err: path not found while resolving tree within virtual file system module - 'SRR765378' cannot be found.
```
Rather mysteriously, the same line worked for the same accession one day before. Could you help me with this issue?

**Comment by klymenko** [comment]
Please download the latest toolkit from
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software

**Comment by kwrodarmer** [comment]
Please see the README, which states:

### IMPORTANT ANNOUNCEMENT
As was announced in [OMB memorandum M-15-13](https://www.whitehouse.gov/sites/default/files/omb/memoranda/2015/m-15-13.pdf) on June 8, 2015, NCBI and all Federal systems will be transitioning to using HTTPS-only protocols before the end of 2016. This change will affect any software that uses NCBI APIs such as the E-utilities or NCBI software toolkits such as `sra-tools`, `ncbi-vdb` or `ngs`.

The NLM and NCBI may implement the switch to HTTPS-only as early as September 30, 2016.

In particular, software products that depend on `sra-tools`, `ncbi-vdb` or `ngs` may not function as expected after September 30 unless they are properly updated from this site or by the software provider.

If you use software that accesses NCBI SRA data in any way, your software will likely be affected by this change. Please check with your software provider for recent udpates or patches, and be sure to acquire these before September 30.
 
If you develop software that relies on `sra-tools`, `ncbi-vdb` or `ngs` in any way, you will likely need to update your code so that it accesses NCBI using HTTPS.

We have released new tools with version 2.8.0 that are HTTPS compatible and `M-15-13` compliant as of October 7, 2016. Please be certain to [update all of your binaries](https://github.com/ncbi/sra-tools/wiki/Downloads) and configuration files.

For additional information on using, configuring, and building the toolkit,
please visit our [wiki](https://github.com/ncbi/sra-tools/wiki)
or our web site at [NCBI](http://www.ncbi.nlm.nih.gov/Traces/sra/?view=toolkit_doc)


SRA Toolkit Development Team

**Comment by EBosi** [comment]
Thank you very much for the timely reply, this basically solved my issue.
Just two more questions:
- how can I check the sra-tool version on a UNIX environment?
- can I upgrade to 2.8 using apt, or should I just use the binaries
provided in the link above? If the latter, is it safe to distribute code
including scripts from sratoolkit2.8.0-*/bin?
Thanks again
Best,
Emanuele

**Comment by kwrodarmer** [comment]
Right now, November 2016, you cannot upgrade using apt-get although it is within our future plans.

Running the tool in question with a `-V` parameter will print its version. Also, whenever it prints information to the log file, the version appears.
