### ISSUE TITLE
Missing blastn_vdb binary after succesful build

### ISSUE THREAD

**Issue by afrenoy** [ncbi/sra-tools#46]
Hi,

I am trying to build this package because I want to use blastn_vdb. I first succesfully installed ngs-sdk and ncbi-vdb.

I am then able to configure and build the master branch without getting any error, however the binary blastn_vdb mentioned in the documentation in nowhere to be found! See below the list of binaries I get in build-prefix/mac/clang/x86_64/rel/bin : everything seems to be there expect blastn_vdb (and tblastn_vdb).

Moreover I do not find any reference to blastn_vdb in any of the Makefiles. Actually the only reference I find in the source code are in test/tarballs/test-tarballs.sh and in the README.

Am I missing something obvious? Any help would be much appreciated!

## List of built binaries:

abi-dump
abi-load
align-cache
align-info
bam-load
cache-mgr
ccextract
cg-load
check-corrupt
copycat
fastdump
fastq-dump
fastq-load
general-loader
helicos-load
illumina-dump
illumina-load
kar
kdbmeta
kget
latf-load
md5cp
pacbio-load
pacbio-loadxml
pileup-stats
prefetch
rcexplain
read-filter-redact
sam-dump
sff-dump
sff-load
sra-pileup
sra-sort
sra-stat
srapath
srf-load
test-sra
vdb-config
vdb-copy
vdb-decrypt
vdb-diff
vdb-dump
vdb-encrypt
vdb-lock
vdb-passwd
vdb-unlock
vdb-validate

**Comment by kwrodarmer** [comment]
The blast tools are not part of the SRA toolkit sources. We build and distribute them the same way that we distribute 3rd party software, although we don't call it 3rd party because it's from NCBI.

This is an issue that we are discussing with the blast team. In the future, you should be able to obtain blast tools directly from them.

Short of having the sources, is there anything that you need from us?

**Comment by frenoy** [comment]
Ok, thank you for your answer.

What confused me is that the page ftp://ftp.ncbi.nlm.nih.gov/blast/WGS_TOOLS/README_BLASTWGS.txt mentions that "blastn_vdb and tblastn_vdb are part of the SRA toolkit".

I am able to download a compiled version of this toolkit from https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software (or from https://github.com/ncbi/sra-tools/wiki/Downloads) and it contains the blastn_vdb binary.

Using the binary (mac os x in my case) is in principle fine for me, but I run into a few problems because it seems that it is dynamically linked against gnutls, which requires gmp, which seems complicated to install on mac os. I am confident I can solve this issue with some patience, but I was thinking that getting the source could be much simpler!
