### ISSUE TITLE
fasterq-dump: is it possible to avoid slow lookup + merge steps?

### ISSUE THREAD

**Issue by carlosmag** [ncbi/sra-tools#503]
Hi!
In a test with 2 microbial genomes of similar size [ERR2653038](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR2653038) and [ERR046821](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR046821), I got very different running times:

`time fasterq-dump --skip-technical --split-3 --threads 6 --progress ERR2653038.sra` -> ≃ 21s
`time fasterq-dump --skip-technical --split-3 --threads 6 --progress ERR046821.sra` -> ≃ 6s

The 1st genome took much longer due to additional **lookup and merge steps**, while the later had only **join and concat**.
Why are **lookup and merge steps** being called for the 2nd genome?

Thanks in advance!

**Comment by wraetz** [comment]
The short answer is: No it is not possible.

If you are interested in an explanation:

The difference between A=ERR046821 and B=ERR2653038 is:

A is a flat table containing just bases and qualities. The tool processes slices of the table in multiple threads ( the join-step ) in parallel, then joins the output of the threads together into the final file(s) ( the concat-step )

B is a database, containing aligned and unaligned data in multiple tables. It contains not just bases and qualities, but also information where the bases align against a reference. It is compressed against the reference. That means the actual bases are not stored in the accession. What is stored is only the difference from the reference. The tool reconstructs the the bases and performs a table-join of the alignment-table with the sequence-table. First it produces a lookup-table ( the lookup-step ) in parallel on multiple slices of the alignment-table. Then the tool has to merge the lookup-tables ( the merge-step ). Then it performs the table-join ( the join-step ) again in parallel on slices of the sequence-table. At last it produces the final output-files (the concat-step).

Why is A a flat table and B a database? Because the submiters of the data sent them to us either as unaligned or aligned data! The SRA-archive tries to make every accession look like they are the same - but "under the hood" they are very different. The fasterq-dump tool makes some of these differences visible (if you opt for the progress-option).

The lookup-table is by the way the central part what makes fasterq-dump faster than fastq-dump! ( Up to 10-times faster on aligned data)

I hope that explains it.

**Comment by wraetz** [comment]
Mostly yes. It depends on the submitter. Sometimes a submitter sends a bam-file containing only unaligned data, this will end up as a flat table. But that is rare. If you want to see whats inside, use the 'vdb-dump' tool. If you run 'vdb-dump --info ERR2653038', you get a short report for this accession. In this case you see that it has SEQ, REF, and PRIM tables inside. The numbers after the table-name is the row-count in these tables. If you run 'vdb-dump --info ERR046821' you see that it has only a SEQ-table.
It is not enough to just look at type=Table/Database. Some databases have just one table! What really distinguishes them is having only 1 table (SEQ) or not.

**Comment by carlosmag** [comment]
Although vdb-dump command was relatively fast (≃ 4s in NVME disk for [ERR046821](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR046821)), I was wondering if there's a faster way to obtain this info online...

**Comment by wraetz** [comment]
OK, there is a difference based on the argument.

vdb-dump --info  ERR046821
this will go out to our servers at NIH and retrieve where to find the accession ( that is the reason for the 4 seconds )

vdb-dump --info  /home/user/data/ERR046821/ERR046821.sra
this will just inspect the given file at the given location, that one should be faster

The technical details of an accession are stored inside the accession itself, you cannot query them online.

**Comment by wraetz** [comment]
4s sounds too long to me... ( especially with a NVME-disk )

Did you call it like this:
A) vdb-dump --info ERR046821
or
B) vdb-dump --info /some/absolute/path/to/ERR046821
?

path or no path is important and makes a big difference. Even if your current directory is the location of the file in question.

About multiple fasterq-dump instances at the same time:

Only if you can afford it! Do you have a server-grade machine with lots of CPU's and lots of I/O bandwidth? (and you are not sharing this machine with other users) --- Then yes.

If not : it will be slower than doing the conversions one at a time.

**Comment by wwood** [comment]
Thanks @wraetz that is very helpful information.

**Comment by klymenko** [comment]
@carlosmag, do you need more help?

**Comment by carlosmag** [comment]
I guess my doubts were addressed! Will close thie issue! Thanks!
