### ISSUE TITLE
fastq-dump and fasterq-dump cannot find prefetched files

### ISSUE THREAD

**Issue by J-Moravec** [ncbi/sra-tools#509]
By default, `prefetch` can download files either to a pre-configured static location or to a current dir.

However, `prefetch` does have an `--output-directory` argument so that it will pre-fetch files into a specified directory.

Unfortunately, both `fastq-dump` and `fasterq-dump` are confused by this behaviour. It seems that they do expect that the files do exist somewhere, but they just sadly hang indefinitely, consuming no apparent resources, waiting for termination. This is changed when they are run from a directory that contains prefetched files.

**Suggestion:** provide a `--prefetch-dir` argument to point at prefetched files, other than current dir.

**Comment by wraetz** [comment]
Right now there are 2 possibilities:

A) you configure the toolkit via vdb-config to download into the current directory. Then you issue the prefetch-command and the tool-command ( fastq/fasterq-dump ) immediately after each other, as the same user, from the same current directory. The tool-commands find the prefetched data if they are in the current directory.

B) you configure the toolkit via vdb-config to download into a user-repository. But that requires you to have a user-repository configured. ( You have to run vdb-config at least once. ) Now the prefetch-command downloads into the user-repository, and the tool-commands will find the downloaded data there. But that requires that everything is been done as the same user.

The logic for the tools, if you issue a command like 'fastq-dump SRRXXXXXX':
1) is there a directory named SRRXXXXXX directly in the current directory? ( if found - use that )
2) is a user-repository configured and can the accession be found there? ( if found - use that )
3) go to the internet and ask a NCBI-server where the accession is located. ( if you have no internet, maybe a cluster, or there is a firewall blocking access - this will look like it is hanging, because the tool will try many, many times, with increasing timeouts to be successful. )

**Comment by J-Moravec** [comment]
This is exactly what I am talking about, except the weird bug. But that is not really what bothers me.

The bug with infinite hang happens with:
```
prefetch XXX --output-directory somedir
fastq-dump XXX --output-directory somedir
```
Normally, `*-dump` outputs some connection messages, but when I run it like this, it just hangs and does not do anything apparently.

Still, while a possible bug, it is not relevant for my project. I want to point `*-dump` to previously downloaded files by `prefetch`. The reason for this is that the `prefetch` does have an `--output-directory` so either it should be possible or the `--output-directory` from `prefetch` should be removed, because if `*-dump` takes only current dir or pre-configured user repository, it doesn't make sense that the `prefetch` can download it into a random specified dir.

Of course this can be temporarily solved by going into `somedir` and running `prefetch` and `*-dump` from there, but this is not ideal solution.

**Comment by klymenko** [comment]
Now you can run:
`prefetch XXX --output-directory somedir`
`fastq-dump somedir/XXX` or `fasterq-dump somedir/XXX`
