### ISSUE TITLE
How can i change the download folder when the disk quote exceeded and keep the files which have downloaded?  

### ISSUE THREAD

**Issue by wkl1990** [ncbi/sra-tools#51]
I have downloaded part of my request dataset, but it is too big to download in the defalt folder. I want to change the folder but it attempt to remove all files which i have downloaded. How could i keep the files and change the folder?

**Comment by kwrodarmer** [comment]
Did you move the files first?

This is a likely action, and you may be surprised that `vdb-config` isn't happy about it. The reason is that when you set a local workspace directory, **the toolkit** intends to own it and modify it. When it is told to use a directory that isn't empty, it will never know whether it is using/overwriting/deleting something that you put there manually and that it should not modify. It is happy if you give it an empty directory.

That said, if you already moved the directory, you can just update the path using the `vdb-config` command line option to set the path. I suggest that for privacy you run the tool `test-sra` and send the output to sra-tools@ncbi.nlm.nih.gov (rather than posting it here) and we can give you the exact command you need to update things.

**Comment by klymenko** [comment]
@wkl1990 , do you still need to solve this issue?
