### ISSUE TITLE
fasterq-dump --split-files not splitting into reads

### ISSUE THREAD

**Issue by BioDebojyoti** [ncbi/sra-tools#541]
Hi,
I am trying to download SRR12565266 using fasterq-dump with "--split-files" but it doesn't give files based on reads. 
`fasterq-dump --split-files --threads 16 --outdir  temp SRR12565266`

"fasterq-dump" version 2.11.0

The https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12565266 upload command does however seem to suggest that one would expect files similar to the ones listed below

--read1PairFiles=CD15P_S3_L004_R1_001.fastq.gz 
--read2PairFiles=CD15P_S3_L004_R2_001.fastq.gz 
--read3PairFiles=CD15P_S3_L004_I1_001.fastq.gz

Am I understanding/using "--split-files" incorrectly or is there some other part that I am missing? 

Any help appreciated!!

**Comment by wraetz** [comment]
If you look at the accession with 'vdb-dump SRR12565266 -R1' ( this displays the first record ), you can see that this particular accession has 3 reads in this sequence : technical-biological-technical. Since fasterq-dump ignores technical reads by default, the outcome is just 1 file, because there is just 1 biological read. If you wish to see the technical reads too, you have to supply the '--include-technical' command-line switch.

**Comment by BioDebojyoti** [comment]
Thank you, @wraetz .
