### ISSUE TITLE
Single-end files that are paired-end

### ISSUE THREAD

**Issue by Miguelb92** [ncbi/sra-tools#557]
Hello everyone,

I was downloading the dataset GSE162462, and theoretically, the files are only single-end. 
I have used prefetch and fasterq-dump commands. The problem is with some of them I have 2 fastq files (read1 and read2). 
I have used one solution provided here https://www.biostars.org/p/139422/#253650 and I obtain paired-end data result for the sra files from which I have 2 fastq files and single-end from the others.

Maybe some of the files are pared-end data and the information provided in the web its not correct?

Thank you so much

**Comment by durbrow** [comment]
These sort of problems are usually caused by incorrect metadata from the submitter. Please send your question to the SRA curators at sra@ncbi.nlm.nih.gov. 

Early on in NGS, it was not uncommon to have paired-end reads concatenated into single read FASTQ files with the read layout being specified by some other means. Consequently, SRA allows submitters to specify the read layout of their single read FASTQ files. If they get it wrong, well … The curators can get it fixed.
