### ISSUE TITLE
fasterq-dump.2.11.0 err: terminated in loop_nr

### ISSUE THREAD

**Issue by pkubgmlixs** [ncbi/sra-tools#561]
Dear sra-tools,

I tried to decompressing dbGaP sra using fasterq-dump with ngc key file provided. I'm stuck with error "2021-12-02T03:16:44 fasterq-dump.2.11.0 err: terminated in loop_nr #36.34573 for SEQ-ROWID #245991506" and have no idea how to get through this. Any help will be appreciated.

The command I used is: 
`time (fasterq-dump --ngc prj_XXX.ngc -e 40  -S -O ./fastq -t ./temp -m 1GB -p  sra/XXX_dbGaP-XXX.sra) 2>log/fasterqDump.XXX_dbGaP-XXX.log`

And the error I encountered is:
```
2021-12-02T02:58:29 fasterq-dump.2.11.0 err: extract_acc2( 'sra/XXX_dbGaP-XXX.sra' ).VFSManagerExtractAccessionOrOID() -> RC(rcVFS,rcPath,rcConstructing,rcParam,rcIncorrect)
lookup :|-------------------------------------------------- 100%
merge  : 1532485769
join   :|  0.35%2021-12-02T03:16:44 fasterq-dump.2.11.0 err: row #245991506 : R[2].len(0) != Q[2].len(151)
2021-12-02T03:16:44 fasterq-dump.2.11.0 err: terminated in loop_nr #36.34573 for SEQ-ROWID #245991506
^H^H^H^H^H^H 0.39%
fasterq-dump quit with error code 3

real    18m32.018s
user    77m44.684s
sys     9m25.156s
```
Best wishes,
Kevin
2021.12.02

**Comment by wraetz** [comment]
The version of the tools 2.11.0 is not the current one. As a first try please install the latest version of sra-tools, then retry. 
A second possibility is that the accession itself may be corrupted. Run vdb-validate on the accession (with the ngc-file). If vdb-validate reports that the accession is not corrupted, please contact the ncbi-curators at 'sra@ncbi.nlm.nih.gov' This issue involves dbGap, project-id and ngc-file, because of that such a problem cannot be resolved on github.
