### ISSUE TITLE
Interleaved output for fastq-dump

### ISSUE THREAD

**Issue by standage** [ncbi/sra-tools#57]
If would be stupendous if there were an option for outputting paired-end reads in a single interleaved file, rather than two split files. The former facilitates data streaming, while the latter complicates it significantly.

**Comment by buddej** [comment]
You can accomplish this by combining the --split-files and -Z options.
I use the following options to cleanup the read names and make the output look a little more like a normal fastq (/1 or /2 at the end of the read name. + before qual line)

`fastq-dump --split-files --defline-seq '@$ac.$si.$sg/$ri' --defline-qual '+' -Z SRR######

**Comment by standage** [comment]
Wow, I guess I need to read the manual. Thanks again!

**Comment by millerh1** [comment]
Would this lead to issues when you have an unmated read in a spot? Would that break the interleaving?

**Comment by millerh1** [comment]
So this solution is actually somewhat dangerous because orphaned reads are also sent to `stdout`. This means that the resulting fastq file is NOT interleaved if an orphaned read is encountered, since that breaks the pattern of R1, R2, R1, R2, etc. For an example of this, check out [ERR011087](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR011087). 

```
prefetch ERR011087
fastq-dump --split-files --defline-seq '@$ac.$si.$sg/$ri' --defline-qual '+' -Z ERR011087 > ERR011087.fastq
```

In this run, all the orphaned reads happen to be at the end which mean that while `head -n 24` gives:

```
@ERR011087.1./1
TTCANATATGGAAAAACAGGGAGCGGAAATCACGTTACTTGCGT
+
hhhh;XhZhhh[HI[LSTbhPRZL\XRJOSUNO[PYLOU]SMQJ
@ERR011087.1./2
ATCATCGGAAAAGGCAGGCTGTCCATGCTCCAACCGGTTAATGA
+
SYhWUhhhOMWURZf`_VhYTMNQ@UQPPO\EOFQFO?JJIDJF
@ERR011087.2./1
ACAANCTTCTCAATCTCGGTCTTTTTCTTGGGGAACTCCTTGGT
+
_^ZJ;hhhhhheJehh_X[PUh[[acJaUJS]PHDDSBLOWGN@
@ERR011087.2./2
AATAGAACTTGGAACACAGTCCTTGGATGAATACCGTTCTTTTG
+
@JhhhSMh_hhhRbhdYK_IOS]WVXXHgOPTMNQPN_NTPVXP
@ERR011087.3./1
ATCANTTTCACTCAAACCATTAATAACATCTACCTGGTTCTTCA
+
QahZ;hhhhhhhfYWbba[d^hVhNbPdhShGS[VZQPQJeTNN
@ERR011087.3./2
GGCTTCGATTCGTTTAAGGGTGATCAAGAGGCAATCATCAGAAA
+
ZUhhhe[VfhWb^hWEVO\V_\@[VIQMLIKSDNHMQSKCSHCH
```

`tail -n 24 ERR011087.fastq` gives:

```
@ERR011087.11640971./2
CCAGATCGTGCGTGATGGAAGCTGATGGGGAAGGACAGGACAAC
+
MhhhhTAhVh=RhhWhhhNXbEhhGh\hhVLThQDZLNWHHFBM
@ERR011087.11640972./2
GACTTGAAAGGGATGGACTGGAGTTGAATGGACTCGAATGAAAT
+
hhhhhhhhhhhhhhhhhhhhhghhhhdRhhha`hXhYhh`RYOe
@ERR011087.11640973./2
CACACACACAAAACACCCCCAACAACCCACACCACAAAAACCAA
+
CEACWhch@Ghhhhh]ehhchVdhh]hEhhhQhchhPQhhhDFh
@ERR011087.11640974./2
GGGGGCATGGGTAGGATTAACGACATAGATTCAAACGATACAAG
+
hhhhhhhhhhhIhhhZhhgMh]_fX\PhThb\]PNYdTQS[SM_
@ERR011087.11640975./2
CAAAAAAAAAAAAACAGAAAAACCCCATTTTTTTAAAACTGGGC
+
hhh\hhh_hhhhh^I?G@SdRQcXdCHKWOALTOUZ\JEGHNFD
@ERR011087.11640976./2
CAGGAATTCTGTAGGATTTTCCACTCTTTTTCCTAGGGCAGTCA
+
K\NUZhQZUGh]\FY>ECfMIMKTSJPUEMLFEIH=HF>>KHBF
```

This shows that the file is not interleaved correctly. This would also occur if you do any filtering in `fastq-dump`. I spent the better part of today trying to find a work-around for this, but to no avail. Hopefully someone will find a way some day. Realistically, it might be as simple as adding an option to `fastq-dump` that would allow you to prevent any orphaned reads from being sent to `stdout`.
