### ISSUE TITLE
vdv-config -I on macosx not running 

### ISSUE THREAD

**Issue by segalmicrobiomelab** [ncbi/sra-tools#573]
Hi all, sorry of this has been asked, but seems to be a weird issue since I have run the SRA tools on this computer before. 
I downloaded the macosx 64 folder (sratoolkit.2.11.3-mac64) and put it to where I wanted to run. 
I cd into "bin" in terminal then ran: "bash vdb-config -I", I also tried sudo'ing the command, but it doesn't run either. I am running a 6 year old i5 iMac so I don't think the M1 Apple Silicone transition is the trouble. 

Error:
"vdb-config: vdb-config: cannot execute binary file" 

Thank you, Ben 

iMac (Retina 5K, 27-inch, Late 2015)
3.2 GHz Quad-Core Intel Core i5
32 GB 1867 MHz DDR3
Macintosh HD
AMD Radeon R9 M390 2 GB

macOS Big Sur 
Version 11.6 

Edit: I also want to mention that I had gotten the SRAtoolkit to work prior (used it for another project). However, it's this version that I am having trouble with - I removed the older version

**Comment by durbrow** [comment]
I am not sure exactly what the problem is, but on macOS (and Linux too), the current directory is not usually searched for executables. If you `cd` to the directory of an executable, typing the bare name of the executable will not usually execute it, you need to use `./` in front of the name.

Try this:
```
cd <directory where you put the toolkit binaries>
./vdb-config -i
```
