### ISSUE TITLE
"self NULL while reading file within network system module" when testing

### ISSUE THREAD

**Issue by brianpenghe** [ncbi/sra-tools#577]
I followed [This instruction](https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit) to install sratools but got these outputs:
```
(base) ubuntu@ph12:~/tools/sratoolkit.2.11.2-ubuntu64$ fastq-dump --stdout SRR390728 | head -n 8
2022-01-22T23:26:51 fastq-dump.2.11.2 int: self NULL while reading file within network system module - cannot Make Compute Environment Token
2022-01-22T23:27:02 fastq-dump.2.11.2 int: self NULL while reading file within network system module - cannot Make Compute Environment Token
@SRR390728.1 1 length=72
CATTCTTCACGTAGTTCTCGAGCCTTGGTTTTCAGCGATGGAGAATGACTTTGACAAGCTGAGAGAAGNTNC
+SRR390728.1 1 length=72
;;;;;;;;;;;;;;;;;;;;;;;;;;;9;;665142;;;;;;;;;;;;;;;;;;;;;;;;;;;;;96&&&&(
@SRR390728.2 2 length=72
AAGTAGGTCTCGTCTGTGTTTTCTACGAGCTTGTGTTCCAGCTGACCCACTCCCTGGGTGGGGGGACTGGGT
+SRR390728.2 2 length=72
;;;;;;;;;;;;;;;;;4;;;;3;393.1+4&&5&&;;;;;;;;;;;;;;;;;;;;;<9;<;;;;;464262
fastq-dump was killed (signal 13 SIGPIPE)
```
Any ideas why this happened?

**Comment by durbrow** [comment]
> `fastq-dump was killed (signal 13 SIGPIPE)`

This is because of what `head` does. It reads some number of lines from stdin and quits. When it quits, its end of the pipe closes and the writer of the pipe recieves a `SIGPIPE` signal from the OS. Try running:
```
fastq-dump --stdout --maxSpotId 2 SRR390728
```
You should get the same output plus a message about the number of spots read and written, and no message about `SIGPIPE`.

As for the messages about `cannot Make Compute Environment Token`, I'm not sure why you are seeing that, but it is not a fatal error. And if you are not running inside AWS or GCP, you can safely ignore it.
