### ISSUE TITLE
faster-dump missing maximum spot id 

### ISSUE THREAD

**Issue by Tiggax** [ncbi/sra-tools#655]
Is there a option in `fasterq-dump` similar to `fastq-dump`'s  -X option?
I cannot seem to find it in the `fasterq-dump` help, or on the internet.

**Comment by wraetz** [comment]
There is no such option ( for now ). Because of the way fasterq-dump works ( it creates first a large lookup-table - then joins it with the sequence table ) you would still have to wait for the lookup-table to be created ( ~50% of the total runtime), even if you just ask for 5 spots. But we are planning to (re) introduce it in the future.
