### ISSUE TITLE
vdb_config Disallows Choosing Folder with Files In It

### ISSUE THREAD

**Issue by DarioS** [ncbi/sra-tools#66]
If a folder is chosen with a file already in it, a message is shown "the given location is not empty" and the only option is OK. There's no indication that the user's choice wasn't accepted nor that this is an error message rather than simply an informational warning message. If I choose another folder that only contains folders, the software does not complain. Why the dislike for files but not for folders? It seems pointlessly annoying.

**Comment by kwrodarmer** [comment]
It is not pointless, and we actually went to the trouble of putting this check in there for a good reason.

The directory that we ask you to provide is intended to be 100% _ours_, such that we have the ability and authority to create and destroy files as needed for operation. When you point us at a directory with other files in it, we can't be sure if we have the authority to delete them or overwrite them (in the case of a name conflict).

These are command-line tools, and you seem to be uncomfortable with that. Absent the greater flexibility of a GUI, we cannot really engage in a dialog with the user about who owns what in the workspace when it is created. To avoid having the dialog entirely as well as any dangerous misunderstandings after the fact, we opted for insisting that you give us a directory empty of files so that accidents could not occur.
