### ISSUE TITLE
Connection to the database failed using prefetch 

### ISSUE THREAD

**Issue by ntekasi** [ncbi/sra-tools#690]
Hi, the last couple days I am getting the same error when I am trying to prefetch or fasterq-dump sra files. It seems that similar errors have been reported for older versions of the sra-toolkit but I think I am using the latest version. I tried to re-run vdb-config as it was suggested for other errors but the problem persists!
Any ideas?
Thank you in advance!

prefetch.2.8.0 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -9984 ( X509 - Certificate verification failed, e.g. CRL, CA or signature check failed )
2022-08-04T13:51:52 prefetch.2.8.0 sys: mbedtls_ssl_get_verify_result returned 0x8 (  !! The certificate is not correctly signed by the trusted CA  )
2022-08-04T13:51:52 prefetch.2.8.0 err: path not found while resolving tree within virtual file system module - 'SRR8427526' cannot be found

**Comment by stineaj** [comment]
Due to updated security at NCBI, versions of the SRA Toolkit 2.9 and older will no longer be supported. You will need to update to the latest version of the SRA Toolkit to download data from NCBI. 
The current release is available on this page. 
https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit

**Comment by ntekasi** [comment]
My bad! Thanks a lot
