### ISSUE TITLE
fasterq-dump was killed (signal 7 SIGBUS)

### ISSUE THREAD

**Issue by arcarneiro** [ncbi/sra-tools#698]
Hi, 

The fasterq-dump process is getting killed with signal 7 (SIGBUS) when I try to process SRA files of 130GB. 

The SIGBUS signal is sent to a process when it causes a bus error. The conditions that lead to the signal being sent are, for example, incorrect memory access alignment or non-existent physical address. 

I tried fasterq-dump from both sratoolkit versions 3.0.0 and 2.10.5, but the result is the same.

The execution line is: fasterq-dump SRR11537947.sra -m 256000MB -e 24 -3 -S --skip-technical -O $PWD  -t /tmp

I'm using Red Hat Enterprise Linux Server release 7.9 (Maipo).

Any ideas of what is happening and how to overcome this?

Best regards.

**Comment by wraetz** [comment]
Hi,
please try to reduce the number of threads ( -e 24 to -e 6 ) or omit this option ( it defaults to -e 6 ). More than 8 threads does not give faster results ( even on machines with lots of cores ), because it exhausts the I/O bandwidth. Also try to omit the option -m 256000MB, it is not necessary ( it is just used for tuning the sorting phase ). The options -3 and -S are mutually exclusive! The tool will take the first one. The second one can be omitted.
