### ISSUE TITLE
“sratools.3.0.0” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by Chrisdoan9** [ncbi/sra-tools#702]
Hi all,

When I run `fastq-dump --stdout -X 2 SRR390728`. I got the error above with the message: Killed: 9. Would anyone please tell me how to fix this? Thank you so much!

**Comment by durbrow** [comment]
What operating system are you using?

**Comment by Chrisdoan9** [comment]
Hi durbrow. I use Mac OS Monterey. Version 12.1.

**Comment by durbrow** [comment]
This has to do with developer identification and code signing. At this time, we don't sign our tools. We will eventually, once we've figured out how to set up our build systems to do it. Since the vast majority of our usage is on some kind of Linux and there are ways around this issue, this isn't high on our priority list.

The "proper" way to work around this is [this](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac). If Apple's way doesn't work or something, try this. Go to System Preferences / Security & Privacy / General and allow apps from "App Store and identified developers". Then, whenever you get that message about "the developer cannot be verified", go to System Preferences / Security & Privacy / General and there should be a message about allowing the app/executable that you just tried to open.

**Comment by Chrisdoan9** [comment]
Thank you so much! I forgot about that solution.
