### ISSUE TITLE
prefetch.2.9.1 sys: connection failed

### ISSUE THREAD

**Issue by SKarr07** [ncbi/sra-tools#714]
hello, since last week (september 8th) I've been having a previously reported issue:

prefetch.2.9.1 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -9984 ( X509 - Certificate verification failed, e.g. CRL, CA or signature check failed )

Is this still a problem of network connection?

**Comment by stineaj** [comment]
Please update to the latest release of the toolkit and let us know if that addresses your problem. It looks like the error you are seeing is due to the announcement below (retirement of expired certificates).

https://github.com/ncbi/sra-tools 
August 4, 2022 : Security Update

Due to updated security at NCBI, versions of the SRA Toolkit 2.9.6 and older will no longer be able to connect to the NCBI data location service. We advise impacted users to update to the [latest version](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) of the SRA Toolkit.
