### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by map2085** [ncbi/sra-tools#73]
`fastq-dump` has an option  --disable-multithreading

But there is no other option for controlling multi-threading (e.g. specifying the number of threads to use), nor can I find any reference to multithreading in SRA toolkit documentation.

How do we specify the number of threads to be used for multi-threading in `fastq-dump`?

The existence of "[parallel-fastq-dump](https://github.com/rvalieris/parallel-fastq-dump)" is confusing, and leads me to wonder what kind of parallelism is already incorporated into `fastq-dump`.  This other user is claiming substantial speed increases using a data-parallel approach.  This suggests that the multithreading capabilitity of `fastq-dump` is not used for data paralellism.  How is multithreading used by `fastq-dump`?

**Comment by kwrodarmer** [comment]
The tool `fastq-dump` from the SRA Toolkit is probably the oldest tool we have. It stays alive due to the large number of arcane functions it has acquired over the years, many of them during the 1000-genomes project.

The author of parallel-fastq-dump is driving the fastq-dump tool directly on multiple threads, which is one approach. Another approach would have been to use our `ngs` API for Python that would allow very simple generation of fastq, and as multi-threaded as you want by means of slicing.

So to answer how multi-threaded in `fastq-dump`, the answer is not very much. It uses VDB in essentially a single-threaded mode. VDB internally uses multiple threads in support of the single cursor, but fastq-dump could be much more parallel, especially if people don't get too excited about read names.

**Comment by map2085** [comment]
OK.  I was not aware of the near-obsolete status of `fastq-dump`.  Looking around online, it is the only tool mentioned or apparently used to get .fastq from .sra.

The `ngs` github page has no documentation or description about the functions contained in the API.

And the [NCBI website](https://www.ncbi.nlm.nih.gov/home/develop/api.shtml) does not mention the existence of `ngs` or other relevant APIs (except blast, entrez, pubchem, pubmed).

Where can I find documentation, examples, or anything else that could help me write some simple python script for generating .fastq from .sra with parallelism?

The "examples" directory within the "ngs-python" has no README and the python files have no comments.  It is not straightforward from the examples how to load reads (paired or single) from the .sra and print to .fastq.

Thank you.

**Comment by kwrodarmer** [comment]
There are examples within `ngs` that demonstrate retrieving fastq data. As to a howto that includes multi-threading, we kind of figure that is not our job to show. But we'll consider adding such an example...

The takeaway from my comments was intended to be that fastq itself is archaic, and we need to stop putting effort into this rather 1990's mode of processing data.
