### ISSUE TITLE
fastq-dump sys: no error-location header not found on relocate msg

### ISSUE THREAD

**Issue by ccmeth** [ncbi/sra-tools#734]
Hi developers,

Thanks a lot for providing such a powerful tool for us. However, one "possible" issue raised as can been seen from the figure below. Such case does not appear before, in the same equipment. Besides, the fastq files seem to be generated normally. What's the possible reason behind such phenomenon?

![image](https://user-images.githubusercontent.com/54224100/200539607-1d8bb99f-d48e-4abc-855c-dea430e141df.png)

Hao

**Comment by wraetz** [comment]
The problem is *.sra ! The fastq-dump tool does not perform globbing. The solution is to write a shell-script around fastq-dump. There is another problem with your approach: a SRA-accession is NOT a file. It is a directory with files in it. If you just pick the file or copy the *.sra files into a different location -  the tool will pull in what is missing over the network. The right approach is to prefetch all the accessions you need ( they will be directories next to each other ) and pass the path to each of these directories to the tool one by one.

**Comment by klymenko** [comment]
Download the latest toolkit.
