### ISSUE TITLE
Fasterq-dump outputs a single file for paired-end reads

### ISSUE THREAD

**Issue by JoshLoecker** [ncbi/sra-tools#753]
Hi,
I am trying to get two files for a paired-end read. The SRR code is: SRR12873784. 

I saw #399, and executed the command: `vdb-dump SRR12873784 -R1 -C READ_TYPE` with the output output of:
```
READ_TYPE: SRA_READ_TYPE_BIOLOGICAL, SRA_READ_TYPE_BIOLOGICAL
```

The command I am using includes more threads, but the basics is as follows:
```
fasterq-dump --split-files --progress SRR12873784/SRR12873784.sra  # I have prefetched the SRR file
```

Fasterq dump version:
```
$ fasterq-dump --version
"fasterq-dump" version 3.0.0
```

The result of the above command is a single fastq file (i.e., with a pre-fetched SRR file)
However, running the fasterq-dump command WITHOUT prefetching gives two files, as expected

Does anyone have an idea of why this may be? 
Thanks for any help!

**Comment by wraetz** [comment]
I just run your command on a prefetched accession - and it did give me 2 files. Sorry - I cannot reproduce your problem. Please try to use your prefetched accession like this: "fasterq-dump ./SRR12873784" instead of "fasterq-dump SRR12873784/SRR12873784.sra". Also verify if you prefetched accession is complete/correct :
