### ISSUE TITLE
fastq-dump  too slow

### ISSUE THREAD

**Issue by weizhiting** [ncbi/sra-tools#78]
HI!
I download my sra file through prefetch and the sra file is about 60GB. But when i using fastq-dump to transfer it to fastq, at the beginning,it was very fast,but then it becomes slower and slower.How can i solve it ?Thanks!

**Comment by osris** [comment]
can you send the accession?
thanks,
-Chris
________________________________

**Comment by weizhiting** [comment]
accession: SRR5450996 SRR5450998 SRR5450997!Thanks!

**Comment by osris** [comment]
Hi, I can successfully dump these. They are huge. The SRA archives are between  40Gb and 70Gb. Resulting uncompressed fastq over 400Gb for SRR5450996 . Fastq-dump is slow because it’s a lot of data to transfer.

There are a lot of ways to access SRA archive files. fastq-dump is only 1 of them.
-Chris


*********************************
Christopher O’Sullivan PhD
Sequence Read Archive
NCBI/NLM/NIH
osulliva@ncbi.nlm.nih.gov
*********************************

**Comment by viv3kanand** [comment]
@osris Wow. I hope that doesn't help anyone. Thanks to you lol.
