### ISSUE TITLE
fastq-dump --split-files returns only one file for paired-end sample

### ISSUE THREAD

**Issue by sofimsofim** [ncbi/sra-tools#797]
I have downloaded SRR files (using prefetch). It says on the ncbi website that all of my runs have 2 reads per spot, but when I for example run [SRR8743324](https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&page_size=10&acc=SRR8743324&display=metadata) with:
`./bin/fastq-dump --split-files SRR8743324`, I only get one single fastq output. I only get SRR8743324_1.fastq, when I am expecting SRR8743324_1.fastq and SRR8743324_2.fastq. 

What am I doing wrong?

I am using sratoolkit version 3.0.2

**Comment by wraetz** [comment]
You are doing nothing wrong. The accession contains only 1 biological read. You can verify with vdb-dump SRR8743324 -R1. The accession has one biological read starting at position 0 with a length of 51 bases. The 'second' read is technical, starting at position 51 with a length of 0 bases. Because of this, fastq-dump/fasterq-dump can produce only one output-file in split-mode. If that is not what you are expecting, you should contact NCBIs help-desk about it.
