### ISSUE TITLE
Parallel fastq-dump

### ISSUE THREAD

**Issue by apredeus** [ncbi/sra-tools#82]
Hello, 

in the newest sra tools I've found --disable-multithreading option, but no options for parallel execution. Can it run in parallel? If not, what's the option for? 

Also, would it be possible to create output options that would re-create correct Illumina read names (with flow cell coordinates and read number identifiers), and lose the useless third line of the fastq file that makes the output bigger by 25% for no reason?

**Comment by kwrodarmer** [comment]
`fastq-dump` does run on multiple threads by default. It processes data serially, but the entire process of blob retrieval and decompression runs on parallel threads. The option is to cause the entire system to run single-threaded, if multi-threading is suspected of causing issues.

So let me see if I understand your comments:
1. recreating correct Illumina read names is impossible because we don't store them. The official read names once submitted to the SRA are the ones given. There are many reasons for this, e.g. because the names themselves are useless other than for identifying mates, but also because names are free form and people put just about everything up to kitchen recipes in them, making them impossible to reliably process. I'd be happy to hear why you think you need them, but would wager that you don't.
2. To "lose" the useless 3rd line of fastq would break the format, such as it is. The format itself is very loosely defined and heavily abused, and causes an almost endless amount of work for NCBI to deal with all of the off-flavors we receive. So as admittedly useless as the line is, it cannot be altered without breaking 100% of the software that reads fastq.

A bigger question is, what do you really *need* fastq for, and why not look for a better way to get at the data? `fastq-dump` is one of our most heavily used tools, but we would much rather see people start using information rather than formats, and especially text formats.

The utility of quality values has been hotly debated. But in general, quality values add no information that is not already present in coverage statistics, and where they diverge, a high coverage statistic is always more reliable than the qualities. Where the coverage is insufficient to make a deterministic call, then the qualities don't actually help anyone; if you don't have enough coverage to support a claim, then it's just bad science and you need to collect more data.

So if we want to improve efficiency, it's not through increasing the threads or dropping lines of fastq - it's going to be dropping qualities (fully 80% of a typical SRA object) and dropping fastq altogether.
