### ISSUE TITLE
Clarification on fasterq-dump usage

### ISSUE THREAD

**Issue by apredeus** [ncbi/sra-tools#856]
Dear SRA team, 

Could you please clarify this part of `fasterq-dump` manual:

> An accession is not a file, it is a container of files. Depending in the data submitted to NCBI, the container will have just one file or many files. Because of that, best practice is to always specify a directory.
> 
> example:	$fasterq-dump /home/user/data/SRR000001
> incorrect:	$fasterq-dump /home/user/data/SRR000001/SRR000001.sra

How can there be many files per one SRR? Isn't it true that 1 run is _always_ associated with 1 SRA file in the database? 

What is the correct way of running `fasterq-dump` on a SRA file if I don't want to use `prefetch`? (it doesn't agree with out network unfortunately, and simple `wget` tends to be a lot more transparent, especially in case when download was unsuccessful). 

Finally, when do options `--bufsize/--curcash/--mem` matter? Do they change performance, and when should one use values different from default? 

Thank you in advance

**Comment by wraetz** [comment]
How can there be many files per one SRR? Yes there can! For a subset of about 20% of the SRA the accessions are so-called cSRA's which were submitted as BAM-files. These accessions do not contain the actual bases, but only the name of a reference and a position on this reference. In other words these accessions are not self contained. If you would take these accessions to a computer without internet access, fastq-dump/fasterq-dump would fail. That means for a tool to produce the bases in FASTQ/FASTA format, the references ( which are separate files ) have to be accessible. If you use a command line labeled as incorrect above, the tool will use the internet to access the missing references. Because of that it is recommended to always give a directory, never a file to the tool. This will always work! And it will be faster too!

If you do not want to use prefetch, just use the bare accession. That only works if you have internet access. But doing this is slower than doing prefetch + fasterq-dump.

Finally --bufsize/--curcache/--mem are for fine-tuning speed and memory usage. The performance and memory usage will change - sometimes only a little and sometimes more ( it depends on the internal structure of the SRR ). We have used them to find the best defaults. You can ignore them.

**Comment by apredeus** [comment]
Could you please provide a run ID that would be an example of this? I'm downloading (many) 10x datasets from ENA ftp (or, failing that, from Amazon - I get URLs using ENA's API), and quite a few of them were originally submitted (to GEO) as Cell Ranger BAM files. Some of these samples are present as fastq files at ENA, but some are decoded incorrectly (into a single-end fastq file), so I have to get the original SRA archive and de-code them with "technical" reads etc. However, from what I can tell, the URL generated always points to a single file, which I was always able to de-code using `fastq-dump`. I'm switching to `fasterq-dump` to save time, and was confused by the part in the manual that I quoted above.

**Comment by wraetz** [comment]
You are free to use fastq-dump or fasterq-dump, the point regarding file vs. directory applies to both ( it is a property of the library which both tools use ). I think you want to use fasterq-dump because it is faster, but it is faster only in the combination of prefetch+fasterq-dump. If you do something else: it might work ( but slower than prefetch+fasterq-dump ). If you are choosing ENA to download the accession, there is a 20% chance that you are getting a cSRA as a single file ( and the tool has to get to the references via internet ). In a nutshell: does it work? YES, is it fast? NO. without internet access? NO. The point about not working without internet access might be not relevant to you, but there are institutions that insist on doing internal work on computers hat are isolated from the internet. An short example of a cSRA: SRR341578.

**Comment by wraetz** [comment]
By the way, I came across some accessions before where customers said: "According to the meta-data this should be paired, but if I run the tool it comes out as a single file - not matter what option I choose". The story here is that some accessions are reported as paired when submitted - but the actual data that has been submitted is not. It might happen that you download the SRR-file, run fastq-dump/fasterq-dump and you still do not get paired data. In this case you report this to NCBI at "sra@ncbi.nlm.nih.gov".

**Comment by apredeus** [comment]
Thank you for your answers! The situation with a reference file is indeed interesting. Is there any way to learn that a certain SRR file is a cSRA, e.g. with something like `vdb-validate`? 

As for single-end vs. paired-end: lots of single cell data has a peculiar format of BAM file, which looks single-end, but has "technical" read information in the tags. However, most SRA files _do_ have the technical reads in them, though - however, ENA still _sometimes_ generates single-end reads. E.g. here:

https://www.ebi.ac.uk/ena/browser/view/SRR10129807 - only one fastq file is reported

however, here

https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR10129807&display=metadata

one can clearly see that SRA file does contain 3 reads. 

That's why I go ENA route: if there are paired-end fastq files, it's a lot more convenient just to download those, but if not, getting the SRA and decoding is the only way to get the correct set of reads.

**Comment by wraetz** [comment]
We have a new tool: sra-info in the pipeline. This tool will be able to answer questions like: "does this accession need references?" or "how many reads are in this accession?" I think it will be available in our next release of the toolkit.

**Comment by apredeus** [comment]
Great. I have a list of some 60,000 SRR accessions that are 10x and have to be _at least_ paired-end. I can run the tool on all of them and report the bad apples :) 

For now, thank you for your help.

**Comment by wraetz** [comment]
As for SRR10129807: if you run "vdb-dump SRR10129807 -R1" - you can see that this run has indeed 3 reads, but only one of them is labeled as biological. The first and last reads are technical. That is why ENA has only one FASTQ-file ( the biological one )
