### ISSUE TITLE
Fastq-Dump unusably slow, exceeds walltimes.

### ISSUE THREAD

**Issue by ATpoint** [ncbi/sra-tools#87]
I feel the need of opening another issue complaning about the speed or fastq-dump.
We downloaded WGS data from dbGaP, e.g. SRR598763, several TB in total. I understand that these files can be hugh, SRR598763 is 93G, but now after 24h only 12% of that file has been converted to fastq (fq-dump-2.8.2 --gzip --split-3). That means that the entire conversion will take 1 week, which is unacceptable. The cluster we have access to does not allow these ridiculous walltimes. Is there a way to speed this up? Given the size of the data, I cannot store all of them locally and convert them there. Could you please provide a solution? Is it somehow possible to split large sra into smaller parts?

Thank you!

**Comment by kwrodarmer** [comment]
Of course! Just create a script that first queries for the number of rows in the object, e.g.
`NUM_ROWS=$(vdb-dump SRR598763 -R1 -CMAX_SPOT_ID -fcsv)`

You should get NUM_ROWS = 1,191,110,908.

Then, divide the number of rows evenly across some number of jobs and assign each job a range to extract, e.g.
`fastq-dump -Z SRR598763 -N $MIN -X $MAX > SRR598763.slice-$N.fastq`

and then you can stitch them all together and start processing fastq!

On the issue of processing fastq, if you are looking for efficiency, maybe you could consider looking for alternatives that aren't as arcane and retro? Just a thought.

**Comment by kwrodarmer** [comment]
You can also use `vdb-dump` to dump fastq, or you can use the NGS API from Python, Java or C++ to access the reads directly and not have to go through the print conversion.

**Comment by kwrodarmer** [comment]
Most of the software that requires FASTQ can only make use of the FAST(a) portion. Qualities are basically only used to make a cutoff type decision, which requires one bit in most cases rather than the 8 we have to dedicate to it. But more importantly, quality values do not exhibit a strong correlation with actual confidence in the correctness of the base calling, which is instead validated by the evidence that comes from alignment depth.

Qualities are often cited as being necessary and/or useful to make decisions when there is insufficient evidence to make a call from depth alone, but in this case we're practicing Voodoo and not Science. Science must be based upon evidence, and quality values should be used as a substitute.

**Comment by ATpoint** [comment]
Cool, thanks a lot for these suggestions!
But what do you mean by retro? Is there a better and more efficient way of getting these data than prefetch-fastqdump?

**Comment by kwrodarmer** [comment]
Ah, very glad you asked!

The community continues to use tools that are requiring fastq as input, yet a decade ago the SRA was designed to allow people to get at their data directly, rather than going through fastq. It's the tools that are largely behind.

Consider this - I assert that you don't need qualities for reasons given above. When you prefetch a typical SRA object, 80% of the storage and network bandwidth (and time) are dedicated to qualities alone, and they're essentially useless. If you used an API-based method, such as the NGS API, you'd get direct access.

Tools that support SRA directly include HISAT2 and the NCBI version of GATK.

**Comment by ATpoint** [comment]
One last question for the future. I read on multiple occasions (incl. the Biowulf documentation) that GPFS is often slowed down notably by random access, and fastq-dump uses random access. Is there any recommendation on how to optimize performance on GPFS-operated clusters?

**Comment by kwrodarmer** [comment]
I have no recommendation for today, but we are working on a piece of caching software that may help in that regard, at least for cases of multiple access.

**Comment by taltman** [comment]
> It's the tools that are largely behind.

It could be due to a lack of documentation about the .sra/VDB format, and the APIs. Perhaps I am looking in the wrong places, but I cannot seem to find much documentation for the SRA-toolkit tools, let alone the other NGS-related repositories. I'd be happy to find out that my views are misplaced, and in fact there is a wealth of useful documentation for developers to learn how to get the most out of the VDB format.

**Comment by kwrodarmer** [comment]
You may be right, of course.
