### ISSUE TITLE
fasts-dump error message question

### ISSUE THREAD

**Issue by yingsun-ucsd** [ncbi/sra-tools#88]
I use fastq-dump from sratoolkit.2.8.2-1-centos_linux64 to download from GEO and sometimes got the following error message:

SRR958672
2017-07-03T19:20:55 fastq-dump.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
Read 38785330 spots for SRR958672
Written 38785330 spots for SRR958672
done with SRR958672

I did check several downloaded files and it seemed that the files were totally fine.  Did anyone have the same issue?  I just want to make sure this error message was caused by some network connection and will not affect the files I download so I don't need to check each time I see such thing.  Thanks.

**Comment by klymenko** [comment]
Messages "mbedtls_ssl_read returned -76" were caused by intermittent network errors.
But fastq-dump retried to download the same data again and succeeded.

The very last message
"Read XXX spots for YYY
Written XXX spots for YYY
done with YYY"
means that the dump was complete and successful.
In case of failure you will not see such a message but some error messages.
