### ISSUE TITLE
Error Message Fastq Dump

### ISSUE THREAD

**Issue by AndreaHobby** [ncbi/sra-tools#95]
I downloaded SRA Toolkit 2.8.2 but I am getting the message below when I try to get SRR390728. 
----
I followed these directions. https://github.com/ncbi/sra-tools/wiki/HowTo:-Binary-Installation

The error message redirects me here. https://github.com/ncbi/sra-tools/wiki

Error message below 2017-09-17T04:30:36 fastq-dump.2.3.5 err: error unexpected while resolving tree within virtual file system module - failed to resolve accession 'SRR390728' - Obsolete software. See https://github.com/ncbi/sra-tools/wiki ( 406 )

Redirected!!!

2017-09-17T04:30:37 fastq-dump.2.3.5 err: name incorrect while evaluating path within network system module - Scheme is 'https' 2017-09-17T04:30:37 fastq-dump.2.3.5 err: item not found while constructing within virtual database module - the path 'SRR390728' cannot be opened as database or table

**Comment by kwrodarmer** [comment]
Upon closure reading of the tool response, you'll see that you were **not** running from the 2.8.2 release. Instead, you're running an old installation from 2.3.5. I am guessing that you are running a distribution that has a very old toolkit installation. You should remove the old installation and install 2.8.2 so that it can be found by default.
